# Source files for IntPatch package
set(OCCT_IntPatch_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_IntPatch_FILES
  IntPatch_ALine.cxx
  IntPatch_ALine.hpp
  IntPatch_ALineToWLine.cxx
  IntPatch_ALineToWLine.hpp
  IntPatch_ArcFunction.cxx
  IntPatch_ArcFunction.hpp
  IntPatch_CSFunction.cxx
  IntPatch_CSFunction.hpp
  IntPatch_CurvIntSurf.hpp
  IntPatch_CurvIntSurf_0.cxx
  IntPatch_GLine.cxx
  IntPatch_GLine.hpp
  IntPatch_HCurve2dTool.cxx
  IntPatch_HCurve2dTool.hpp
  IntPatch_HInterTool.cxx
  IntPatch_HInterTool.hpp
  IntPatch_IType.hpp
  IntPatch_ImpImpIntersection.cxx
  IntPatch_ImpImpIntersection.hpp
  IntPatch_ImpPrmIntersection.cxx
  IntPatch_ImpPrmIntersection.hpp
  IntPatch_InterferencePolyhedron.cxx
  IntPatch_InterferencePolyhedron.hpp
  IntPatch_Intersection.cxx
  IntPatch_Intersection.hpp
  IntPatch_Line.cxx
  IntPatch_Line.hpp
  IntPatch_LineConstructor.cxx
  IntPatch_LineConstructor.hpp
  IntPatch_Point.cxx
  IntPatch_Point.hpp
  IntPatch_PointLine.cxx
  IntPatch_PointLine.hpp
  IntPatch_PolyArc.cxx
  IntPatch_PolyArc.hpp
  IntPatch_PolyLine.cxx
  IntPatch_PolyLine.hpp
  IntPatch_Polygo.cxx
  IntPatch_Polygo.hpp
  IntPatch_Polyhedron.cxx
  IntPatch_Polyhedron.hpp
  IntPatch_PolyhedronTool.hpp
  IntPatch_PrmPrmIntersection.cxx
  IntPatch_PrmPrmIntersection.hpp
  IntPatch_PrmPrmIntersection_T3Bits.cxx
  IntPatch_PrmPrmIntersection_T3Bits.hpp
  IntPatch_RLine.cxx
  IntPatch_RLine.hpp
  IntPatch_RstInt.cxx
  IntPatch_RstInt.hpp
  IntPatch_SearchPnt.hpp

  IntPatch_SpecialPoints.cxx
  IntPatch_SpecialPoints.hpp
  IntPatch_TheIWLineOfTheIWalking.hpp
  IntPatch_TheIWLineOfTheIWalking_0.cxx
  IntPatch_TheIWalking.hpp
  IntPatch_TheIWalking_0.cxx
  IntPatch_ThePathPointOfTheSOnBounds.hpp
  IntPatch_ThePathPointOfTheSOnBounds_0.cxx
  IntPatch_TheSOnBounds.hpp
  IntPatch_TheSOnBounds_0.cxx
  IntPatch_TheSearchInside.hpp
  IntPatch_TheSearchInside_0.cxx
  IntPatch_TheSegmentOfTheSOnBounds.hpp
  IntPatch_TheSegmentOfTheSOnBounds_0.cxx
  IntPatch_TheSurfFunction.hpp
  IntPatch_TheSurfFunction_0.cxx
  IntPatch_WLine.cxx
  IntPatch_WLine.hpp
  IntPatch_WLineTool.cxx
  IntPatch_WLineTool.hpp
)
