# Source files for Expr package
set(OCCT_Expr_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_Expr_FILES
  Expr.cxx
  Expr.hpp
  Expr_Absolute.cxx
  Expr_Absolute.hpp
  Expr_ArcCosine.cxx
  Expr_ArcCosine.hpp
  Expr_ArcSine.cxx
  Expr_ArcSine.hpp
  Expr_ArcTangent.cxx
  Expr_ArcTangent.hpp
  Expr_ArgCosh.cxx
  Expr_ArgCosh.hpp
  Expr_ArgSinh.cxx
  Expr_ArgSinh.hpp
  Expr_ArgTanh.cxx
  Expr_ArgTanh.hpp


  Expr_BinaryExpression.cxx
  Expr_BinaryExpression.hpp
  Expr_BinaryFunction.cxx
  Expr_BinaryFunction.hpp
  Expr_Cosh.cxx
  Expr_Cosh.hpp
  Expr_Cosine.cxx
  Expr_Cosine.hpp
  Expr_Difference.cxx
  Expr_Difference.hpp
  Expr_Different.cxx
  Expr_Different.hpp
  Expr_Division.cxx
  Expr_Division.hpp
  Expr_Equal.cxx
  Expr_Equal.hpp
  Expr_Exponential.cxx
  Expr_Exponential.hpp
  Expr_Exponentiate.cxx
  Expr_Exponentiate.hpp
  Expr_ExprFailure.hpp
  Expr_FunctionDerivative.cxx
  Expr_FunctionDerivative.hpp
  Expr_GeneralExpression.cxx
  Expr_GeneralExpression.hpp
  Expr_GeneralFunction.cxx
  Expr_GeneralFunction.hpp
  Expr_GeneralRelation.cxx
  Expr_GeneralRelation.hpp
  Expr_GreaterThan.cxx
  Expr_GreaterThan.hpp
  Expr_GreaterThanOrEqual.cxx
  Expr_GreaterThanOrEqual.hpp
  Expr_InvalidAssignment.hpp
  Expr_InvalidFunction.hpp
  Expr_InvalidOperand.hpp
  Expr_LessThan.cxx
  Expr_LessThan.hpp
  Expr_LessThanOrEqual.cxx
  Expr_LessThanOrEqual.hpp
  Expr_LogOf10.cxx
  Expr_LogOf10.hpp
  Expr_LogOfe.cxx
  Expr_LogOfe.hpp

  Expr_NamedConstant.cxx
  Expr_NamedConstant.hpp
  Expr_NamedExpression.cxx
  Expr_NamedExpression.hpp
  Expr_NamedFunction.cxx
  Expr_NamedFunction.hpp
  Expr_NamedUnknown.cxx
  Expr_NamedUnknown.hpp
  Expr_NotAssigned.hpp
  Expr_NotEvaluable.hpp
  Expr_NumericValue.cxx
  Expr_NumericValue.hpp
  Expr_Operators.cxx
  Expr_Operators.hpp
  Expr_PolyExpression.cxx
  Expr_PolyExpression.hpp
  Expr_PolyFunction.cxx
  Expr_PolyFunction.hpp
  Expr_Product.cxx
  Expr_Product.hpp
  Expr_RelationIterator.cxx
  Expr_RelationIterator.hpp
  Expr_RUIterator.cxx
  Expr_RUIterator.hpp

  Expr_Sign.cxx
  Expr_Sign.hpp
  Expr_Sine.cxx
  Expr_Sine.hpp
  Expr_SingleRelation.cxx
  Expr_SingleRelation.hpp
  Expr_Sinh.cxx
  Expr_Sinh.hpp
  Expr_Square.cxx
  Expr_Square.hpp
  Expr_SquareRoot.cxx
  Expr_SquareRoot.hpp
  Expr_Sum.cxx
  Expr_Sum.hpp
  Expr_SystemRelation.cxx
  Expr_SystemRelation.hpp
  Expr_Tangent.cxx
  Expr_Tangent.hpp
  Expr_Tanh.cxx
  Expr_Tanh.hpp
  Expr_UnaryExpression.cxx
  Expr_UnaryExpression.hpp
  Expr_UnaryFunction.cxx
  Expr_UnaryFunction.hpp
  Expr_UnaryMinus.cxx
  Expr_UnaryMinus.hpp
  Expr_UnknownIterator.cxx
  Expr_UnknownIterator.hpp
)
