# Source files for IGESGeom package
set(OCCT_IGESGeom_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_IGESGeom_FILES
  IGESGeom.cxx
  IGESGeom.hpp

  IGESGeom_Boundary.cxx
  IGESGeom_Boundary.hpp
  IGESGeom_BoundedSurface.cxx
  IGESGeom_BoundedSurface.hpp
  IGESGeom_BSplineCurve.cxx
  IGESGeom_BSplineCurve.hpp
  IGESGeom_BSplineSurface.cxx
  IGESGeom_BSplineSurface.hpp
  IGESGeom_CircularArc.cxx
  IGESGeom_CircularArc.hpp
  IGESGeom_CompositeCurve.cxx
  IGESGeom_CompositeCurve.hpp
  IGESGeom_ConicArc.cxx
  IGESGeom_ConicArc.hpp
  IGESGeom_CopiousData.cxx
  IGESGeom_CopiousData.hpp
  IGESGeom_CurveOnSurface.cxx
  IGESGeom_CurveOnSurface.hpp
  IGESGeom_Direction.cxx
  IGESGeom_Direction.hpp
  IGESGeom_Flash.cxx
  IGESGeom_Flash.hpp
  IGESGeom_GeneralModule.cxx
  IGESGeom_GeneralModule.hpp

  IGESGeom_Line.cxx
  IGESGeom_Line.hpp
  IGESGeom_OffsetCurve.cxx
  IGESGeom_OffsetCurve.hpp
  IGESGeom_OffsetSurface.cxx
  IGESGeom_OffsetSurface.hpp
  IGESGeom_Plane.cxx
  IGESGeom_Plane.hpp
  IGESGeom_Point.cxx
  IGESGeom_Point.hpp
  IGESGeom_Protocol.cxx
  IGESGeom_Protocol.hpp
  IGESGeom_ReadWriteModule.cxx
  IGESGeom_ReadWriteModule.hpp
  IGESGeom_RuledSurface.cxx
  IGESGeom_RuledSurface.hpp
  IGESGeom_SpecificModule.cxx
  IGESGeom_SpecificModule.hpp
  IGESGeom_SplineCurve.cxx
  IGESGeom_SplineCurve.hpp
  IGESGeom_SplineSurface.cxx
  IGESGeom_SplineSurface.hpp
  IGESGeom_SurfaceOfRevolution.cxx
  IGESGeom_SurfaceOfRevolution.hpp
  IGESGeom_TabulatedCylinder.cxx
  IGESGeom_TabulatedCylinder.hpp
  IGESGeom_ToolBoundary.cxx
  IGESGeom_ToolBoundary.hpp
  IGESGeom_ToolBoundedSurface.cxx
  IGESGeom_ToolBoundedSurface.hpp
  IGESGeom_ToolBSplineCurve.cxx
  IGESGeom_ToolBSplineCurve.hpp
  IGESGeom_ToolBSplineSurface.cxx
  IGESGeom_ToolBSplineSurface.hpp
  IGESGeom_ToolCircularArc.cxx
  IGESGeom_ToolCircularArc.hpp
  IGESGeom_ToolCompositeCurve.cxx
  IGESGeom_ToolCompositeCurve.hpp
  IGESGeom_ToolConicArc.cxx
  IGESGeom_ToolConicArc.hpp
  IGESGeom_ToolCopiousData.cxx
  IGESGeom_ToolCopiousData.hpp
  IGESGeom_ToolCurveOnSurface.cxx
  IGESGeom_ToolCurveOnSurface.hpp
  IGESGeom_ToolDirection.cxx
  IGESGeom_ToolDirection.hpp
  IGESGeom_ToolFlash.cxx
  IGESGeom_ToolFlash.hpp
  IGESGeom_ToolLine.cxx
  IGESGeom_ToolLine.hpp
  IGESGeom_ToolOffsetCurve.cxx
  IGESGeom_ToolOffsetCurve.hpp
  IGESGeom_ToolOffsetSurface.cxx
  IGESGeom_ToolOffsetSurface.hpp
  IGESGeom_ToolPlane.cxx
  IGESGeom_ToolPlane.hpp
  IGESGeom_ToolPoint.cxx
  IGESGeom_ToolPoint.hpp
  IGESGeom_ToolRuledSurface.cxx
  IGESGeom_ToolRuledSurface.hpp
  IGESGeom_ToolSplineCurve.cxx
  IGESGeom_ToolSplineCurve.hpp
  IGESGeom_ToolSplineSurface.cxx
  IGESGeom_ToolSplineSurface.hpp
  IGESGeom_ToolSurfaceOfRevolution.cxx
  IGESGeom_ToolSurfaceOfRevolution.hpp
  IGESGeom_ToolTabulatedCylinder.cxx
  IGESGeom_ToolTabulatedCylinder.hpp
  IGESGeom_ToolTransformationMatrix.cxx
  IGESGeom_ToolTransformationMatrix.hpp
  IGESGeom_ToolTrimmedSurface.cxx
  IGESGeom_ToolTrimmedSurface.hpp
  IGESGeom_TransformationMatrix.cxx
  IGESGeom_TransformationMatrix.hpp
  IGESGeom_TrimmedSurface.cxx
  IGESGeom_TrimmedSurface.hpp
)
