# Source files for StepBasic package
set(OCCT_StepBasic_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_StepBasic_FILES
  StepBasic_Action.cxx
  StepBasic_Action.hpp
  StepBasic_ActionAssignment.cxx
  StepBasic_ActionAssignment.hpp
  StepBasic_ActionMethod.cxx
  StepBasic_ActionMethod.hpp
  StepBasic_ActionRequestAssignment.cxx
  StepBasic_ActionRequestAssignment.hpp
  StepBasic_ActionRequestSolution.cxx
  StepBasic_ActionRequestSolution.hpp
  StepBasic_Address.cxx
  StepBasic_Address.hpp
  StepBasic_AheadOrBehind.hpp
  StepBasic_ApplicationContext.cxx
  StepBasic_ApplicationContext.hpp
  StepBasic_ApplicationContextElement.cxx
  StepBasic_ApplicationContextElement.hpp
  StepBasic_ApplicationProtocolDefinition.cxx
  StepBasic_ApplicationProtocolDefinition.hpp
  StepBasic_Approval.cxx
  StepBasic_Approval.hpp
  StepBasic_ApprovalAssignment.cxx
  StepBasic_ApprovalAssignment.hpp
  StepBasic_ApprovalDateTime.cxx
  StepBasic_ApprovalDateTime.hpp
  StepBasic_ApprovalPersonOrganization.cxx
  StepBasic_ApprovalPersonOrganization.hpp
  StepBasic_ApprovalRelationship.cxx
  StepBasic_ApprovalRelationship.hpp
  StepBasic_ApprovalRole.cxx
  StepBasic_ApprovalRole.hpp
  StepBasic_ApprovalStatus.cxx
  StepBasic_ApprovalStatus.hpp
  StepBasic_AreaUnit.cxx
  StepBasic_AreaUnit.hpp

  StepBasic_CalendarDate.cxx
  StepBasic_CalendarDate.hpp
  StepBasic_Certification.cxx
  StepBasic_Certification.hpp
  StepBasic_CertificationAssignment.cxx
  StepBasic_CertificationAssignment.hpp
  StepBasic_CertificationType.cxx
  StepBasic_CertificationType.hpp
  StepBasic_CharacterizedObject.cxx
  StepBasic_CharacterizedObject.hpp
  StepBasic_Contract.cxx
  StepBasic_Contract.hpp
  StepBasic_ContractAssignment.cxx
  StepBasic_ContractAssignment.hpp
  StepBasic_ContractType.cxx
  StepBasic_ContractType.hpp
  StepBasic_ConversionBasedUnit.cxx
  StepBasic_ConversionBasedUnit.hpp
  StepBasic_ConversionBasedUnitAndAreaUnit.cxx
  StepBasic_ConversionBasedUnitAndAreaUnit.hpp
  StepBasic_ConversionBasedUnitAndLengthUnit.cxx
  StepBasic_ConversionBasedUnitAndLengthUnit.hpp
  StepBasic_ConversionBasedUnitAndMassUnit.cxx
  StepBasic_ConversionBasedUnitAndMassUnit.hpp
  StepBasic_ConversionBasedUnitAndPlaneAngleUnit.cxx
  StepBasic_ConversionBasedUnitAndPlaneAngleUnit.hpp
  StepBasic_ConversionBasedUnitAndRatioUnit.cxx
  StepBasic_ConversionBasedUnitAndRatioUnit.hpp
  StepBasic_ConversionBasedUnitAndSolidAngleUnit.cxx
  StepBasic_ConversionBasedUnitAndSolidAngleUnit.hpp
  StepBasic_ConversionBasedUnitAndTimeUnit.cxx
  StepBasic_ConversionBasedUnitAndTimeUnit.hpp
  StepBasic_ConversionBasedUnitAndVolumeUnit.cxx
  StepBasic_ConversionBasedUnitAndVolumeUnit.hpp
  StepBasic_CoordinatedUniversalTimeOffset.cxx
  StepBasic_CoordinatedUniversalTimeOffset.hpp
  StepBasic_Date.cxx
  StepBasic_Date.hpp
  StepBasic_DateAndTime.cxx
  StepBasic_DateAndTime.hpp
  StepBasic_DateAndTimeAssignment.cxx
  StepBasic_DateAndTimeAssignment.hpp
  StepBasic_DateAssignment.cxx
  StepBasic_DateAssignment.hpp
  StepBasic_DateRole.cxx
  StepBasic_DateRole.hpp
  StepBasic_DateTimeRole.cxx
  StepBasic_DateTimeRole.hpp
  StepBasic_DateTimeSelect.cxx
  StepBasic_DateTimeSelect.hpp
  StepBasic_DerivedUnit.cxx
  StepBasic_DerivedUnit.hpp
  StepBasic_DerivedUnitElement.cxx
  StepBasic_DerivedUnitElement.hpp
  StepBasic_DesignContext.cxx
  StepBasic_DesignContext.hpp
  StepBasic_DigitalDocument.cxx
  StepBasic_DigitalDocument.hpp
  StepBasic_DimensionalExponents.cxx
  StepBasic_DimensionalExponents.hpp
  StepBasic_Document.cxx
  StepBasic_Document.hpp
  StepBasic_DocumentFile.cxx
  StepBasic_DocumentFile.hpp
  StepBasic_DocumentProductAssociation.cxx
  StepBasic_DocumentProductAssociation.hpp
  StepBasic_DocumentProductEquivalence.cxx
  StepBasic_DocumentProductEquivalence.hpp
  StepBasic_DocumentReference.cxx
  StepBasic_DocumentReference.hpp
  StepBasic_DocumentRelationship.cxx
  StepBasic_DocumentRelationship.hpp
  StepBasic_DocumentRepresentationType.cxx
  StepBasic_DocumentRepresentationType.hpp
  StepBasic_DocumentType.cxx
  StepBasic_DocumentType.hpp
  StepBasic_DocumentUsageConstraint.cxx
  StepBasic_DocumentUsageConstraint.hpp
  StepBasic_Effectivity.cxx
  StepBasic_Effectivity.hpp
  StepBasic_EffectivityAssignment.cxx
  StepBasic_EffectivityAssignment.hpp
  StepBasic_EulerAngles.cxx
  StepBasic_EulerAngles.hpp
  StepBasic_ExternalIdentificationAssignment.cxx
  StepBasic_ExternalIdentificationAssignment.hpp
  StepBasic_ExternallyDefinedItem.cxx
  StepBasic_ExternallyDefinedItem.hpp
  StepBasic_ExternalSource.cxx
  StepBasic_ExternalSource.hpp
  StepBasic_GeneralProperty.cxx
  StepBasic_GeneralProperty.hpp
  StepBasic_GeneralPropertyAssociation.cxx
  StepBasic_GeneralPropertyAssociation.hpp
  StepBasic_GeneralPropertyRelationship.cxx
  StepBasic_GeneralPropertyRelationship.hpp
  StepBasic_Group.cxx
  StepBasic_Group.hpp
  StepBasic_GroupAssignment.cxx
  StepBasic_GroupAssignment.hpp
  StepBasic_GroupRelationship.cxx
  StepBasic_GroupRelationship.hpp

  StepBasic_IdentificationAssignment.cxx
  StepBasic_IdentificationAssignment.hpp
  StepBasic_IdentificationRole.cxx
  StepBasic_IdentificationRole.hpp
  StepBasic_LengthMeasureWithUnit.cxx
  StepBasic_LengthMeasureWithUnit.hpp
  StepBasic_LengthUnit.cxx
  StepBasic_LengthUnit.hpp
  StepBasic_LocalTime.cxx
  StepBasic_LocalTime.hpp
  StepBasic_MassMeasureWithUnit.cxx
  StepBasic_MassMeasureWithUnit.hpp
  StepBasic_MassUnit.cxx
  StepBasic_MassUnit.hpp
  StepBasic_MeasureValueMember.cxx
  StepBasic_MeasureValueMember.hpp
  StepBasic_MeasureWithUnit.cxx
  StepBasic_MeasureWithUnit.hpp
  StepBasic_MechanicalContext.cxx
  StepBasic_MechanicalContext.hpp
  StepBasic_NameAssignment.cxx
  StepBasic_NameAssignment.hpp
  StepBasic_NamedUnit.cxx
  StepBasic_NamedUnit.hpp
  StepBasic_ObjectRole.cxx
  StepBasic_ObjectRole.hpp
  StepBasic_OrdinalDate.cxx
  StepBasic_OrdinalDate.hpp
  StepBasic_Organization.cxx
  StepBasic_Organization.hpp
  StepBasic_OrganizationalAddress.cxx
  StepBasic_OrganizationalAddress.hpp
  StepBasic_OrganizationAssignment.cxx
  StepBasic_OrganizationAssignment.hpp
  StepBasic_OrganizationRole.cxx
  StepBasic_OrganizationRole.hpp
  StepBasic_Person.cxx
  StepBasic_Person.hpp
  StepBasic_PersonalAddress.cxx
  StepBasic_PersonalAddress.hpp
  StepBasic_PersonAndOrganization.cxx
  StepBasic_PersonAndOrganization.hpp
  StepBasic_PersonAndOrganizationAssignment.cxx
  StepBasic_PersonAndOrganizationAssignment.hpp
  StepBasic_PersonAndOrganizationRole.cxx
  StepBasic_PersonAndOrganizationRole.hpp
  StepBasic_PersonOrganizationSelect.cxx
  StepBasic_PersonOrganizationSelect.hpp
  StepBasic_PhysicallyModeledProductDefinition.cxx
  StepBasic_PhysicallyModeledProductDefinition.hpp
  StepBasic_PlaneAngleMeasureWithUnit.cxx
  StepBasic_PlaneAngleMeasureWithUnit.hpp
  StepBasic_PlaneAngleUnit.cxx
  StepBasic_PlaneAngleUnit.hpp
  StepBasic_Product.cxx
  StepBasic_Product.hpp
  StepBasic_ProductCategory.cxx
  StepBasic_ProductCategory.hpp
  StepBasic_ProductCategoryRelationship.cxx
  StepBasic_ProductCategoryRelationship.hpp
  StepBasic_ProductConceptContext.cxx
  StepBasic_ProductConceptContext.hpp
  StepBasic_ProductContext.cxx
  StepBasic_ProductContext.hpp
  StepBasic_ProductDefinition.cxx
  StepBasic_ProductDefinition.hpp
  StepBasic_ProductDefinitionContext.cxx
  StepBasic_ProductDefinitionContext.hpp
  StepBasic_ProductDefinitionEffectivity.cxx
  StepBasic_ProductDefinitionEffectivity.hpp
  StepBasic_ProductDefinitionFormation.cxx
  StepBasic_ProductDefinitionFormation.hpp
  StepBasic_ProductDefinitionFormationRelationship.cxx
  StepBasic_ProductDefinitionFormationRelationship.hpp
  StepBasic_ProductDefinitionFormationWithSpecifiedSource.cxx
  StepBasic_ProductDefinitionFormationWithSpecifiedSource.hpp
  StepBasic_ProductDefinitionOrReference.cxx
  StepBasic_ProductDefinitionOrReference.hpp
  StepBasic_ProductDefinitionReference.cxx
  StepBasic_ProductDefinitionReference.hpp
  StepBasic_ProductDefinitionReferenceWithLocalRepresentation.cxx
  StepBasic_ProductDefinitionReferenceWithLocalRepresentation.hpp
  StepBasic_ProductDefinitionRelationship.cxx
  StepBasic_ProductDefinitionRelationship.hpp
  StepBasic_ProductDefinitionWithAssociatedDocuments.cxx
  StepBasic_ProductDefinitionWithAssociatedDocuments.hpp
  StepBasic_ProductOrFormationOrDefinition.cxx
  StepBasic_ProductOrFormationOrDefinition.hpp
  StepBasic_ProductRelatedProductCategory.cxx
  StepBasic_ProductRelatedProductCategory.hpp
  StepBasic_ProductType.cxx
  StepBasic_ProductType.hpp
  StepBasic_RatioMeasureWithUnit.cxx
  StepBasic_RatioMeasureWithUnit.hpp
  StepBasic_RatioUnit.cxx
  StepBasic_RatioUnit.hpp
  StepBasic_RoleAssociation.cxx
  StepBasic_RoleAssociation.hpp
  StepBasic_RoleSelect.cxx
  StepBasic_RoleSelect.hpp
  StepBasic_SecurityClassification.cxx
  StepBasic_SecurityClassification.hpp
  StepBasic_SecurityClassificationAssignment.cxx
  StepBasic_SecurityClassificationAssignment.hpp
  StepBasic_SecurityClassificationLevel.cxx
  StepBasic_SecurityClassificationLevel.hpp
  StepBasic_SiPrefix.hpp
  StepBasic_SiUnit.cxx
  StepBasic_SiUnit.hpp
  StepBasic_SiUnitAndAreaUnit.cxx
  StepBasic_SiUnitAndAreaUnit.hpp
  StepBasic_SiUnitAndLengthUnit.cxx
  StepBasic_SiUnitAndLengthUnit.hpp
  StepBasic_SiUnitAndMassUnit.cxx
  StepBasic_SiUnitAndMassUnit.hpp
  StepBasic_SiUnitAndPlaneAngleUnit.cxx
  StepBasic_SiUnitAndPlaneAngleUnit.hpp
  StepBasic_SiUnitAndRatioUnit.cxx
  StepBasic_SiUnitAndRatioUnit.hpp
  StepBasic_SiUnitAndSolidAngleUnit.cxx
  StepBasic_SiUnitAndSolidAngleUnit.hpp
  StepBasic_SiUnitAndThermodynamicTemperatureUnit.cxx
  StepBasic_SiUnitAndThermodynamicTemperatureUnit.hpp
  StepBasic_SiUnitAndTimeUnit.cxx
  StepBasic_SiUnitAndTimeUnit.hpp
  StepBasic_SiUnitAndVolumeUnit.cxx
  StepBasic_SiUnitAndVolumeUnit.hpp
  StepBasic_SiUnitName.hpp
  StepBasic_SizeMember.cxx
  StepBasic_SizeMember.hpp
  StepBasic_SizeSelect.cxx
  StepBasic_SizeSelect.hpp
  StepBasic_SolidAngleMeasureWithUnit.cxx
  StepBasic_SolidAngleMeasureWithUnit.hpp
  StepBasic_SolidAngleUnit.cxx
  StepBasic_SolidAngleUnit.hpp
  StepBasic_Source.hpp
  StepBasic_SourceItem.cxx
  StepBasic_SourceItem.hpp
  StepBasic_ThermodynamicTemperatureUnit.cxx
  StepBasic_ThermodynamicTemperatureUnit.hpp
  StepBasic_TimeMeasureWithUnit.cxx
  StepBasic_TimeMeasureWithUnit.hpp
  StepBasic_TimeUnit.cxx
  StepBasic_TimeUnit.hpp
  StepBasic_UncertaintyMeasureWithUnit.cxx
  StepBasic_UncertaintyMeasureWithUnit.hpp
  StepBasic_Unit.cxx
  StepBasic_Unit.hpp
  StepBasic_VersionedActionRequest.cxx
  StepBasic_VersionedActionRequest.hpp
  StepBasic_VolumeUnit.cxx
  StepBasic_VolumeUnit.hpp
  StepBasic_WeekOfYearAndDayDate.cxx
  StepBasic_WeekOfYearAndDayDate.hpp
)
