# Source files for Extrema package
set(OCCT_Extrema_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_Extrema_FILES

  Extrema_CCLocFOfLocECC.hpp
  Extrema_CCLocFOfLocECC2d.hpp
  Extrema_Curve2dTool.cxx
  Extrema_Curve2dTool.hpp
  Extrema_CurveTool.cxx
  Extrema_CurveTool.hpp
  Extrema_ECC.hpp
  Extrema_ECC2d.hpp
  Extrema_ElementType.hpp
  Extrema_ELPCOfLocateExtPC.hpp
  Extrema_ELPCOfLocateExtPC2d.hpp
  Extrema_EPCOfELPCOfLocateExtPC.hpp
  Extrema_EPCOfELPCOfLocateExtPC2d.hpp
  Extrema_EPCOfExtPC.hpp
  Extrema_EPCOfExtPC2d.hpp
  Extrema_ExtAlgo.hpp
  Extrema_ExtCC.cxx
  Extrema_ExtCC.hpp
  Extrema_ExtCC2d.cxx
  Extrema_ExtCC2d.hpp
  Extrema_ExtCS.cxx
  Extrema_ExtCS.hpp
  Extrema_ExtElC.cxx
  Extrema_ExtElC.hpp
  Extrema_ExtElC2d.cxx
  Extrema_ExtElC2d.hpp
  Extrema_ExtElCS.cxx
  Extrema_ExtElCS.hpp
  Extrema_ExtElSS.cxx
  Extrema_ExtElSS.hpp
  Extrema_ExtFlag.hpp
  Extrema_ExtPC.hpp
  Extrema_ExtPC2d.hpp
  Extrema_ExtPElC.cxx
  Extrema_ExtPElC.hpp
  Extrema_ExtPElC2d.cxx
  Extrema_ExtPElC2d.hpp
  Extrema_ExtPElS.cxx
  Extrema_ExtPElS.hpp
  Extrema_ExtPExtS.cxx
  Extrema_ExtPExtS.hpp
  Extrema_ExtPRevS.cxx
  Extrema_ExtPRevS.hpp
  Extrema_ExtPS.cxx
  Extrema_ExtPS.hpp
  Extrema_ExtSS.cxx
  Extrema_ExtSS.hpp
  Extrema_FuncExtCS.cxx
  Extrema_FuncExtCS.hpp
  Extrema_GFuncExtCC.hpp
  Extrema_GFuncExtPC.hpp
  Extrema_FuncPSNorm.cxx
  Extrema_FuncPSNorm.hpp
  Extrema_FuncPSDist.cxx
  Extrema_FuncPSDist.hpp
  Extrema_FuncExtSS.cxx
  Extrema_FuncExtSS.hpp
  Extrema_GCurveLocator.hpp
  Extrema_GGenExtCC.hpp
  Extrema_GenExtCS.cxx
  Extrema_GenExtCS.hpp
  Extrema_GGenExtPC.hpp
  Extrema_GenExtPS.cxx
  Extrema_GenExtPS.hpp
  Extrema_GenExtSS.cxx
  Extrema_GenExtSS.hpp
  Extrema_GenLocateExtCC.hpp
  Extrema_GenLocateExtCS.cxx
  Extrema_GenLocateExtCS.hpp
  Extrema_GenLocateExtPC.hpp
  Extrema_GenLocateExtPS.cxx
  Extrema_GenLocateExtPS.hpp
  Extrema_GenLocateExtSS.cxx
  Extrema_GenLocateExtSS.hpp
  Extrema_GGExtPC.hpp
  Extrema_GlobOptFuncCC.cxx
  Extrema_GlobOptFuncCC.hpp
  Extrema_GlobOptFuncCS.cxx
  Extrema_GlobOptFuncCS.hpp
  Extrema_GlobOptFuncConicS.cxx
  Extrema_GlobOptFuncConicS.hpp
  Extrema_GlobOptFuncCQuadric.cxx
  Extrema_GlobOptFuncCQuadric.hpp
  Extrema_GLocateExtPC.hpp

  Extrema_LocateExtCC.cxx
  Extrema_LocateExtCC.hpp
  Extrema_LocateExtCC2d.cxx
  Extrema_LocateExtCC2d.hpp
  Extrema_LocateExtPC.hpp
  Extrema_LocateExtPC2d.hpp
  Extrema_LocECC.hpp
  Extrema_LocECC2d.hpp
  Extrema_LocEPCOfLocateExtPC.hpp
  Extrema_LocEPCOfLocateExtPC2d.hpp
  Extrema_PCFOfEPCOfELPCOfLocateExtPC.hpp
  Extrema_PCFOfEPCOfELPCOfLocateExtPC2d.hpp
  Extrema_PCFOfEPCOfExtPC.hpp
  Extrema_PCFOfEPCOfExtPC2d.hpp
  Extrema_PCLocFOfLocEPCOfLocateExtPC.hpp
  Extrema_PCLocFOfLocEPCOfLocateExtPC2d.hpp
  Extrema_POnCurv.hpp
  Extrema_POnCurv2d.hpp
  Extrema_POnSurf.hpp
  Extrema_POnSurfParams.hpp

)
