# Source files for gce package
set(OCCT_gce_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_gce_FILES
  gce_ErrorType.hpp
  gce_MakeCirc.cxx
  gce_MakeCirc.hpp
  gce_MakeCirc2d.cxx
  gce_MakeCirc2d.hpp
  gce_MakeCone.cxx
  gce_MakeCone.hpp
  gce_MakeCylinder.cxx
  gce_MakeCylinder.hpp
  gce_MakeDir.cxx
  gce_MakeDir.hpp
  gce_MakeDir2d.cxx
  gce_MakeDir2d.hpp
  gce_MakeElips.cxx
  gce_MakeElips.hpp
  gce_MakeElips2d.cxx
  gce_MakeElips2d.hpp
  gce_MakeHypr.cxx
  gce_MakeHypr.hpp
  gce_MakeHypr2d.cxx
  gce_MakeHypr2d.hpp
  gce_MakeLin.cxx
  gce_MakeLin.hpp
  gce_MakeLin2d.cxx
  gce_MakeLin2d.hpp
  gce_MakeMirror.cxx
  gce_MakeMirror.hpp
  gce_MakeMirror2d.cxx
  gce_MakeMirror2d.hpp
  gce_MakeParab.cxx
  gce_MakeParab.hpp
  gce_MakeParab2d.cxx
  gce_MakeParab2d.hpp
  gce_MakePln.cxx
  gce_MakePln.hpp
  gce_MakeRotation.cxx
  gce_MakeRotation.hpp
  gce_MakeRotation2d.cxx
  gce_MakeRotation2d.hpp
  gce_MakeScale.cxx
  gce_MakeScale.hpp
  gce_MakeScale2d.cxx
  gce_MakeScale2d.hpp
  gce_MakeTranslation.cxx
  gce_MakeTranslation.hpp
  gce_MakeTranslation2d.cxx
  gce_MakeTranslation2d.hpp
  gce_Root.hpp
  gce_Root_1.hpp
)
