# Source files for TopOpeBRepDS package
set(OCCT_TopOpeBRepDS_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_TopOpeBRepDS_FILES
  TopOpeBRepDS.cxx
  TopOpeBRepDS.hpp

  TopOpeBRepDS_Association.cxx
  TopOpeBRepDS_Association.hpp
  TopOpeBRepDS_BuildTool.cxx
  TopOpeBRepDS_BuildTool.hpp
  TopOpeBRepDS_Check.cxx
  TopOpeBRepDS_Check.hpp
  TopOpeBRepDS_CheckStatus.hpp
  TopOpeBRepDS_Config.hpp
  TopOpeBRepDS_connex.cxx
  TopOpeBRepDS_connex.hpp
  TopOpeBRepDS_Curve.cxx
  TopOpeBRepDS_Curve.hpp
  TopOpeBRepDS_CurveData.cxx
  TopOpeBRepDS_CurveData.hpp
  TopOpeBRepDS_CurveExplorer.cxx
  TopOpeBRepDS_CurveExplorer.hpp
  TopOpeBRepDS_CurveIterator.cxx
  TopOpeBRepDS_CurveIterator.hpp
  TopOpeBRepDS_CurvePointInterference.cxx
  TopOpeBRepDS_CurvePointInterference.hpp

  TopOpeBRepDS_DataStructure.cxx
  TopOpeBRepDS_DataStructure.hpp
  TopOpeBRepDS_define.hpp

  TopOpeBRepDS_Dumper.cxx
  TopOpeBRepDS_Dumper.hpp
  TopOpeBRepDS_Edge3dInterferenceTool.cxx
  TopOpeBRepDS_Edge3dInterferenceTool.hpp
  TopOpeBRepDS_EdgeInterferenceTool.cxx
  TopOpeBRepDS_EdgeInterferenceTool.hpp
  TopOpeBRepDS_EdgeVertexInterference.cxx
  TopOpeBRepDS_EdgeVertexInterference.hpp
  TopOpeBRepDS_EIR.cxx
  TopOpeBRepDS_EIR.hpp
  TopOpeBRepDS_Explorer.cxx
  TopOpeBRepDS_Explorer.hpp
  TopOpeBRepDS_EXPORT.cxx
  TopOpeBRepDS_EXPORT.hpp
  TopOpeBRepDS_FaceEdgeInterference.cxx
  TopOpeBRepDS_FaceEdgeInterference.hpp
  TopOpeBRepDS_FaceInterferenceTool.cxx
  TopOpeBRepDS_FaceInterferenceTool.hpp
  TopOpeBRepDS_Filter.cxx
  TopOpeBRepDS_Filter.hpp
  TopOpeBRepDS_FilterCurveInterferences.cxx
  TopOpeBRepDS_FilterEdgeInterferences.cxx
  TopOpeBRepDS_FilterFaceInterferences.cxx
  TopOpeBRepDS_FIR.cxx
  TopOpeBRepDS_FIR.hpp
  TopOpeBRepDS_funk.cxx
  TopOpeBRepDS_GapFiller.cxx
  TopOpeBRepDS_GapFiller.hpp
  TopOpeBRepDS_GapTool.cxx
  TopOpeBRepDS_GapTool.hpp
  TopOpeBRepDS_GeometryData.cxx
  TopOpeBRepDS_GeometryData.hpp

  TopOpeBRepDS_HDataStructure.cxx
  TopOpeBRepDS_HDataStructure.hpp

  TopOpeBRepDS_Interference.cxx
  TopOpeBRepDS_Interference.hpp
  TopOpeBRepDS_InterferenceIterator.cxx
  TopOpeBRepDS_InterferenceIterator.hpp
  TopOpeBRepDS_InterferenceTool.cxx
  TopOpeBRepDS_InterferenceTool.hpp
  TopOpeBRepDS_Kind.hpp

  TopOpeBRepDS_ListOfShapeOn1State.cxx
  TopOpeBRepDS_ListOfShapeOn1State.hpp

  TopOpeBRepDS_Marker.cxx
  TopOpeBRepDS_Marker.hpp
  TopOpeBRepDS_PDataStructure.hpp
  TopOpeBRepDS_Point.cxx
  TopOpeBRepDS_Point.hpp
  TopOpeBRepDS_PointData.cxx
  TopOpeBRepDS_PointData.hpp
  TopOpeBRepDS_PointExplorer.cxx
  TopOpeBRepDS_PointExplorer.hpp
  TopOpeBRepDS_PointIterator.cxx
  TopOpeBRepDS_PointIterator.hpp
  TopOpeBRepDS_ProcessEdgeInterferences.cxx
  TopOpeBRepDS_ProcessFaceInterferences.cxx
  TopOpeBRepDS_ProcessInterferencesTool.cxx
  TopOpeBRepDS_ProcessInterferencesTool.hpp
  TopOpeBRepDS_redu.cxx
  TopOpeBRepDS_Reducer.cxx
  TopOpeBRepDS_Reducer.hpp
  TopOpeBRepDS_repvg.cxx
  TopOpeBRepDS_repvg.hpp
  TopOpeBRepDS_samdom.cxx
  TopOpeBRepDS_samdom.hpp
  TopOpeBRepDS_ShapeData.cxx
  TopOpeBRepDS_ShapeData.hpp
  TopOpeBRepDS_ShapeShapeInterference.cxx
  TopOpeBRepDS_ShapeShapeInterference.hpp

  TopOpeBRepDS_ShapeWithState.cxx
  TopOpeBRepDS_ShapeWithState.hpp
  TopOpeBRepDS_SolidSurfaceInterference.cxx
  TopOpeBRepDS_SolidSurfaceInterference.hpp
  TopOpeBRepDS_Surface.cxx
  TopOpeBRepDS_Surface.hpp
  TopOpeBRepDS_SurfaceCurveInterference.cxx
  TopOpeBRepDS_SurfaceCurveInterference.hpp
  TopOpeBRepDS_SurfaceData.cxx
  TopOpeBRepDS_SurfaceData.hpp
  TopOpeBRepDS_SurfaceExplorer.cxx
  TopOpeBRepDS_SurfaceExplorer.hpp
  TopOpeBRepDS_SurfaceIterator.cxx
  TopOpeBRepDS_SurfaceIterator.hpp
  TopOpeBRepDS_TKI.cxx
  TopOpeBRepDS_TKI.hpp
  TopOpeBRepDS_TOOL.cxx
  TopOpeBRepDS_TOOL.hpp
  TopOpeBRepDS_Transition.cxx
  TopOpeBRepDS_Transition.hpp
)
