# Source files for Transfer package
set(OCCT_Transfer_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_Transfer_FILES
  Transfer_ActorDispatch.cxx
  Transfer_ActorDispatch.hpp
  Transfer_ActorOfFinderProcess.cxx
  Transfer_ActorOfFinderProcess.hpp
  Transfer_ActorOfProcessForFinder.hpp
  Transfer_ActorOfProcessForFinder_0.cxx
  Transfer_ActorOfProcessForTransient.hpp
  Transfer_ActorOfProcessForTransient_0.cxx
  Transfer_ActorOfTransientProcess.cxx
  Transfer_ActorOfTransientProcess.hpp
  Transfer_Binder.cxx
  Transfer_Binder.hpp
  Transfer_BinderOfTransientInteger.cxx
  Transfer_BinderOfTransientInteger.hpp
  Transfer_DataInfo.cxx
  Transfer_DataInfo.hpp
  Transfer_DispatchControl.cxx
  Transfer_DispatchControl.hpp
  Transfer_Finder.cxx
  Transfer_Finder.hpp
  Transfer_FinderProcess.cxx
  Transfer_FinderProcess.hpp
  Transfer_FindHasher.hpp

  Transfer_IteratorOfProcessForFinder.hpp
  Transfer_IteratorOfProcessForFinder_0.cxx
  Transfer_IteratorOfProcessForTransient.hpp
  Transfer_IteratorOfProcessForTransient_0.cxx
  Transfer_MapContainer.cxx
  Transfer_MapContainer.hpp
  Transfer_MultipleBinder.cxx
  Transfer_MultipleBinder.hpp
  Transfer_ProcessForFinder.hpp
  Transfer_ProcessForFinder_0.cxx
  Transfer_ProcessForTransient.hpp
  Transfer_ProcessForTransient_0.cxx
  Transfer_ResultFromModel.cxx
  Transfer_ResultFromModel.hpp
  Transfer_ResultFromTransient.cxx
  Transfer_ResultFromTransient.hpp

  Transfer_SimpleBinderOfTransient.cxx
  Transfer_SimpleBinderOfTransient.hpp
  Transfer_StatusExec.hpp
  Transfer_StatusResult.hpp
  Transfer_TransferDeadLoop.hpp
  Transfer_TransferDispatch.cxx
  Transfer_TransferDispatch.hpp
  Transfer_TransferFailure.hpp
  Transfer_TransferInput.cxx
  Transfer_TransferInput.hpp
  Transfer_TransferIterator.cxx
  Transfer_TransferIterator.hpp

  Transfer_TransferOutput.cxx
  Transfer_TransferOutput.hpp
  Transfer_TransientListBinder.cxx
  Transfer_TransientListBinder.hpp
  Transfer_TransientMapper.hpp
  Transfer_TransientMapper_0.cxx
  Transfer_TransientProcess.cxx
  Transfer_TransientProcess.hpp
  Transfer_UndefMode.hpp
  Transfer_VoidBinder.cxx
  Transfer_VoidBinder.hpp
)
