# Source files for IFSelect package
set(OCCT_IFSelect_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_IFSelect_FILES
  IFSelect.cxx
  IFSelect.hpp
  IFSelect_Act.cxx
  IFSelect_Act.hpp
  IFSelect_ActFunc.hpp
  IFSelect_Activator.cxx
  IFSelect_Activator.hpp
  IFSelect_AppliedModifiers.cxx
  IFSelect_AppliedModifiers.hpp
  IFSelect_BasicDumper.cxx
  IFSelect_BasicDumper.hpp
  IFSelect_CheckCounter.cxx
  IFSelect_CheckCounter.hpp
  IFSelect_ContextModif.cxx
  IFSelect_ContextModif.hpp
  IFSelect_ContextWrite.cxx
  IFSelect_ContextWrite.hpp
  IFSelect_Dispatch.cxx
  IFSelect_Dispatch.hpp
  IFSelect_DispGlobal.cxx
  IFSelect_DispGlobal.hpp
  IFSelect_DispPerCount.cxx
  IFSelect_DispPerCount.hpp
  IFSelect_DispPerFiles.cxx
  IFSelect_DispPerFiles.hpp
  IFSelect_DispPerOne.cxx
  IFSelect_DispPerOne.hpp
  IFSelect_DispPerSignature.cxx
  IFSelect_DispPerSignature.hpp
  IFSelect_EditForm.cxx
  IFSelect_EditForm.hpp
  IFSelect_Editor.cxx
  IFSelect_Editor.hpp
  IFSelect_EditValue.hpp
  IFSelect_Functions.cxx
  IFSelect_Functions.hpp
  IFSelect_GeneralModifier.cxx
  IFSelect_GeneralModifier.hpp
  IFSelect_GraphCounter.cxx
  IFSelect_GraphCounter.hpp

  IFSelect_IntParam.cxx
  IFSelect_IntParam.hpp
  IFSelect_ListEditor.cxx
  IFSelect_ListEditor.hpp
  IFSelect_ModelCopier.cxx
  IFSelect_ModelCopier.hpp
  IFSelect_ModifEditForm.cxx
  IFSelect_ModifEditForm.hpp
  IFSelect_Modifier.cxx
  IFSelect_Modifier.hpp
  IFSelect_ModifReorder.cxx
  IFSelect_ModifReorder.hpp
  IFSelect_PacketList.cxx
  IFSelect_PacketList.hpp
  IFSelect_ParamEditor.cxx
  IFSelect_ParamEditor.hpp
  IFSelect_PrintCount.hpp
  IFSelect_PrintFail.hpp
  IFSelect_RemainMode.hpp
  IFSelect_ReturnStatus.hpp
  IFSelect_SelectAnyList.cxx
  IFSelect_SelectAnyList.hpp
  IFSelect_SelectAnyType.cxx
  IFSelect_SelectAnyType.hpp
  IFSelect_SelectBase.cxx
  IFSelect_SelectBase.hpp
  IFSelect_SelectCombine.cxx
  IFSelect_SelectCombine.hpp
  IFSelect_SelectControl.cxx
  IFSelect_SelectControl.hpp
  IFSelect_SelectDeduct.cxx
  IFSelect_SelectDeduct.hpp
  IFSelect_SelectDiff.cxx
  IFSelect_SelectDiff.hpp
  IFSelect_SelectEntityNumber.cxx
  IFSelect_SelectEntityNumber.hpp
  IFSelect_SelectErrorEntities.cxx
  IFSelect_SelectErrorEntities.hpp
  IFSelect_SelectExplore.cxx
  IFSelect_SelectExplore.hpp
  IFSelect_SelectExtract.cxx
  IFSelect_SelectExtract.hpp
  IFSelect_SelectFlag.cxx
  IFSelect_SelectFlag.hpp
  IFSelect_SelectIncorrectEntities.cxx
  IFSelect_SelectIncorrectEntities.hpp
  IFSelect_SelectInList.cxx
  IFSelect_SelectInList.hpp
  IFSelect_SelectIntersection.cxx
  IFSelect_SelectIntersection.hpp
  IFSelect_Selection.cxx
  IFSelect_Selection.hpp
  IFSelect_SelectionIterator.cxx
  IFSelect_SelectionIterator.hpp
  IFSelect_SelectModelEntities.cxx
  IFSelect_SelectModelEntities.hpp
  IFSelect_SelectModelRoots.cxx
  IFSelect_SelectModelRoots.hpp
  IFSelect_SelectPointed.cxx
  IFSelect_SelectPointed.hpp
  IFSelect_SelectRange.cxx
  IFSelect_SelectRange.hpp
  IFSelect_SelectRootComps.cxx
  IFSelect_SelectRootComps.hpp
  IFSelect_SelectRoots.cxx
  IFSelect_SelectRoots.hpp
  IFSelect_SelectSent.cxx
  IFSelect_SelectSent.hpp
  IFSelect_SelectShared.cxx
  IFSelect_SelectShared.hpp
  IFSelect_SelectSharing.cxx
  IFSelect_SelectSharing.hpp
  IFSelect_SelectSignature.cxx
  IFSelect_SelectSignature.hpp
  IFSelect_SelectSignedShared.cxx
  IFSelect_SelectSignedShared.hpp
  IFSelect_SelectSignedSharing.cxx
  IFSelect_SelectSignedSharing.hpp
  IFSelect_SelectSuite.cxx
  IFSelect_SelectSuite.hpp
  IFSelect_SelectType.cxx
  IFSelect_SelectType.hpp
  IFSelect_SelectUnion.cxx
  IFSelect_SelectUnion.hpp
  IFSelect_SelectUnknownEntities.cxx
  IFSelect_SelectUnknownEntities.hpp

  IFSelect_SessionDumper.cxx
  IFSelect_SessionDumper.hpp
  IFSelect_SessionFile.cxx
  IFSelect_SessionFile.hpp
  IFSelect_SessionPilot.cxx
  IFSelect_SessionPilot.hpp
  IFSelect_ShareOut.cxx
  IFSelect_ShareOut.hpp
  IFSelect_ShareOutResult.cxx
  IFSelect_ShareOutResult.hpp
  IFSelect_SignAncestor.cxx
  IFSelect_SignAncestor.hpp
  IFSelect_Signature.cxx
  IFSelect_Signature.hpp
  IFSelect_SignatureList.cxx
  IFSelect_SignatureList.hpp
  IFSelect_SignCategory.cxx
  IFSelect_SignCategory.hpp
  IFSelect_SignCounter.cxx
  IFSelect_SignCounter.hpp
  IFSelect_SignMultiple.cxx
  IFSelect_SignMultiple.hpp
  IFSelect_SignType.cxx
  IFSelect_SignType.hpp
  IFSelect_SignValidity.cxx
  IFSelect_SignValidity.hpp
  IFSelect_Transformer.cxx
  IFSelect_Transformer.hpp
  IFSelect_TransformStandard.cxx
  IFSelect_TransformStandard.hpp

  IFSelect_WorkLibrary.cxx
  IFSelect_WorkLibrary.hpp
  IFSelect_WorkSession.cxx
  IFSelect_WorkSession.hpp
)
