# Source files for RWStepShape package
set(OCCT_RWStepShape_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_RWStepShape_FILES
  RWStepShape_RWAdvancedBrepShapeRepresentation.cxx
  RWStepShape_RWAdvancedBrepShapeRepresentation.hpp
  RWStepShape_RWAdvancedFace.cxx
  RWStepShape_RWAdvancedFace.hpp
  RWStepShape_RWAngularLocation.cxx
  RWStepShape_RWAngularLocation.hpp
  RWStepShape_RWAngularSize.cxx
  RWStepShape_RWAngularSize.hpp
  RWStepShape_RWBlock.cxx
  RWStepShape_RWBlock.hpp
  RWStepShape_RWBooleanOperator.hpp
  RWStepShape_RWBooleanResult.cxx
  RWStepShape_RWBooleanResult.hpp
  RWStepShape_RWBoxDomain.cxx
  RWStepShape_RWBoxDomain.hpp
  RWStepShape_RWBoxedHalfSpace.cxx
  RWStepShape_RWBoxedHalfSpace.hpp
  RWStepShape_RWBrepWithVoids.cxx
  RWStepShape_RWBrepWithVoids.hpp
  RWStepShape_RWClosedShell.cxx
  RWStepShape_RWClosedShell.hpp
  RWStepShape_RWCompoundShapeRepresentation.cxx
  RWStepShape_RWCompoundShapeRepresentation.hpp
  RWStepShape_RWConnectedEdgeSet.cxx
  RWStepShape_RWConnectedEdgeSet.hpp
  RWStepShape_RWConnectedFaceSet.cxx
  RWStepShape_RWConnectedFaceSet.hpp
  RWStepShape_RWConnectedFaceShapeRepresentation.cxx
  RWStepShape_RWConnectedFaceShapeRepresentation.hpp
  RWStepShape_RWConnectedFaceSubSet.cxx
  RWStepShape_RWConnectedFaceSubSet.hpp
  RWStepShape_RWContextDependentShapeRepresentation.cxx
  RWStepShape_RWContextDependentShapeRepresentation.hpp
  RWStepShape_RWCsgShapeRepresentation.cxx
  RWStepShape_RWCsgShapeRepresentation.hpp
  RWStepShape_RWCsgSolid.cxx
  RWStepShape_RWCsgSolid.hpp
  RWStepShape_RWDefinitionalRepresentationAndShapeRepresentation.cxx
  RWStepShape_RWDefinitionalRepresentationAndShapeRepresentation.hpp
  RWStepShape_RWDimensionalCharacteristicRepresentation.cxx
  RWStepShape_RWDimensionalCharacteristicRepresentation.hpp
  RWStepShape_RWDimensionalLocation.cxx
  RWStepShape_RWDimensionalLocation.hpp
  RWStepShape_RWDimensionalLocationWithPath.cxx
  RWStepShape_RWDimensionalLocationWithPath.hpp
  RWStepShape_RWDimensionalSize.cxx
  RWStepShape_RWDimensionalSize.hpp
  RWStepShape_RWDimensionalSizeWithPath.cxx
  RWStepShape_RWDimensionalSizeWithPath.hpp
  RWStepShape_RWEdge.cxx
  RWStepShape_RWEdge.hpp
  RWStepShape_RWEdgeBasedWireframeModel.cxx
  RWStepShape_RWEdgeBasedWireframeModel.hpp
  RWStepShape_RWEdgeBasedWireframeShapeRepresentation.cxx
  RWStepShape_RWEdgeBasedWireframeShapeRepresentation.hpp
  RWStepShape_RWEdgeCurve.cxx
  RWStepShape_RWEdgeCurve.hpp
  RWStepShape_RWEdgeLoop.cxx
  RWStepShape_RWEdgeLoop.hpp
  RWStepShape_RWExtrudedAreaSolid.cxx
  RWStepShape_RWExtrudedAreaSolid.hpp
  RWStepShape_RWExtrudedFaceSolid.cxx
  RWStepShape_RWExtrudedFaceSolid.hpp
  RWStepShape_RWFace.cxx
  RWStepShape_RWFace.hpp
  RWStepShape_RWFaceBasedSurfaceModel.cxx
  RWStepShape_RWFaceBasedSurfaceModel.hpp
  RWStepShape_RWFaceBound.cxx
  RWStepShape_RWFaceBound.hpp
  RWStepShape_RWFaceOuterBound.cxx
  RWStepShape_RWFaceOuterBound.hpp
  RWStepShape_RWFaceSurface.cxx
  RWStepShape_RWFaceSurface.hpp
  RWStepShape_RWFacetedBrep.cxx
  RWStepShape_RWFacetedBrep.hpp
  RWStepShape_RWFacetedBrepAndBrepWithVoids.cxx
  RWStepShape_RWFacetedBrepAndBrepWithVoids.hpp
  RWStepShape_RWFacetedBrepShapeRepresentation.cxx
  RWStepShape_RWFacetedBrepShapeRepresentation.hpp
  RWStepShape_RWGeometricallyBoundedSurfaceShapeRepresentation.cxx
  RWStepShape_RWGeometricallyBoundedSurfaceShapeRepresentation.hpp
  RWStepShape_RWGeometricallyBoundedWireframeShapeRepresentation.cxx
  RWStepShape_RWGeometricallyBoundedWireframeShapeRepresentation.hpp
  RWStepShape_RWGeometricCurveSet.cxx
  RWStepShape_RWGeometricCurveSet.hpp
  RWStepShape_RWGeometricSet.cxx
  RWStepShape_RWGeometricSet.hpp
  RWStepShape_RWHalfSpaceSolid.cxx
  RWStepShape_RWHalfSpaceSolid.hpp
  RWStepShape_RWLimitsAndFits.cxx
  RWStepShape_RWLimitsAndFits.hpp
  RWStepShape_RWLoop.cxx
  RWStepShape_RWLoop.hpp
  RWStepShape_RWLoopAndPath.cxx
  RWStepShape_RWLoopAndPath.hpp
  RWStepShape_RWManifoldSolidBrep.cxx
  RWStepShape_RWManifoldSolidBrep.hpp
  RWStepShape_RWManifoldSurfaceShapeRepresentation.cxx
  RWStepShape_RWManifoldSurfaceShapeRepresentation.hpp
  RWStepShape_RWMeasureQualification.cxx
  RWStepShape_RWMeasureQualification.hpp
  RWStepShape_RWMeasureRepresentationItemAndQualifiedRepresentationItem.cxx
  RWStepShape_RWMeasureRepresentationItemAndQualifiedRepresentationItem.hpp
  RWStepShape_RWNonManifoldSurfaceShapeRepresentation.cxx
  RWStepShape_RWNonManifoldSurfaceShapeRepresentation.hpp
  RWStepShape_RWOpenShell.cxx
  RWStepShape_RWOpenShell.hpp
  RWStepShape_RWOrientedClosedShell.cxx
  RWStepShape_RWOrientedClosedShell.hpp
  RWStepShape_RWOrientedEdge.cxx
  RWStepShape_RWOrientedEdge.hpp
  RWStepShape_RWOrientedFace.cxx
  RWStepShape_RWOrientedFace.hpp
  RWStepShape_RWOrientedOpenShell.cxx
  RWStepShape_RWOrientedOpenShell.hpp
  RWStepShape_RWOrientedPath.cxx
  RWStepShape_RWOrientedPath.hpp
  RWStepShape_RWPath.cxx
  RWStepShape_RWPath.hpp
  RWStepShape_RWPlusMinusTolerance.cxx
  RWStepShape_RWPlusMinusTolerance.hpp
  RWStepShape_RWPointRepresentation.cxx
  RWStepShape_RWPointRepresentation.hpp
  RWStepShape_RWPolyLoop.cxx
  RWStepShape_RWPolyLoop.hpp
  RWStepShape_RWPrecisionQualifier.cxx
  RWStepShape_RWPrecisionQualifier.hpp
  RWStepShape_RWQualifiedRepresentationItem.cxx
  RWStepShape_RWQualifiedRepresentationItem.hpp
  RWStepShape_RWRevolvedAreaSolid.cxx
  RWStepShape_RWRevolvedAreaSolid.hpp
  RWStepShape_RWRevolvedFaceSolid.cxx
  RWStepShape_RWRevolvedFaceSolid.hpp
  RWStepShape_RWRightAngularWedge.cxx
  RWStepShape_RWRightAngularWedge.hpp
  RWStepShape_RWRightCircularCone.cxx
  RWStepShape_RWRightCircularCone.hpp
  RWStepShape_RWRightCircularCylinder.cxx
  RWStepShape_RWRightCircularCylinder.hpp
  RWStepShape_RWSeamEdge.cxx
  RWStepShape_RWSeamEdge.hpp
  RWStepShape_RWShapeDefinitionRepresentation.cxx
  RWStepShape_RWShapeDefinitionRepresentation.hpp
  RWStepShape_RWShapeDimensionRepresentation.cxx
  RWStepShape_RWShapeDimensionRepresentation.hpp
  RWStepShape_RWShapeRepresentation.cxx
  RWStepShape_RWShapeRepresentation.hpp
  RWStepShape_RWShapeRepresentationWithParameters.cxx
  RWStepShape_RWShapeRepresentationWithParameters.hpp
  RWStepShape_RWShellBasedSurfaceModel.cxx
  RWStepShape_RWShellBasedSurfaceModel.hpp
  RWStepShape_RWSolidModel.cxx
  RWStepShape_RWSolidModel.hpp
  RWStepShape_RWSolidReplica.cxx
  RWStepShape_RWSolidReplica.hpp
  RWStepShape_RWSphere.cxx
  RWStepShape_RWSphere.hpp
  RWStepShape_RWSubedge.cxx
  RWStepShape_RWSubedge.hpp
  RWStepShape_RWSubface.cxx
  RWStepShape_RWSubface.hpp
  RWStepShape_RWSweptAreaSolid.cxx
  RWStepShape_RWSweptAreaSolid.hpp
  RWStepShape_RWSweptFaceSolid.cxx
  RWStepShape_RWSweptFaceSolid.hpp
  RWStepShape_RWToleranceValue.cxx
  RWStepShape_RWToleranceValue.hpp
  RWStepShape_RWTopologicalRepresentationItem.cxx
  RWStepShape_RWTopologicalRepresentationItem.hpp
  RWStepShape_RWTorus.cxx
  RWStepShape_RWTorus.hpp
  RWStepShape_RWTransitionalShapeRepresentation.cxx
  RWStepShape_RWTransitionalShapeRepresentation.hpp
  RWStepShape_RWTypeQualifier.cxx
  RWStepShape_RWTypeQualifier.hpp
  RWStepShape_RWValueFormatTypeQualifier.cxx
  RWStepShape_RWValueFormatTypeQualifier.hpp
  RWStepShape_RWVertex.cxx
  RWStepShape_RWVertex.hpp
  RWStepShape_RWVertexLoop.cxx
  RWStepShape_RWVertexLoop.hpp
  RWStepShape_RWVertexPoint.cxx
  RWStepShape_RWVertexPoint.hpp
)
