#include <StepDimTol_SurfaceProfileTolerance.hpp>

IMPLEMENT_STANDARD_RTTIEXT(StepDimTol_SurfaceProfileTolerance, StepDimTol_GeometricTolerance)

StepDimTol_SurfaceProfileTolerance::StepDimTol_SurfaceProfileTolerance() = default;
