#include <StepDimTol_DatumReferenceCompartment.hpp>

IMPLEMENT_STANDARD_RTTIEXT(StepDimTol_DatumReferenceCompartment, StepDimTol_GeneralDatumReference)

StepDimTol_DatumReferenceCompartment::StepDimTol_DatumReferenceCompartment() = default;
