#include <StepDimTol_DatumReferenceElement.hpp>

IMPLEMENT_STANDARD_RTTIEXT(StepDimTol_DatumReferenceElement, StepDimTol_GeneralDatumReference)

StepDimTol_DatumReferenceElement::StepDimTol_DatumReferenceElement() = default;
