#include <StepVisual_AnnotationCurveOccurrence.hpp>

IMPLEMENT_STANDARD_RTTIEXT(StepVisual_AnnotationCurveOccurrence, StepVisual_AnnotationOccurrence)

StepVisual_AnnotationCurveOccurrence::StepVisual_AnnotationCurveOccurrence() = default;
