#include <StepVisual_TessellatedAnnotationOccurrence.hpp>

IMPLEMENT_STANDARD_RTTIEXT(StepVisual_TessellatedAnnotationOccurrence, StepVisual_StyledItem);

StepVisual_TessellatedAnnotationOccurrence::StepVisual_TessellatedAnnotationOccurrence() = default;
