

#include <StepVisual_CubicBezierTessellatedEdge.hpp>

IMPLEMENT_STANDARD_RTTIEXT(StepVisual_CubicBezierTessellatedEdge, StepVisual_TessellatedEdge)

StepVisual_CubicBezierTessellatedEdge::StepVisual_CubicBezierTessellatedEdge() = default;
