

#include <StepVisual_TessellatedShapeRepresentation.hpp>

IMPLEMENT_STANDARD_RTTIEXT(StepVisual_TessellatedShapeRepresentation, StepShape_ShapeRepresentation)

StepVisual_TessellatedShapeRepresentation::StepVisual_TessellatedShapeRepresentation() = default;
