# Source files for TopOpeBRepTool package
set(OCCT_TopOpeBRepTool_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_TopOpeBRepTool_FILES
  FILES
  TopOpeBRepTool.cxx
  TopOpeBRepTool.hpp
  TopOpeBRepTool_2d.cxx
  TopOpeBRepTool_2d.hpp
  TopOpeBRepTool_AncestorsTool.cxx
  TopOpeBRepTool_AncestorsTool.hpp
  TopOpeBRepTool_box.cxx
  TopOpeBRepTool_box.hpp
  TopOpeBRepTool_BoxSort.cxx
  TopOpeBRepTool_BoxSort.hpp
  TopOpeBRepTool_C2DF.cxx
  TopOpeBRepTool_C2DF.hpp
  TopOpeBRepTool_CLASSI.cxx
  TopOpeBRepTool_CLASSI.hpp
  TopOpeBRepTool_connexity.cxx
  TopOpeBRepTool_connexity.hpp
  TopOpeBRepTool_CORRISO.cxx
  TopOpeBRepTool_CORRISO.hpp
  TopOpeBRepTool_CurveTool.cxx
  TopOpeBRepTool_CurveTool.hpp

  TopOpeBRepTool_defineG.hpp

  TopOpeBRepTool_face.cxx
  TopOpeBRepTool_face.hpp
  TopOpeBRepTool_faulty.cxx
  TopOpeBRepTool_FuseEdges.cxx
  TopOpeBRepTool_FuseEdges.hpp
  TopOpeBRepTool_GEOMETRY.cxx
  TopOpeBRepTool_GEOMETRY.hpp
  TopOpeBRepTool_GeomTool.cxx
  TopOpeBRepTool_GeomTool.hpp
  TopOpeBRepTool_HBoxTool.cxx
  TopOpeBRepTool_HBoxTool.hpp

  TopOpeBRepTool_KRO.hpp

  TopOpeBRepTool_makeTransition.cxx
  TopOpeBRepTool_makeTransition.hpp
  TopOpeBRepTool_matter.cxx
  TopOpeBRepTool_mkTondgE.cxx
  TopOpeBRepTool_mkTondgE.hpp
  TopOpeBRepTool_OutCurveType.hpp
  TopOpeBRepTool_Plos.hpp
  TopOpeBRepTool_PROJECT.cxx
  TopOpeBRepTool_PROJECT.hpp
  TopOpeBRepTool_PShapeClassifier.hpp
  TopOpeBRepTool_PURGE.cxx
  TopOpeBRepTool_PURGE.hpp
  TopOpeBRepTool_PurgeInternalEdges.cxx
  TopOpeBRepTool_PurgeInternalEdges.hpp
  TopOpeBRepTool_RegularizeS.cxx
  TopOpeBRepTool_RegularizeW.cxx
  TopOpeBRepTool_REGUS.cxx
  TopOpeBRepTool_REGUS.hpp
  TopOpeBRepTool_REGUW.cxx
  TopOpeBRepTool_REGUW.hpp
  TopOpeBRepTool_SC.cxx
  TopOpeBRepTool_SC.hpp
  TopOpeBRepTool_ShapeClassifier.cxx
  TopOpeBRepTool_ShapeClassifier.hpp
  TopOpeBRepTool_ShapeExplorer.hpp
  TopOpeBRepTool_ShapeTool.cxx
  TopOpeBRepTool_ShapeTool.hpp
  TopOpeBRepTool_SolidClassifier.cxx
  TopOpeBRepTool_SolidClassifier.hpp
  TopOpeBRepTool_STATE.cxx
  TopOpeBRepTool_STATE.hpp
  TopOpeBRepTool_tol.cxx
  TopOpeBRepTool_tol.hpp
  TopOpeBRepTool_TOOL.cxx
  TopOpeBRepTool_TOOL.hpp
  TopOpeBRepTool_TOPOLOGY.cxx
  TopOpeBRepTool_TOPOLOGY.hpp
  TopOpeBRepTool_trace.cxx
  TopOpeBRepTool_traceSTATE.cxx
)
