# Source files for Select3D package
set(OCCT_Select3D_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_Select3D_FILES
  Select3D_BndBox3d.hpp
  Select3D_BVHBuilder3d.hpp
  Select3D_InteriorSensitivePointSet.cxx
  Select3D_InteriorSensitivePointSet.hpp
  Select3D_SensitiveBox.cxx
  Select3D_SensitiveBox.hpp
  Select3D_SensitiveCircle.cxx
  Select3D_SensitiveCircle.hpp
  Select3D_SensitiveCurve.cxx
  Select3D_SensitiveCurve.hpp
  Select3D_SensitiveCylinder.cxx
  Select3D_SensitiveCylinder.hpp
  Select3D_SensitiveEntity.cxx
  Select3D_SensitiveEntity.hpp
  Select3D_SensitiveFace.cxx
  Select3D_SensitiveFace.hpp
  Select3D_SensitiveGroup.cxx
  Select3D_SensitiveGroup.hpp
  Select3D_SensitivePoint.cxx
  Select3D_SensitivePoint.hpp
  Select3D_SensitivePoly.cxx
  Select3D_SensitivePoly.hpp
  Select3D_SensitivePrimitiveArray.cxx
  Select3D_SensitivePrimitiveArray.hpp
  Select3D_SensitiveSegment.cxx
  Select3D_SensitiveSegment.hpp
  Select3D_SensitiveSet.cxx
  Select3D_SensitiveSet.hpp
  Select3D_SensitiveSphere.cxx
  Select3D_SensitiveSphere.hpp
  Select3D_SensitiveTriangle.cxx
  Select3D_SensitiveTriangle.hpp
  Select3D_SensitiveTriangulation.cxx
  Select3D_SensitiveTriangulation.hpp
  Select3D_SensitiveWire.cxx
  Select3D_SensitiveWire.hpp
  Select3D_TypeOfSensitivity.hpp
)
