# Source files for BRepMesh package
set(OCCT_BRepMesh_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_BRepMesh_FILES
  BRepMesh_BaseMeshAlgo.cxx
  BRepMesh_BaseMeshAlgo.hpp
  BRepMesh_ConstrainedBaseMeshAlgo.hpp
  BRepMesh_ConstrainedBaseMeshAlgo.cxx
  BRepMesh_BoundaryParamsRangeSplitter.hpp
  BRepMesh_Circle.hpp
  BRepMesh_CircleInspector.hpp
  BRepMesh_CircleTool.cxx
  BRepMesh_CircleTool.hpp
  BRepMesh_Classifier.cxx
  BRepMesh_Classifier.hpp
  BRepMesh_ConeRangeSplitter.cxx
  BRepMesh_ConeRangeSplitter.hpp
  BRepMesh_Context.cxx
  BRepMesh_Context.hpp
  BRepMesh_CurveTessellator.cxx
  BRepMesh_CurveTessellator.hpp
  BRepMesh_CylinderRangeSplitter.cxx
  BRepMesh_CylinderRangeSplitter.hpp
  BRepMesh_DataStructureOfDelaun.cxx
  BRepMesh_DataStructureOfDelaun.hpp
  BRepMesh_DefaultRangeSplitter.cxx
  BRepMesh_DefaultRangeSplitter.hpp
  BRepMesh_Deflection.cxx
  BRepMesh_Deflection.hpp
  BRepMesh_DegreeOfFreedom.hpp
  BRepMesh_Delaun.cxx
  BRepMesh_Delaun.hpp
  BRepMesh_DelaunayBaseMeshAlgo.cxx
  BRepMesh_DelaunayBaseMeshAlgo.hpp
  BRepMesh_DelaunayDeflectionControlMeshAlgo.hpp
  BRepMesh_DiscretFactory.cxx
  BRepMesh_DiscretFactory.hpp
  BRepMesh_DiscretRoot.cxx
  BRepMesh_DiscretRoot.hpp
  BRepMesh_Edge.hpp
  BRepMesh_EdgeDiscret.cxx
  BRepMesh_EdgeDiscret.hpp
  BRepMesh_EdgeTessellationExtractor.cxx
  BRepMesh_EdgeTessellationExtractor.hpp
  BRepMesh_ExtrusionRangeSplitter.cxx
  BRepMesh_ExtrusionRangeSplitter.hpp
  BRepMesh_FaceChecker.cxx
  BRepMesh_FaceChecker.hpp
  BRepMesh_FaceDiscret.cxx
  BRepMesh_FaceDiscret.hpp
  BRepMesh_FactoryError.hpp
  
  BRepMesh_GeomTool.cxx
  BRepMesh_GeomTool.hpp
  BRepMesh_IncrementalMesh.cxx
  BRepMesh_IncrementalMesh.hpp
  BRepMesh_MeshAlgoFactory.cxx
  BRepMesh_MeshAlgoFactory.hpp
  BRepMesh_MeshTool.cxx
  BRepMesh_MeshTool.hpp
  BRepMesh_ModelBuilder.cxx
  BRepMesh_ModelBuilder.hpp
  BRepMesh_ModelHealer.cxx
  BRepMesh_ModelHealer.hpp
  BRepMesh_ModelPostProcessor.cxx
  BRepMesh_ModelPostProcessor.hpp
  BRepMesh_ModelPreProcessor.cxx
  BRepMesh_ModelPreProcessor.hpp
  BRepMesh_NURBSRangeSplitter.cxx
  BRepMesh_NURBSRangeSplitter.hpp
  BRepMesh_PairOfIndex.hpp
  BRepMesh_PluginMacro.hpp
  BRepMesh_SelectorOfDataStructureOfDelaun.cxx
  BRepMesh_SelectorOfDataStructureOfDelaun.hpp
  BRepMesh_ShapeTool.cxx
  BRepMesh_ShapeTool.hpp
  BRepMesh_ShapeVisitor.cxx
  BRepMesh_ShapeVisitor.hpp
  BRepMesh_SphereRangeSplitter.cxx
  BRepMesh_SphereRangeSplitter.hpp
  BRepMesh_TorusRangeSplitter.cxx
  BRepMesh_TorusRangeSplitter.hpp
  BRepMesh_Triangle.hpp
  BRepMesh_UndefinedRangeSplitter.cxx
  BRepMesh_UndefinedRangeSplitter.hpp
  BRepMesh_UVParamRangeSplitter.hpp
  BRepMesh_Vertex.hpp
  BRepMesh_VertexTool.cxx
  BRepMesh_VertexTool.hpp
  BRepMesh_CustomBaseMeshAlgo.hpp
  BRepMesh_CustomBaseMeshAlgo.cxx
  BRepMesh_CustomDelaunayBaseMeshAlgo.hpp
  delabella.hpp
  delabella.cpp
  BRepMesh_DelabellaBaseMeshAlgo.hpp
  BRepMesh_DelabellaBaseMeshAlgo.cxx
  BRepMesh_DelabellaMeshAlgoFactory.hpp
  BRepMesh_DelabellaMeshAlgoFactory.cxx
  BRepMesh_Triangulator.cxx
  BRepMesh_Triangulator.hpp
)
