# Source files for TDataStd package
set(OCCT_TDataStd_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_TDataStd_FILES
  TDataStd.cxx
  TDataStd.hpp
  TDataStd_AsciiString.cxx
  TDataStd_AsciiString.hpp
  TDataStd_BooleanArray.cxx
  TDataStd_BooleanArray.hpp
  TDataStd_BooleanList.cxx
  TDataStd_BooleanList.hpp
  TDataStd_ByteArray.cxx
  TDataStd_ByteArray.hpp
  TDataStd_ChildNodeIterator.cxx
  TDataStd_ChildNodeIterator.hpp
  TDataStd_Comment.cxx
  TDataStd_Comment.hpp
  TDataStd_Current.cxx
  TDataStd_Current.hpp
  TDataStd_GenericEmpty.cxx
  TDataStd_GenericEmpty.hpp
  TDataStd_GenericExtString.cxx
  TDataStd_GenericExtString.hpp

  TDataStd_DeltaOnModificationOfByteArray.cxx
  TDataStd_DeltaOnModificationOfByteArray.hpp
  TDataStd_DeltaOnModificationOfExtStringArray.cxx
  TDataStd_DeltaOnModificationOfExtStringArray.hpp
  TDataStd_DeltaOnModificationOfIntArray.cxx
  TDataStd_DeltaOnModificationOfIntArray.hpp
  TDataStd_DeltaOnModificationOfIntPackedMap.cxx
  TDataStd_DeltaOnModificationOfIntPackedMap.hpp
  TDataStd_DeltaOnModificationOfRealArray.cxx
  TDataStd_DeltaOnModificationOfRealArray.hpp
  TDataStd_Directory.cxx
  TDataStd_Directory.hpp
  TDataStd_Expression.cxx
  TDataStd_Expression.hpp
  TDataStd_ExtStringArray.cxx
  TDataStd_ExtStringArray.hpp
  TDataStd_ExtStringList.cxx
  TDataStd_ExtStringList.hpp
  TDataStd_HDataMapOfStringByte.cxx
  TDataStd_HDataMapOfStringByte.hpp
  TDataStd_HDataMapOfStringHArray1OfInteger.cxx
  TDataStd_HDataMapOfStringHArray1OfInteger.hpp
  TDataStd_HDataMapOfStringHArray1OfReal.cxx
  TDataStd_HDataMapOfStringHArray1OfReal.hpp
  TDataStd_HDataMapOfStringInteger.cxx
  TDataStd_HDataMapOfStringInteger.hpp
  TDataStd_HDataMapOfStringReal.cxx
  TDataStd_HDataMapOfStringReal.hpp
  TDataStd_HDataMapOfStringString.cxx
  TDataStd_HDataMapOfStringString.hpp

  TDataStd_Integer.cxx
  TDataStd_Integer.hpp
  TDataStd_IntegerArray.cxx
  TDataStd_IntegerArray.hpp
  TDataStd_IntegerList.cxx
  TDataStd_IntegerList.hpp
  TDataStd_IntPackedMap.cxx
  TDataStd_IntPackedMap.hpp

  TDataStd_Name.cxx
  TDataStd_Name.hpp
  TDataStd_NamedData.cxx
  TDataStd_NamedData.hpp
  TDataStd_NoteBook.cxx
  TDataStd_NoteBook.hpp
  TDataStd_Real.cxx
  TDataStd_Real.hpp
  TDataStd_RealArray.cxx
  TDataStd_RealArray.hpp
  TDataStd_RealEnum.hpp
  TDataStd_RealList.cxx
  TDataStd_RealList.hpp
  TDataStd_ReferenceArray.cxx
  TDataStd_ReferenceArray.hpp
  TDataStd_ReferenceList.cxx
  TDataStd_ReferenceList.hpp
  TDataStd_Relation.cxx
  TDataStd_Relation.hpp
  TDataStd_Tick.cxx
  TDataStd_Tick.hpp
  TDataStd_TreeNode.cxx
  TDataStd_TreeNode.hpp
  TDataStd_UAttribute.cxx
  TDataStd_UAttribute.hpp
  TDataStd_Variable.cxx
  TDataStd_Variable.hpp
)
