# Source files for BlendFunc package
set(OCCT_BlendFunc_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_BlendFunc_FILES
  BlendFunc.cxx
  BlendFunc.hpp
  BlendFunc_GenChamfer.cxx
  BlendFunc_GenChamfer.hpp
  BlendFunc_GenChamfInv.cxx
  BlendFunc_GenChamfInv.hpp
  BlendFunc_Chamfer.cxx
  BlendFunc_Chamfer.hpp
  BlendFunc_ChamfInv.cxx
  BlendFunc_ChamfInv.hpp
  BlendFunc_ChAsym.cxx
  BlendFunc_ChAsym.hpp
  BlendFunc_ChAsymInv.cxx
  BlendFunc_ChAsymInv.hpp
  BlendFunc_ConstRad.cxx
  BlendFunc_ConstRad.hpp
  BlendFunc_ConstRadInv.cxx
  BlendFunc_ConstRadInv.hpp
  BlendFunc_Corde.cxx
  BlendFunc_Corde.hpp
  BlendFunc_CSCircular.cxx
  BlendFunc_CSCircular.hpp
  BlendFunc_CSConstRad.cxx
  BlendFunc_CSConstRad.hpp
  BlendFunc_EvolRad.cxx
  BlendFunc_EvolRad.hpp
  BlendFunc_EvolRadInv.cxx
  BlendFunc_EvolRadInv.hpp
  BlendFunc_Ruled.cxx
  BlendFunc_Ruled.hpp
  BlendFunc_RuledInv.cxx
  BlendFunc_RuledInv.hpp
  BlendFunc_SectionShape.hpp
  BlendFunc_Tensor.cxx
  BlendFunc_Tensor.hpp
  BlendFunc_ConstThroat.cxx
  BlendFunc_ConstThroat.hpp
  BlendFunc_ConstThroatInv.cxx
  BlendFunc_ConstThroatInv.hpp
  BlendFunc_ConstThroatWithPenetration.cxx
  BlendFunc_ConstThroatWithPenetration.hpp
  BlendFunc_ConstThroatWithPenetrationInv.cxx
  BlendFunc_ConstThroatWithPenetrationInv.hpp
)
