# Source files for ShapeUpgrade package
set(OCCT_ShapeUpgrade_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_ShapeUpgrade_FILES
  ShapeUpgrade.cxx
  ShapeUpgrade.hpp
  ShapeUpgrade_ClosedEdgeDivide.cxx
  ShapeUpgrade_ClosedEdgeDivide.hpp
  ShapeUpgrade_ClosedFaceDivide.cxx
  ShapeUpgrade_ClosedFaceDivide.hpp
  ShapeUpgrade_ConvertCurve2dToBezier.cxx
  ShapeUpgrade_ConvertCurve2dToBezier.hpp
  ShapeUpgrade_ConvertCurve3dToBezier.cxx
  ShapeUpgrade_ConvertCurve3dToBezier.hpp
  ShapeUpgrade_ConvertCurve3dToBezier_1.hpp
  ShapeUpgrade_ConvertSurfaceToBezierBasis.cxx
  ShapeUpgrade_ConvertSurfaceToBezierBasis.hpp
  ShapeUpgrade_ConvertSurfaceToBezierBasis_1.hpp
  ShapeUpgrade_EdgeDivide.cxx
  ShapeUpgrade_EdgeDivide.hpp
  ShapeUpgrade_EdgeDivide_1.hpp
  ShapeUpgrade_FaceDivide.cxx
  ShapeUpgrade_FaceDivide.hpp
  ShapeUpgrade_FaceDivideArea.cxx
  ShapeUpgrade_FaceDivideArea.hpp
  ShapeUpgrade_FaceDivideArea_1.hpp
  ShapeUpgrade_FixSmallBezierCurves.cxx
  ShapeUpgrade_FixSmallBezierCurves.hpp
  ShapeUpgrade_FixSmallCurves.cxx
  ShapeUpgrade_FixSmallCurves.hpp
  ShapeUpgrade_RemoveInternalWires.cxx
  ShapeUpgrade_RemoveInternalWires.hpp
  ShapeUpgrade_RemoveInternalWires_1.hpp
  ShapeUpgrade_RemoveLocations.cxx
  ShapeUpgrade_RemoveLocations.hpp
  ShapeUpgrade_RemoveLocations_1.hpp
  ShapeUpgrade_ShapeConvertToBezier.cxx
  ShapeUpgrade_ShapeConvertToBezier.hpp
  ShapeUpgrade_ShapeConvertToBezier_1.hpp
  ShapeUpgrade_ShapeDivide.cxx
  ShapeUpgrade_ShapeDivide.hpp
  ShapeUpgrade_ShapeDivideAngle.cxx
  ShapeUpgrade_ShapeDivideAngle.hpp
  ShapeUpgrade_ShapeDivideArea.cxx
  ShapeUpgrade_ShapeDivideArea.hpp
  ShapeUpgrade_ShapeDivideArea_1.hpp
  ShapeUpgrade_ShapeDivideClosed.cxx
  ShapeUpgrade_ShapeDivideClosed.hpp
  ShapeUpgrade_ShapeDivideClosedEdges.cxx
  ShapeUpgrade_ShapeDivideClosedEdges.hpp
  ShapeUpgrade_ShapeDivideContinuity.cxx
  ShapeUpgrade_ShapeDivideContinuity.hpp
  ShapeUpgrade_ShellSewing.cxx
  ShapeUpgrade_ShellSewing.hpp
  ShapeUpgrade_SplitCurve.cxx
  ShapeUpgrade_SplitCurve.hpp
  ShapeUpgrade_SplitCurve2d.cxx
  ShapeUpgrade_SplitCurve2d.hpp
  ShapeUpgrade_SplitCurve2dContinuity.cxx
  ShapeUpgrade_SplitCurve2dContinuity.hpp
  ShapeUpgrade_SplitCurve3d.cxx
  ShapeUpgrade_SplitCurve3d.hpp
  ShapeUpgrade_SplitCurve3dContinuity.cxx
  ShapeUpgrade_SplitCurve3dContinuity.hpp
  ShapeUpgrade_SplitSurface.cxx
  ShapeUpgrade_SplitSurface.hpp
  ShapeUpgrade_SplitSurfaceAngle.cxx
  ShapeUpgrade_SplitSurfaceAngle.hpp
  ShapeUpgrade_SplitSurfaceArea.cxx
  ShapeUpgrade_SplitSurfaceArea.hpp
  ShapeUpgrade_SplitSurfaceArea_1.hpp
  ShapeUpgrade_SplitSurfaceContinuity.cxx
  ShapeUpgrade_SplitSurfaceContinuity.hpp
  ShapeUpgrade_Tool.cxx
  ShapeUpgrade_Tool.hpp
  ShapeUpgrade_Tool_1.hpp
  ShapeUpgrade_UnifySameDomain.cxx
  ShapeUpgrade_UnifySameDomain.hpp
  ShapeUpgrade_WireDivide.cxx
  ShapeUpgrade_WireDivide.hpp
)
