# Source files for IGESDraw package
set(OCCT_IGESDraw_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_IGESDraw_FILES
  IGESDraw.cxx
  IGESDraw.hpp

  IGESDraw_CircArraySubfigure.cxx
  IGESDraw_CircArraySubfigure.hpp
  IGESDraw_ConnectPoint.cxx
  IGESDraw_ConnectPoint.hpp
  IGESDraw_Drawing.cxx
  IGESDraw_Drawing.hpp
  IGESDraw_DrawingWithRotation.cxx
  IGESDraw_DrawingWithRotation.hpp
  IGESDraw_GeneralModule.cxx
  IGESDraw_GeneralModule.hpp

  IGESDraw_LabelDisplay.cxx
  IGESDraw_LabelDisplay.hpp
  IGESDraw_NetworkSubfigure.cxx
  IGESDraw_NetworkSubfigure.hpp
  IGESDraw_NetworkSubfigureDef.cxx
  IGESDraw_NetworkSubfigureDef.hpp
  IGESDraw_PerspectiveView.cxx
  IGESDraw_PerspectiveView.hpp
  IGESDraw_Planar.cxx
  IGESDraw_Planar.hpp
  IGESDraw_Protocol.cxx
  IGESDraw_Protocol.hpp
  IGESDraw_ReadWriteModule.cxx
  IGESDraw_ReadWriteModule.hpp
  IGESDraw_RectArraySubfigure.cxx
  IGESDraw_RectArraySubfigure.hpp
  IGESDraw_SegmentedViewsVisible.cxx
  IGESDraw_SegmentedViewsVisible.hpp
  IGESDraw_SpecificModule.cxx
  IGESDraw_SpecificModule.hpp
  IGESDraw_ToolCircArraySubfigure.cxx
  IGESDraw_ToolCircArraySubfigure.hpp
  IGESDraw_ToolConnectPoint.cxx
  IGESDraw_ToolConnectPoint.hpp
  IGESDraw_ToolDrawing.cxx
  IGESDraw_ToolDrawing.hpp
  IGESDraw_ToolDrawingWithRotation.cxx
  IGESDraw_ToolDrawingWithRotation.hpp
  IGESDraw_ToolLabelDisplay.cxx
  IGESDraw_ToolLabelDisplay.hpp
  IGESDraw_ToolNetworkSubfigure.cxx
  IGESDraw_ToolNetworkSubfigure.hpp
  IGESDraw_ToolNetworkSubfigureDef.cxx
  IGESDraw_ToolNetworkSubfigureDef.hpp
  IGESDraw_ToolPerspectiveView.cxx
  IGESDraw_ToolPerspectiveView.hpp
  IGESDraw_ToolPlanar.cxx
  IGESDraw_ToolPlanar.hpp
  IGESDraw_ToolRectArraySubfigure.cxx
  IGESDraw_ToolRectArraySubfigure.hpp
  IGESDraw_ToolSegmentedViewsVisible.cxx
  IGESDraw_ToolSegmentedViewsVisible.hpp
  IGESDraw_ToolView.cxx
  IGESDraw_ToolView.hpp
  IGESDraw_ToolViewsVisible.cxx
  IGESDraw_ToolViewsVisible.hpp
  IGESDraw_ToolViewsVisibleWithAttr.cxx
  IGESDraw_ToolViewsVisibleWithAttr.hpp
  IGESDraw_View.cxx
  IGESDraw_View.hpp
  IGESDraw_ViewsVisible.cxx
  IGESDraw_ViewsVisible.hpp
  IGESDraw_ViewsVisibleWithAttr.cxx
  IGESDraw_ViewsVisibleWithAttr.hpp
)
