# Source files for GC package
set(OCCT_GC_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_GC_FILES
  GC_MakeArcOfCircle.cxx
  GC_MakeArcOfCircle.hpp
  GC_MakeArcOfEllipse.cxx
  GC_MakeArcOfEllipse.hpp
  GC_MakeArcOfHyperbola.cxx
  GC_MakeArcOfHyperbola.hpp
  GC_MakeArcOfParabola.cxx
  GC_MakeArcOfParabola.hpp
  GC_MakeCircle.cxx
  GC_MakeCircle.hpp
  GC_MakeConicalSurface.cxx
  GC_MakeConicalSurface.hpp
  GC_MakeCylindricalSurface.cxx
  GC_MakeCylindricalSurface.hpp
  GC_MakeEllipse.cxx
  GC_MakeEllipse.hpp
  GC_MakeHyperbola.cxx
  GC_MakeHyperbola.hpp
  GC_MakeLine.cxx
  GC_MakeLine.hpp
  GC_MakeMirror.cxx
  GC_MakeMirror.hpp
  GC_MakePlane.cxx
  GC_MakePlane.hpp
  GC_MakeRotation.cxx
  GC_MakeRotation.hpp
  GC_MakeScale.cxx
  GC_MakeScale.hpp
  GC_MakeSegment.cxx
  GC_MakeSegment.hpp
  GC_MakeTranslation.cxx
  GC_MakeTranslation.hpp
  GC_MakeTrimmedCone.cxx
  GC_MakeTrimmedCone.hpp
  GC_MakeTrimmedCylinder.cxx
  GC_MakeTrimmedCylinder.hpp
  GC_Root.hpp
)
