# Source files for BRepFill package
set(OCCT_BRepFill_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_BRepFill_FILES
  BRepFill.cxx
  BRepFill.hpp
  BRepFill_ACRLaw.cxx
  BRepFill_ACRLaw.hpp
  BRepFill_AdvancedEvolved.cxx
  BRepFill_AdvancedEvolved.hpp
  BRepFill_ApproxSeewing.cxx
  BRepFill_ApproxSeewing.hpp
  BRepFill_CompatibleWires.cxx
  BRepFill_CompatibleWires.hpp
  BRepFill_ComputeCLine.hpp
  BRepFill_ComputeCLine_0.cxx
  BRepFill_CurveConstraint.cxx
  BRepFill_CurveConstraint.hpp

  BRepFill_Draft.cxx
  BRepFill_Draft.hpp
  BRepFill_DraftLaw.cxx
  BRepFill_DraftLaw.hpp
  BRepFill_Edge3DLaw.cxx
  BRepFill_Edge3DLaw.hpp
  BRepFill_EdgeFaceAndOrder.cxx
  BRepFill_EdgeFaceAndOrder.hpp
  BRepFill_EdgeOnSurfLaw.cxx
  BRepFill_EdgeOnSurfLaw.hpp
  BRepFill_Evolved.cxx
  BRepFill_Evolved.hpp
  BRepFill_FaceAndOrder.cxx
  BRepFill_FaceAndOrder.hpp
  BRepFill_Filling.cxx
  BRepFill_Filling.hpp
  BRepFill_Generator.cxx
  BRepFill_Generator.hpp

  BRepFill_LocationLaw.cxx
  BRepFill_LocationLaw.hpp
  BRepFill_MultiLine.cxx
  BRepFill_MultiLine.hpp
  BRepFill_NSections.cxx
  BRepFill_NSections.hpp
  BRepFill_OffsetAncestors.cxx
  BRepFill_OffsetAncestors.hpp
  BRepFill_OffsetWire.cxx
  BRepFill_OffsetWire.hpp
  BRepFill_Pipe.cxx
  BRepFill_Pipe.hpp
  BRepFill_PipeShell.cxx
  BRepFill_PipeShell.hpp
  BRepFill_Section.cxx
  BRepFill_Section.hpp
  BRepFill_SectionLaw.cxx
  BRepFill_SectionLaw.hpp
  BRepFill_SectionPlacement.cxx
  BRepFill_SectionPlacement.hpp

  BRepFill_ShapeLaw.cxx
  BRepFill_ShapeLaw.hpp
  BRepFill_Sweep.cxx
  BRepFill_Sweep.hpp
  BRepFill_ThruSectionErrorStatus.hpp
  BRepFill_TransitionStyle.hpp
  BRepFill_TrimEdgeTool.cxx
  BRepFill_TrimEdgeTool.hpp
  BRepFill_TrimShellCorner.cxx
  BRepFill_TrimShellCorner.hpp
  BRepFill_TrimSurfaceTool.cxx
  BRepFill_TrimSurfaceTool.hpp
  BRepFill_TypeOfContact.hpp
)
