# Source files for Graphic3d package
set(OCCT_Graphic3d_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_Graphic3d_FILES
  Graphic3d_AlphaMode.hpp
  Graphic3d_ArrayOfPoints.hpp
  Graphic3d_ArrayOfPolygons.hpp
  Graphic3d_ArrayOfPolylines.hpp
  Graphic3d_ArrayOfPrimitives.cxx
  Graphic3d_ArrayOfPrimitives.hpp
  Graphic3d_ArrayOfQuadrangles.hpp
  Graphic3d_ArrayOfQuadrangleStrips.hpp
  Graphic3d_ArrayOfSegments.hpp
  Graphic3d_ArrayOfTriangleFans.hpp
  Graphic3d_ArrayOfTriangles.hpp
  Graphic3d_ArrayOfTriangleStrips.hpp
  Graphic3d_Aspects.cxx
  Graphic3d_Aspects.hpp
  Graphic3d_AspectFillArea3d.cxx
  Graphic3d_AspectFillArea3d.hpp
  Graphic3d_AspectLine3d.cxx
  Graphic3d_AspectLine3d.hpp
  Graphic3d_AspectMarker3d.cxx
  Graphic3d_AspectMarker3d.hpp
  Graphic3d_AspectText3d.cxx
  Graphic3d_AspectText3d.hpp
  Graphic3d_AttribBuffer.cxx
  Graphic3d_AttribBuffer.hpp
  Graphic3d_BndBox3d.hpp
  
  Graphic3d_BoundBuffer.hpp
  Graphic3d_BSDF.cxx
  Graphic3d_BSDF.hpp
  Graphic3d_Buffer.cxx
  Graphic3d_Buffer.hpp
  Graphic3d_BufferType.hpp
  Graphic3d_BvhCStructureSet.cxx
  Graphic3d_BvhCStructureSet.hpp
  Graphic3d_BvhCStructureSetTrsfPers.cxx
  Graphic3d_BvhCStructureSetTrsfPers.hpp
  Graphic3d_Camera.cxx
  Graphic3d_Camera.hpp
  Graphic3d_CameraTile.cxx
  Graphic3d_CameraTile.hpp
  Graphic3d_CLight.cxx
  Graphic3d_CLight.hpp
  Graphic3d_ClipPlane.cxx
  Graphic3d_ClipPlane.hpp
  Graphic3d_CStructure.cxx
  Graphic3d_CStructure.hpp
  Graphic3d_CubeMap.cxx
  Graphic3d_CubeMap.hpp
  Graphic3d_CubeMapOrder.cxx
  Graphic3d_CubeMapOrder.hpp
  Graphic3d_CubeMapPacked.cxx
  Graphic3d_CubeMapPacked.hpp
  Graphic3d_CubeMapSeparate.cxx
  Graphic3d_CubeMapSeparate.hpp
  Graphic3d_CullingTool.cxx
  Graphic3d_CullingTool.hpp
  Graphic3d_CView.cxx
  Graphic3d_CView.hpp
  Graphic3d_DataStructureManager.cxx
  Graphic3d_DataStructureManager.hpp
  Graphic3d_DiagnosticInfo.hpp
  Graphic3d_DisplayPriority.hpp
  Graphic3d_FrameStats.cxx
  Graphic3d_FrameStats.hpp
  Graphic3d_FrameStatsData.cxx
  Graphic3d_FrameStatsData.hpp
  Graphic3d_GraduatedTrihedron.hpp
  Graphic3d_GraphicDriver.cxx
  Graphic3d_GraphicDriver.hpp
  Graphic3d_GraphicDriverFactory.cxx
  Graphic3d_GraphicDriverFactory.hpp
  Graphic3d_Group.cxx
  Graphic3d_Group.hpp
  Graphic3d_GroupDefinitionError.hpp
  Graphic3d_HatchStyle.hpp
  Graphic3d_HatchStyle.cxx
  Graphic3d_PresentationAttributes.hpp
  Graphic3d_PresentationAttributes.cxx
  Graphic3d_HorizontalTextAlignment.hpp
  Graphic3d_IndexBuffer.hpp
  Graphic3d_MutableIndexBuffer.hpp
  Graphic3d_LevelOfTextureAnisotropy.hpp
  Graphic3d_LightSet.cxx
  Graphic3d_LightSet.hpp

  Graphic3d_MarkerImage.cxx
  Graphic3d_MarkerImage.hpp
  Graphic3d_MarkerImage_1.hpp

  Graphic3d_MaterialAspect.cxx
  Graphic3d_MaterialAspect.hpp
  Graphic3d_MaterialDefinitionError.hpp
  Graphic3d_MediaTexture.cxx
  Graphic3d_MediaTexture.hpp
  Graphic3d_MediaTextureSet.cxx
  Graphic3d_MediaTextureSet.hpp
  Graphic3d_NameOfMaterial.hpp
  Graphic3d_NameOfTexture1D.hpp
  Graphic3d_NameOfTexture2D.hpp
  Graphic3d_NameOfTextureEnv.hpp

  Graphic3d_PBRMaterial.cxx
  Graphic3d_PBRMaterial.hpp
  Graphic3d_PolygonOffset.cxx
  Graphic3d_PolygonOffset.hpp
  Graphic3d_PriorityDefinitionError.hpp
  Graphic3d_RenderingParams.cxx
  Graphic3d_RenderingParams.hpp
  Graphic3d_RenderTransparentMethod.hpp

  Graphic3d_SequenceOfHClipPlane.cxx
  Graphic3d_SequenceOfHClipPlane.hpp

  Graphic3d_ShaderAttribute.cxx
  Graphic3d_ShaderAttribute.hpp
  Graphic3d_ShaderFlags.hpp
  Graphic3d_ShaderManager.cxx
  Graphic3d_ShaderManager.hpp
  Graphic3d_ShaderObject.cxx
  Graphic3d_ShaderObject.hpp
  Graphic3d_ShaderProgram.cxx
  Graphic3d_ShaderProgram.hpp
  Graphic3d_ShaderVariable.cxx
  Graphic3d_ShaderVariable.hpp
  Graphic3d_StereoMode.hpp
  Graphic3d_Structure.cxx
  Graphic3d_Structure.hpp
  Graphic3d_StructureDefinitionError.hpp
  Graphic3d_StructureManager.cxx
  Graphic3d_StructureManager.hpp
  Graphic3d_TextPath.hpp
  Graphic3d_Text.cxx
  Graphic3d_Text.hpp
  Graphic3d_Texture1D.cxx
  Graphic3d_Texture1D.hpp
  Graphic3d_Texture1Dmanual.cxx
  Graphic3d_Texture1Dmanual.hpp
  Graphic3d_Texture1Dsegment.cxx
  Graphic3d_Texture1Dsegment.hpp
  Graphic3d_Texture2D.cxx
  Graphic3d_Texture2D.hpp

  Graphic3d_Texture2Dplane.cxx
  Graphic3d_Texture2Dplane.hpp
  Graphic3d_Texture3D.cxx
  Graphic3d_Texture3D.hpp
  Graphic3d_TextureEnv.cxx
  Graphic3d_TextureEnv.hpp
  Graphic3d_TextureMap.cxx
  Graphic3d_TextureMap.hpp
  Graphic3d_TextureParams.cxx
  Graphic3d_TextureParams.hpp
  Graphic3d_TextureRoot.cxx
  Graphic3d_TextureRoot.hpp
  Graphic3d_TextureUnit.hpp
  Graphic3d_TextureSet.cxx
  Graphic3d_TextureSet.hpp
  Graphic3d_TextureSetBits.hpp
  Graphic3d_TransformPers.hpp
  Graphic3d_TransformPers.cxx
  Graphic3d_TransformPersScaledAbove.hpp
  Graphic3d_TransformPersScaledAbove.cxx
  Graphic3d_TransformUtils.hpp
  Graphic3d_TransModeFlags.hpp
  Graphic3d_TypeOfBackfacingModel.hpp
  Graphic3d_TypeOfBackground.hpp
  Graphic3d_TypeOfPrimitiveArray.hpp
  Graphic3d_TypeOfReflection.hpp
  Graphic3d_TypeOfShadingModel.hpp
  Graphic3d_TypeOfTexture.hpp
  Graphic3d_TypeOfTextureFilter.hpp
  Graphic3d_TypeOfTextureMode.hpp

  Graphic3d_Vertex.cxx
  Graphic3d_Vertex.hpp
  Graphic3d_VerticalTextAlignment.hpp
  Graphic3d_ViewAffinity.cxx
  Graphic3d_ViewAffinity.hpp
  Graphic3d_WorldViewProjState.hpp
  Graphic3d_Layer.cxx
  Graphic3d_Layer.hpp
  Graphic3d_ZLayerId.hpp
  Graphic3d_ZLayerSettings.hpp
)
