# Source files for Draw package
set(OCCT_Draw_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_Draw_FILES
  Draw.cxx
  Draw.hpp
  Draw_Appli.hpp
  Draw_Axis2D.cxx
  Draw_Axis2D.hpp
  Draw_Axis3D.cxx
  Draw_Axis3D.hpp
  Draw_BasicCommands.cxx
  Draw_Box.cxx
  Draw_Box.hpp
  Draw_Chronometer.cxx
  Draw_Chronometer.hpp
  Draw_Circle2D.cxx
  Draw_Circle2D.hpp
  Draw_Circle3D.cxx
  Draw_Circle3D.hpp
  Draw_Color.cxx
  Draw_Color.hpp
  Draw_ColorKind.hpp
  Draw_Commands.cxx
  Draw_Debug.cxx
  Draw_Display.cxx
  Draw_Display.hpp
  Draw_Drawable2D.cxx
  Draw_Drawable2D.hpp
  Draw_Drawable3D.cxx
  Draw_Drawable3D.hpp
  Draw_Failure.hpp
  Draw_GraphicCommands.cxx
  Draw_Grid.cxx
  Draw_Grid.hpp
  Draw_Interpretor.cxx
  Draw_Interpretor.hpp
  Draw_Main.cxx
  Draw_Main.hpp

  Draw_Marker2D.cxx
  Draw_Marker2D.hpp
  Draw_Marker3D.cxx
  Draw_Marker3D.hpp
  Draw_MarkerShape.hpp
  Draw_MessageCommands.cxx
  Draw_Number.cxx
  Draw_Number.hpp
  Draw_PloadCommands.cxx
  Draw_PluginMacro.hpp
  Draw_Printer.cxx
  Draw_Printer.hpp
  Draw_ProgressIndicator.cxx
  Draw_ProgressIndicator.hpp
  Draw_Replace.tcl
  Draw_Segment2D.cxx
  Draw_Segment2D.hpp
  Draw_Segment3D.cxx
  Draw_Segment3D.hpp

  Draw_Text2D.cxx
  Draw_Text2D.hpp
  Draw_Text3D.cxx
  Draw_Text3D.hpp
  Draw_UnitCommands.cxx
  Draw_VariableCommands.cxx
  Draw_View.cxx
  Draw_View.hpp
  Draw_Viewer.cxx
  Draw_Viewer.hpp
  Draw_Window.cxx
  Draw_Window.hpp
  Draw_Window_1.mm
  Draw_WNTCommandWindow.cxx
  Draw_WNTCommandWindow.hpp
  Draw_WNTInit.cxx
  Draw_WNTInit.hpp
  Draw_WNTMainWindow.cxx
  Draw_WNTMainWindow.hpp
  Draw_WNTRessource.hpp
)
