# Source files for PrsDim package
set(OCCT_PrsDim_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_PrsDim_FILES
  PrsDim.cxx
  PrsDim.hpp
  PrsDim_AngleDimension.cxx
  PrsDim_AngleDimension.hpp
  PrsDim_Chamf2dDimension.cxx
  PrsDim_Chamf2dDimension.hpp
  PrsDim_Chamf3dDimension.cxx
  PrsDim_Chamf3dDimension.hpp
  PrsDim_ConcentricRelation.cxx
  PrsDim_ConcentricRelation.hpp
  PrsDim_DiameterDimension.cxx
  PrsDim_DiameterDimension.hpp
  PrsDim_Dimension.cxx
  PrsDim_Dimension.hpp
  PrsDim_DimensionOwner.cxx
  PrsDim_DimensionOwner.hpp
  PrsDim_EllipseRadiusDimension.cxx
  PrsDim_EllipseRadiusDimension.hpp
  PrsDim_EqualDistanceRelation.cxx
  PrsDim_EqualDistanceRelation.hpp
  PrsDim_EqualRadiusRelation.cxx
  PrsDim_EqualRadiusRelation.hpp
  PrsDim_FixRelation.cxx
  PrsDim_FixRelation.hpp
  PrsDim_IdenticRelation.cxx
  PrsDim_IdenticRelation.hpp
  PrsDim_LengthDimension.cxx
  PrsDim_LengthDimension.hpp
  PrsDim_MaxRadiusDimension.cxx
  PrsDim_MaxRadiusDimension.hpp
  PrsDim_MidPointRelation.cxx
  PrsDim_MidPointRelation.hpp
  PrsDim_MinRadiusDimension.cxx
  PrsDim_MinRadiusDimension.hpp
  PrsDim_OffsetDimension.cxx
  PrsDim_OffsetDimension.hpp
  PrsDim_ParallelRelation.cxx
  PrsDim_ParallelRelation.hpp
  PrsDim_PerpendicularRelation.cxx
  PrsDim_PerpendicularRelation.hpp
  PrsDim_RadiusDimension.cxx
  PrsDim_RadiusDimension.hpp
  PrsDim_Relation.cxx
  PrsDim_Relation.hpp
  PrsDim_SymmetricRelation.cxx
  PrsDim_SymmetricRelation.hpp
  PrsDim_TangentRelation.cxx
  PrsDim_TangentRelation.hpp
  PrsDim_KindOfDimension.hpp
  PrsDim_KindOfRelation.hpp
  PrsDim_KindOfSurface.hpp
)
