# Source files for RWStepGeom package
set(OCCT_RWStepGeom_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_RWStepGeom_FILES
  RWStepGeom_RWAxis1Placement.cxx
  RWStepGeom_RWAxis1Placement.hpp
  RWStepGeom_RWAxis2Placement2d.cxx
  RWStepGeom_RWAxis2Placement2d.hpp
  RWStepGeom_RWAxis2Placement3d.cxx
  RWStepGeom_RWAxis2Placement3d.hpp
  RWStepGeom_RWBezierCurve.cxx
  RWStepGeom_RWBezierCurve.hpp
  RWStepGeom_RWBezierCurveAndRationalBSplineCurve.cxx
  RWStepGeom_RWBezierCurveAndRationalBSplineCurve.hpp
  RWStepGeom_RWBezierSurface.cxx
  RWStepGeom_RWBezierSurface.hpp
  RWStepGeom_RWBezierSurfaceAndRationalBSplineSurface.cxx
  RWStepGeom_RWBezierSurfaceAndRationalBSplineSurface.hpp
  RWStepGeom_RWBoundaryCurve.cxx
  RWStepGeom_RWBoundaryCurve.hpp
  RWStepGeom_RWBoundedCurve.cxx
  RWStepGeom_RWBoundedCurve.hpp
  RWStepGeom_RWBoundedSurface.cxx
  RWStepGeom_RWBoundedSurface.hpp
  RWStepGeom_RWBSplineCurve.cxx
  RWStepGeom_RWBSplineCurve.hpp
  RWStepGeom_RWBSplineCurveWithKnots.cxx
  RWStepGeom_RWBSplineCurveForm.hpp
  RWStepGeom_RWBSplineCurveWithKnots.hpp
  RWStepGeom_RWBSplineCurveWithKnotsAndRationalBSplineCurve.cxx
  RWStepGeom_RWBSplineCurveWithKnotsAndRationalBSplineCurve.hpp
  RWStepGeom_RWBSplineSurface.cxx
  RWStepGeom_RWBSplineSurface.hpp
  RWStepGeom_RWBSplineSurfaceWithKnots.cxx
  RWStepGeom_RWBSplineSurfaceForm.hpp
  RWStepGeom_RWBSplineSurfaceWithKnots.hpp
  RWStepGeom_RWBSplineSurfaceWithKnotsAndRationalBSplineSurface.cxx
  RWStepGeom_RWBSplineSurfaceWithKnotsAndRationalBSplineSurface.hpp
  RWStepGeom_RWCartesianPoint.cxx
  RWStepGeom_RWCartesianPoint.hpp
  RWStepGeom_RWCartesianTransformationOperator.cxx
  RWStepGeom_RWCartesianTransformationOperator.hpp
  RWStepGeom_RWCartesianTransformationOperator3d.cxx
  RWStepGeom_RWCartesianTransformationOperator3d.hpp
  RWStepGeom_RWCircle.cxx
  RWStepGeom_RWCircle.hpp
  RWStepGeom_RWCompositeCurve.cxx
  RWStepGeom_RWCompositeCurve.hpp
  RWStepGeom_RWCompositeCurveOnSurface.cxx
  RWStepGeom_RWCompositeCurveOnSurface.hpp
  RWStepGeom_RWCompositeCurveSegment.cxx
  RWStepGeom_RWCompositeCurveSegment.hpp
  RWStepGeom_RWConic.cxx
  RWStepGeom_RWConic.hpp
  RWStepGeom_RWConicalSurface.cxx
  RWStepGeom_RWConicalSurface.hpp
  RWStepGeom_RWCurve.cxx
  RWStepGeom_RWCurve.hpp
  RWStepGeom_RWCurveBoundedSurface.cxx
  RWStepGeom_RWCurveBoundedSurface.hpp
  RWStepGeom_RWCurveReplica.cxx
  RWStepGeom_RWCurveReplica.hpp
  RWStepGeom_RWCylindricalSurface.cxx
  RWStepGeom_RWCylindricalSurface.hpp
  RWStepGeom_RWDegeneratePcurve.cxx
  RWStepGeom_RWDegeneratePcurve.hpp
  RWStepGeom_RWDegenerateToroidalSurface.cxx
  RWStepGeom_RWDegenerateToroidalSurface.hpp
  RWStepGeom_RWDirection.cxx
  RWStepGeom_RWDirection.hpp
  RWStepGeom_RWElementarySurface.cxx
  RWStepGeom_RWElementarySurface.hpp
  RWStepGeom_RWEllipse.cxx
  RWStepGeom_RWEllipse.hpp
  RWStepGeom_RWEvaluatedDegeneratePcurve.cxx
  RWStepGeom_RWEvaluatedDegeneratePcurve.hpp
  RWStepGeom_RWGeometricRepresentationContext.cxx
  RWStepGeom_RWGeometricRepresentationContext.hpp
  RWStepGeom_RWGeometricRepresentationContextAndGlobalUnitAssignedContext.cxx
  RWStepGeom_RWGeometricRepresentationContextAndGlobalUnitAssignedContext.hpp
  RWStepGeom_RWGeometricRepresentationContextAndParametricRepresentationContext.cxx
  RWStepGeom_RWGeometricRepresentationContextAndParametricRepresentationContext.hpp
  RWStepGeom_RWGeometricRepresentationItem.cxx
  RWStepGeom_RWGeometricRepresentationItem.hpp
  RWStepGeom_RWGeomRepContextAndGlobUnitAssCtxAndGlobUncertaintyAssCtx.cxx
  RWStepGeom_RWGeomRepContextAndGlobUnitAssCtxAndGlobUncertaintyAssCtx.hpp
  RWStepGeom_RWHyperbola.cxx
  RWStepGeom_RWHyperbola.hpp
  RWStepGeom_RWIntersectionCurve.cxx
  RWStepGeom_RWIntersectionCurve.hpp
  RWStepGeom_RWKnotType.hpp
  RWStepGeom_RWLine.cxx
  RWStepGeom_RWLine.hpp
  RWStepGeom_RWOffsetCurve3d.cxx
  RWStepGeom_RWOffsetCurve3d.hpp
  RWStepGeom_RWOffsetSurface.cxx
  RWStepGeom_RWOffsetSurface.hpp
  RWStepGeom_RWOrientedSurface.cxx
  RWStepGeom_RWOrientedSurface.hpp
  RWStepGeom_RWOuterBoundaryCurve.cxx
  RWStepGeom_RWOuterBoundaryCurve.hpp
  RWStepGeom_RWParabola.cxx
  RWStepGeom_RWParabola.hpp
  RWStepGeom_RWPcurve.cxx
  RWStepGeom_RWPcurve.hpp
  RWStepGeom_RWPlacement.cxx
  RWStepGeom_RWPlacement.hpp
  RWStepGeom_RWPlane.cxx
  RWStepGeom_RWPlane.hpp
  RWStepGeom_RWPoint.cxx
  RWStepGeom_RWPoint.hpp
  RWStepGeom_RWPointOnCurve.cxx
  RWStepGeom_RWPointOnCurve.hpp
  RWStepGeom_RWPointOnSurface.cxx
  RWStepGeom_RWPointOnSurface.hpp
  RWStepGeom_RWPointReplica.cxx
  RWStepGeom_RWPointReplica.hpp
  RWStepGeom_RWPolyline.cxx
  RWStepGeom_RWPolyline.hpp
  RWStepGeom_RWPreferredSurfaceCurveRepresentation.hpp
  RWStepGeom_RWQuasiUniformCurve.cxx
  RWStepGeom_RWQuasiUniformCurve.hpp
  RWStepGeom_RWQuasiUniformCurveAndRationalBSplineCurve.cxx
  RWStepGeom_RWQuasiUniformCurveAndRationalBSplineCurve.hpp
  RWStepGeom_RWQuasiUniformSurface.cxx
  RWStepGeom_RWQuasiUniformSurface.hpp
  RWStepGeom_RWQuasiUniformSurfaceAndRationalBSplineSurface.cxx
  RWStepGeom_RWQuasiUniformSurfaceAndRationalBSplineSurface.hpp
  RWStepGeom_RWRationalBSplineCurve.cxx
  RWStepGeom_RWRationalBSplineCurve.hpp
  RWStepGeom_RWRationalBSplineSurface.cxx
  RWStepGeom_RWRationalBSplineSurface.hpp
  RWStepGeom_RWRectangularCompositeSurface.cxx
  RWStepGeom_RWRectangularCompositeSurface.hpp
  RWStepGeom_RWRectangularTrimmedSurface.cxx
  RWStepGeom_RWRectangularTrimmedSurface.hpp
  RWStepGeom_RWReparametrisedCompositeCurveSegment.cxx
  RWStepGeom_RWReparametrisedCompositeCurveSegment.hpp
  RWStepGeom_RWSeamCurve.cxx
  RWStepGeom_RWSeamCurve.hpp
  RWStepGeom_RWSphericalSurface.cxx
  RWStepGeom_RWSphericalSurface.hpp
  RWStepGeom_RWSuParameters.cxx
  RWStepGeom_RWSuParameters.hpp
  RWStepGeom_RWSurface.cxx
  RWStepGeom_RWSurface.hpp
  RWStepGeom_RWSurfaceCurve.cxx
  RWStepGeom_RWSurfaceCurve.hpp
  RWStepGeom_RWSurfaceCurveAndBoundedCurve.cxx
  RWStepGeom_RWSurfaceCurveAndBoundedCurve.hpp
  RWStepGeom_RWSurfaceOfLinearExtrusion.cxx
  RWStepGeom_RWSurfaceOfLinearExtrusion.hpp
  RWStepGeom_RWSurfaceOfRevolution.cxx
  RWStepGeom_RWSurfaceOfRevolution.hpp
  RWStepGeom_RWSurfacePatch.cxx
  RWStepGeom_RWSurfacePatch.hpp
  RWStepGeom_RWSurfaceReplica.cxx
  RWStepGeom_RWSurfaceReplica.hpp
  RWStepGeom_RWSweptSurface.cxx
  RWStepGeom_RWSweptSurface.hpp
  RWStepGeom_RWToroidalSurface.cxx
  RWStepGeom_RWToroidalSurface.hpp
  RWStepGeom_RWTransitionCode.hpp
  RWStepGeom_RWTrimmedCurve.cxx
  RWStepGeom_RWTrimmedCurve.hpp
  RWStepGeom_RWUniformCurve.cxx
  RWStepGeom_RWUniformCurve.hpp
  RWStepGeom_RWUniformCurveAndRationalBSplineCurve.cxx
  RWStepGeom_RWUniformCurveAndRationalBSplineCurve.hpp
  RWStepGeom_RWUniformSurface.cxx
  RWStepGeom_RWUniformSurface.hpp
  RWStepGeom_RWUniformSurfaceAndRationalBSplineSurface.cxx
  RWStepGeom_RWUniformSurfaceAndRationalBSplineSurface.hpp
  RWStepGeom_RWVector.cxx
  RWStepGeom_RWVector.hpp
)
