# Source files for StepShape package
set(OCCT_StepShape_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_StepShape_FILES
  StepShape_AdvancedBrepShapeRepresentation.cxx
  StepShape_AdvancedBrepShapeRepresentation.hpp
  StepShape_AdvancedFace.cxx
  StepShape_AdvancedFace.hpp
  StepShape_AngleRelator.hpp
  StepShape_AngularLocation.cxx
  StepShape_AngularLocation.hpp
  StepShape_AngularSize.cxx
  StepShape_AngularSize.hpp

  StepShape_Block.cxx
  StepShape_Block.hpp
  StepShape_BooleanOperand.cxx
  StepShape_BooleanOperand.hpp
  StepShape_BooleanOperator.hpp
  StepShape_BooleanResult.cxx
  StepShape_BooleanResult.hpp
  StepShape_BoxDomain.cxx
  StepShape_BoxDomain.hpp
  StepShape_BoxedHalfSpace.cxx
  StepShape_BoxedHalfSpace.hpp
  StepShape_BrepWithVoids.cxx
  StepShape_BrepWithVoids.hpp
  StepShape_ClosedShell.cxx
  StepShape_ClosedShell.hpp
  StepShape_CompoundShapeRepresentation.cxx
  StepShape_CompoundShapeRepresentation.hpp
  StepShape_ConnectedEdgeSet.cxx
  StepShape_ConnectedEdgeSet.hpp
  StepShape_ConnectedFaceSet.cxx
  StepShape_ConnectedFaceSet.hpp
  StepShape_ConnectedFaceShapeRepresentation.cxx
  StepShape_ConnectedFaceShapeRepresentation.hpp
  StepShape_ConnectedFaceSubSet.cxx
  StepShape_ConnectedFaceSubSet.hpp
  StepShape_ContextDependentShapeRepresentation.cxx
  StepShape_ContextDependentShapeRepresentation.hpp
  StepShape_CsgPrimitive.cxx
  StepShape_CsgPrimitive.hpp
  StepShape_CsgSelect.cxx
  StepShape_CsgSelect.hpp
  StepShape_CsgShapeRepresentation.cxx
  StepShape_CsgShapeRepresentation.hpp
  StepShape_CsgSolid.cxx
  StepShape_CsgSolid.hpp
  StepShape_DefinitionalRepresentationAndShapeRepresentation.cxx
  StepShape_DefinitionalRepresentationAndShapeRepresentation.hpp
  StepShape_DimensionalCharacteristic.cxx
  StepShape_DimensionalCharacteristic.hpp
  StepShape_DimensionalCharacteristicRepresentation.cxx
  StepShape_DimensionalCharacteristicRepresentation.hpp
  StepShape_DimensionalLocation.cxx
  StepShape_DimensionalLocation.hpp
  StepShape_DimensionalLocationWithPath.cxx
  StepShape_DimensionalLocationWithPath.hpp
  StepShape_DimensionalSize.cxx
  StepShape_DimensionalSize.hpp
  StepShape_DimensionalSizeWithPath.cxx
  StepShape_DimensionalSizeWithPath.hpp
  StepShape_DirectedDimensionalLocation.cxx
  StepShape_DirectedDimensionalLocation.hpp
  StepShape_Edge.cxx
  StepShape_Edge.hpp
  StepShape_EdgeBasedWireframeModel.cxx
  StepShape_EdgeBasedWireframeModel.hpp
  StepShape_EdgeBasedWireframeShapeRepresentation.cxx
  StepShape_EdgeBasedWireframeShapeRepresentation.hpp
  StepShape_EdgeCurve.cxx
  StepShape_EdgeCurve.hpp
  StepShape_EdgeLoop.cxx
  StepShape_EdgeLoop.hpp
  StepShape_ExtrudedAreaSolid.cxx
  StepShape_ExtrudedAreaSolid.hpp
  StepShape_ExtrudedFaceSolid.cxx
  StepShape_ExtrudedFaceSolid.hpp
  StepShape_Face.cxx
  StepShape_Face.hpp
  StepShape_FaceBasedSurfaceModel.cxx
  StepShape_FaceBasedSurfaceModel.hpp
  StepShape_FaceBound.cxx
  StepShape_FaceBound.hpp
  StepShape_FaceOuterBound.cxx
  StepShape_FaceOuterBound.hpp
  StepShape_FaceSurface.cxx
  StepShape_FaceSurface.hpp
  StepShape_FacetedBrep.cxx
  StepShape_FacetedBrep.hpp
  StepShape_FacetedBrepAndBrepWithVoids.cxx
  StepShape_FacetedBrepAndBrepWithVoids.hpp
  StepShape_FacetedBrepShapeRepresentation.cxx
  StepShape_FacetedBrepShapeRepresentation.hpp
  StepShape_GeometricallyBoundedSurfaceShapeRepresentation.cxx
  StepShape_GeometricallyBoundedSurfaceShapeRepresentation.hpp
  StepShape_GeometricallyBoundedWireframeShapeRepresentation.cxx
  StepShape_GeometricallyBoundedWireframeShapeRepresentation.hpp
  StepShape_GeometricCurveSet.cxx
  StepShape_GeometricCurveSet.hpp
  StepShape_GeometricSet.cxx
  StepShape_GeometricSet.hpp
  StepShape_GeometricSetSelect.cxx
  StepShape_GeometricSetSelect.hpp
  StepShape_HalfSpaceSolid.cxx
  StepShape_HalfSpaceSolid.hpp

  StepShape_LimitsAndFits.cxx
  StepShape_LimitsAndFits.hpp
  StepShape_Loop.cxx
  StepShape_Loop.hpp
  StepShape_LoopAndPath.cxx
  StepShape_LoopAndPath.hpp
  StepShape_ManifoldSolidBrep.cxx
  StepShape_ManifoldSolidBrep.hpp
  StepShape_ManifoldSurfaceShapeRepresentation.cxx
  StepShape_ManifoldSurfaceShapeRepresentation.hpp
  StepShape_MeasureQualification.cxx
  StepShape_MeasureQualification.hpp
  StepShape_MeasureRepresentationItemAndQualifiedRepresentationItem.cxx
  StepShape_MeasureRepresentationItemAndQualifiedRepresentationItem.hpp
  StepShape_NonManifoldSurfaceShapeRepresentation.cxx
  StepShape_NonManifoldSurfaceShapeRepresentation.hpp
  StepShape_OpenShell.cxx
  StepShape_OpenShell.hpp
  StepShape_OrientedClosedShell.cxx
  StepShape_OrientedClosedShell.hpp
  StepShape_OrientedEdge.cxx
  StepShape_OrientedEdge.hpp
  StepShape_OrientedFace.cxx
  StepShape_OrientedFace.hpp
  StepShape_OrientedOpenShell.cxx
  StepShape_OrientedOpenShell.hpp
  StepShape_OrientedPath.cxx
  StepShape_OrientedPath.hpp
  StepShape_Path.cxx
  StepShape_Path.hpp
  StepShape_PlusMinusTolerance.cxx
  StepShape_PlusMinusTolerance.hpp
  StepShape_PointRepresentation.cxx
  StepShape_PointRepresentation.hpp
  StepShape_PolyLoop.cxx
  StepShape_PolyLoop.hpp
  StepShape_PrecisionQualifier.cxx
  StepShape_PrecisionQualifier.hpp
  StepShape_QualifiedRepresentationItem.cxx
  StepShape_QualifiedRepresentationItem.hpp
  StepShape_ReversibleTopologyItem.cxx
  StepShape_ReversibleTopologyItem.hpp
  StepShape_RevolvedAreaSolid.cxx
  StepShape_RevolvedAreaSolid.hpp
  StepShape_RevolvedFaceSolid.cxx
  StepShape_RevolvedFaceSolid.hpp
  StepShape_RightAngularWedge.cxx
  StepShape_RightAngularWedge.hpp
  StepShape_RightCircularCone.cxx
  StepShape_RightCircularCone.hpp
  StepShape_RightCircularCylinder.cxx
  StepShape_RightCircularCylinder.hpp
  StepShape_SeamEdge.cxx
  StepShape_SeamEdge.hpp
  StepShape_ShapeDefinitionRepresentation.cxx
  StepShape_ShapeDefinitionRepresentation.hpp
  StepShape_ShapeDimensionRepresentation.cxx
  StepShape_ShapeDimensionRepresentation.hpp
  StepShape_ShapeDimensionRepresentationItem.cxx
  StepShape_ShapeDimensionRepresentationItem.hpp
  StepShape_ShapeRepresentation.cxx
  StepShape_ShapeRepresentation.hpp
  StepShape_ShapeRepresentationWithParameters.cxx
  StepShape_ShapeRepresentationWithParameters.hpp
  StepShape_Shell.cxx
  StepShape_Shell.hpp
  StepShape_ShellBasedSurfaceModel.cxx
  StepShape_ShellBasedSurfaceModel.hpp
  StepShape_SolidModel.cxx
  StepShape_SolidModel.hpp
  StepShape_SolidReplica.cxx
  StepShape_SolidReplica.hpp
  StepShape_Sphere.cxx
  StepShape_Sphere.hpp
  StepShape_Subedge.cxx
  StepShape_Subedge.hpp
  StepShape_Subface.cxx
  StepShape_Subface.hpp
  StepShape_SurfaceModel.cxx
  StepShape_SurfaceModel.hpp
  StepShape_SweptAreaSolid.cxx
  StepShape_SweptAreaSolid.hpp
  StepShape_SweptFaceSolid.cxx
  StepShape_SweptFaceSolid.hpp
  StepShape_ToleranceMethodDefinition.cxx
  StepShape_ToleranceMethodDefinition.hpp
  StepShape_ToleranceValue.cxx
  StepShape_ToleranceValue.hpp
  StepShape_TopologicalRepresentationItem.cxx
  StepShape_TopologicalRepresentationItem.hpp
  StepShape_Torus.cxx
  StepShape_Torus.hpp
  StepShape_TransitionalShapeRepresentation.cxx
  StepShape_TransitionalShapeRepresentation.hpp
  StepShape_TypeQualifier.cxx
  StepShape_TypeQualifier.hpp
  StepShape_ValueFormatTypeQualifier.cxx
  StepShape_ValueFormatTypeQualifier.hpp
  StepShape_ValueQualifier.cxx
  StepShape_ValueQualifier.hpp
  StepShape_Vertex.cxx
  StepShape_Vertex.hpp
  StepShape_VertexLoop.cxx
  StepShape_VertexLoop.hpp
  StepShape_VertexPoint.cxx
  StepShape_VertexPoint.hpp
)
