# Source files for Geom2dGcc package
set(OCCT_Geom2dGcc_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_Geom2dGcc_FILES
  Geom2dGcc.cxx
  Geom2dGcc.hpp
  Geom2dGcc_Circ2d2TanOn.cxx
  Geom2dGcc_Circ2d2TanOn.hpp
  Geom2dGcc_Circ2d2TanOnGeo.cxx
  Geom2dGcc_Circ2d2TanOnGeo.hpp
  Geom2dGcc_Circ2d2TanOnIter.cxx
  Geom2dGcc_Circ2d2TanOnIter.hpp
  Geom2dGcc_Circ2d2TanRad.cxx
  Geom2dGcc_Circ2d2TanRad.hpp
  Geom2dGcc_Circ2d2TanRadGeo.cxx
  Geom2dGcc_Circ2d2TanRadGeo.hpp
  Geom2dGcc_Circ2d3Tan.cxx
  Geom2dGcc_Circ2d3Tan.hpp
  Geom2dGcc_Circ2d3TanIter.cxx
  Geom2dGcc_Circ2d3TanIter.hpp
  Geom2dGcc_Circ2dTanCen.cxx
  Geom2dGcc_Circ2dTanCen.hpp
  Geom2dGcc_Circ2dTanCenGeo.cxx
  Geom2dGcc_Circ2dTanCenGeo.hpp
  Geom2dGcc_Circ2dTanOnRad.cxx
  Geom2dGcc_Circ2dTanOnRad.hpp
  Geom2dGcc_Circ2dTanOnRadGeo.cxx
  Geom2dGcc_Circ2dTanOnRadGeo.hpp
  Geom2dGcc_CurveTool.cxx
  Geom2dGcc_CurveTool.hpp
  Geom2dGcc_FunctionTanCirCu.cxx
  Geom2dGcc_FunctionTanCirCu.hpp
  Geom2dGcc_FunctionTanCuCu.cxx
  Geom2dGcc_FunctionTanCuCu.hpp
  Geom2dGcc_FunctionTanCuCuCu.cxx
  Geom2dGcc_FunctionTanCuCuCu.hpp
  Geom2dGcc_FunctionTanCuCuOnCu.cxx
  Geom2dGcc_FunctionTanCuCuOnCu.hpp
  Geom2dGcc_FunctionTanCuPnt.cxx
  Geom2dGcc_FunctionTanCuPnt.hpp
  Geom2dGcc_FunctionTanObl.cxx
  Geom2dGcc_FunctionTanObl.hpp
  Geom2dGcc_IsParallel.hpp
  Geom2dGcc_Lin2d2Tan.cxx
  Geom2dGcc_Lin2d2Tan.hpp
  Geom2dGcc_Lin2d2TanIter.cxx
  Geom2dGcc_Lin2d2TanIter.hpp
  Geom2dGcc_Lin2dTanObl.cxx
  Geom2dGcc_Lin2dTanObl.hpp
  Geom2dGcc_Lin2dTanOblIter.cxx
  Geom2dGcc_Lin2dTanOblIter.hpp
  Geom2dGcc_QCurve.cxx
  Geom2dGcc_QCurve.hpp
  Geom2dGcc_QualifiedCurve.cxx
  Geom2dGcc_QualifiedCurve.hpp
)
