# Source files for IGESDimen package
set(OCCT_IGESDimen_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_IGESDimen_FILES
  IGESDimen.cxx
  IGESDimen.hpp
  IGESDimen_AngularDimension.cxx
  IGESDimen_AngularDimension.hpp

  IGESDimen_BasicDimension.cxx
  IGESDimen_BasicDimension.hpp
  IGESDimen_CenterLine.cxx
  IGESDimen_CenterLine.hpp
  IGESDimen_CurveDimension.cxx
  IGESDimen_CurveDimension.hpp
  IGESDimen_DiameterDimension.cxx
  IGESDimen_DiameterDimension.hpp
  IGESDimen_DimensionDisplayData.cxx
  IGESDimen_DimensionDisplayData.hpp
  IGESDimen_DimensionedGeometry.cxx
  IGESDimen_DimensionedGeometry.hpp
  IGESDimen_DimensionTolerance.cxx
  IGESDimen_DimensionTolerance.hpp
  IGESDimen_DimensionUnits.cxx
  IGESDimen_DimensionUnits.hpp
  IGESDimen_FlagNote.cxx
  IGESDimen_FlagNote.hpp
  IGESDimen_GeneralLabel.cxx
  IGESDimen_GeneralLabel.hpp
  IGESDimen_GeneralModule.cxx
  IGESDimen_GeneralModule.hpp
  IGESDimen_GeneralNote.cxx
  IGESDimen_GeneralNote.hpp
  IGESDimen_GeneralSymbol.cxx
  IGESDimen_GeneralSymbol.hpp

  IGESDimen_LeaderArrow.cxx
  IGESDimen_LeaderArrow.hpp
  IGESDimen_LinearDimension.cxx
  IGESDimen_LinearDimension.hpp
  IGESDimen_NewDimensionedGeometry.cxx
  IGESDimen_NewDimensionedGeometry.hpp
  IGESDimen_NewGeneralNote.cxx
  IGESDimen_NewGeneralNote.hpp
  IGESDimen_OrdinateDimension.cxx
  IGESDimen_OrdinateDimension.hpp
  IGESDimen_PointDimension.cxx
  IGESDimen_PointDimension.hpp
  IGESDimen_Protocol.cxx
  IGESDimen_Protocol.hpp
  IGESDimen_RadiusDimension.cxx
  IGESDimen_RadiusDimension.hpp
  IGESDimen_ReadWriteModule.cxx
  IGESDimen_ReadWriteModule.hpp
  IGESDimen_Section.cxx
  IGESDimen_Section.hpp
  IGESDimen_SectionedArea.cxx
  IGESDimen_SectionedArea.hpp
  IGESDimen_SpecificModule.cxx
  IGESDimen_SpecificModule.hpp
  IGESDimen_ToolAngularDimension.cxx
  IGESDimen_ToolAngularDimension.hpp
  IGESDimen_ToolBasicDimension.cxx
  IGESDimen_ToolBasicDimension.hpp
  IGESDimen_ToolCenterLine.cxx
  IGESDimen_ToolCenterLine.hpp
  IGESDimen_ToolCurveDimension.cxx
  IGESDimen_ToolCurveDimension.hpp
  IGESDimen_ToolDiameterDimension.cxx
  IGESDimen_ToolDiameterDimension.hpp
  IGESDimen_ToolDimensionDisplayData.cxx
  IGESDimen_ToolDimensionDisplayData.hpp
  IGESDimen_ToolDimensionedGeometry.cxx
  IGESDimen_ToolDimensionedGeometry.hpp
  IGESDimen_ToolDimensionTolerance.cxx
  IGESDimen_ToolDimensionTolerance.hpp
  IGESDimen_ToolDimensionUnits.cxx
  IGESDimen_ToolDimensionUnits.hpp
  IGESDimen_ToolFlagNote.cxx
  IGESDimen_ToolFlagNote.hpp
  IGESDimen_ToolGeneralLabel.cxx
  IGESDimen_ToolGeneralLabel.hpp
  IGESDimen_ToolGeneralNote.cxx
  IGESDimen_ToolGeneralNote.hpp
  IGESDimen_ToolGeneralSymbol.cxx
  IGESDimen_ToolGeneralSymbol.hpp
  IGESDimen_ToolLeaderArrow.cxx
  IGESDimen_ToolLeaderArrow.hpp
  IGESDimen_ToolLinearDimension.cxx
  IGESDimen_ToolLinearDimension.hpp
  IGESDimen_ToolNewDimensionedGeometry.cxx
  IGESDimen_ToolNewDimensionedGeometry.hpp
  IGESDimen_ToolNewGeneralNote.cxx
  IGESDimen_ToolNewGeneralNote.hpp
  IGESDimen_ToolOrdinateDimension.cxx
  IGESDimen_ToolOrdinateDimension.hpp
  IGESDimen_ToolPointDimension.cxx
  IGESDimen_ToolPointDimension.hpp
  IGESDimen_ToolRadiusDimension.cxx
  IGESDimen_ToolRadiusDimension.hpp
  IGESDimen_ToolSection.cxx
  IGESDimen_ToolSection.hpp
  IGESDimen_ToolSectionedArea.cxx
  IGESDimen_ToolSectionedArea.hpp
  IGESDimen_ToolWitnessLine.cxx
  IGESDimen_ToolWitnessLine.hpp
  IGESDimen_WitnessLine.cxx
  IGESDimen_WitnessLine.hpp
)
