# Source files for IGESSelect package
set(OCCT_IGESSelect_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_IGESSelect_FILES
  IGESSelect.cxx
  IGESSelect.hpp
  IGESSelect_Activator.cxx
  IGESSelect_Activator.hpp
  IGESSelect_AddFileComment.cxx
  IGESSelect_AddFileComment.hpp
  IGESSelect_AddGroup.cxx
  IGESSelect_AddGroup.hpp
  IGESSelect_AutoCorrect.cxx
  IGESSelect_AutoCorrect.hpp
  IGESSelect_ChangeLevelList.cxx
  IGESSelect_ChangeLevelList.hpp
  IGESSelect_ChangeLevelNumber.cxx
  IGESSelect_ChangeLevelNumber.hpp
  IGESSelect_ComputeStatus.cxx
  IGESSelect_ComputeStatus.hpp
  IGESSelect_CounterOfLevelNumber.cxx
  IGESSelect_CounterOfLevelNumber.hpp
  IGESSelect_DispPerDrawing.cxx
  IGESSelect_DispPerDrawing.hpp
  IGESSelect_DispPerSingleView.cxx
  IGESSelect_DispPerSingleView.hpp
  IGESSelect_Dumper.cxx
  IGESSelect_Dumper.hpp
  IGESSelect_EditDirPart.cxx
  IGESSelect_EditDirPart.hpp
  IGESSelect_EditHeader.cxx
  IGESSelect_EditHeader.hpp
  IGESSelect_FileModifier.hpp
  IGESSelect_FileModifier_0.cxx
  IGESSelect_FloatFormat.cxx
  IGESSelect_FloatFormat.hpp
  IGESSelect_IGESName.cxx
  IGESSelect_IGESName.hpp
  IGESSelect_IGESTypeForm.cxx
  IGESSelect_IGESTypeForm.hpp
  IGESSelect_ModelModifier.hpp
  IGESSelect_ModelModifier_0.cxx
  IGESSelect_RebuildDrawings.cxx
  IGESSelect_RebuildDrawings.hpp
  IGESSelect_RebuildGroups.cxx
  IGESSelect_RebuildGroups.hpp
  IGESSelect_RemoveCurves.cxx
  IGESSelect_RemoveCurves.hpp
  IGESSelect_SelectBasicGeom.cxx
  IGESSelect_SelectBasicGeom.hpp
  IGESSelect_SelectBypassGroup.cxx
  IGESSelect_SelectBypassGroup.hpp
  IGESSelect_SelectBypassSubfigure.cxx
  IGESSelect_SelectBypassSubfigure.hpp
  IGESSelect_SelectDrawingFrom.cxx
  IGESSelect_SelectDrawingFrom.hpp
  IGESSelect_SelectFaces.cxx
  IGESSelect_SelectFaces.hpp
  IGESSelect_SelectFromDrawing.cxx
  IGESSelect_SelectFromDrawing.hpp
  IGESSelect_SelectFromSingleView.cxx
  IGESSelect_SelectFromSingleView.hpp
  IGESSelect_SelectLevelNumber.cxx
  IGESSelect_SelectLevelNumber.hpp
  IGESSelect_SelectName.cxx
  IGESSelect_SelectName.hpp
  IGESSelect_SelectPCurves.cxx
  IGESSelect_SelectPCurves.hpp
  IGESSelect_SelectSingleViewFrom.cxx
  IGESSelect_SelectSingleViewFrom.hpp
  IGESSelect_SelectSubordinate.cxx
  IGESSelect_SelectSubordinate.hpp
  IGESSelect_SelectVisibleStatus.cxx
  IGESSelect_SelectVisibleStatus.hpp
  IGESSelect_SetGlobalParameter.cxx
  IGESSelect_SetGlobalParameter.hpp
  IGESSelect_SetLabel.cxx
  IGESSelect_SetLabel.hpp
  IGESSelect_SetVersion5.cxx
  IGESSelect_SetVersion5.hpp
  IGESSelect_SignColor.cxx
  IGESSelect_SignColor.hpp
  IGESSelect_SignLevelNumber.cxx
  IGESSelect_SignLevelNumber.hpp
  IGESSelect_SignStatus.cxx
  IGESSelect_SignStatus.hpp
  IGESSelect_SplineToBSpline.cxx
  IGESSelect_SplineToBSpline.hpp
  IGESSelect_UpdateCreationDate.cxx
  IGESSelect_UpdateCreationDate.hpp
  IGESSelect_UpdateFileName.cxx
  IGESSelect_UpdateFileName.hpp
  IGESSelect_UpdateLastChange.cxx
  IGESSelect_UpdateLastChange.hpp
  IGESSelect_ViewSorter.cxx
  IGESSelect_ViewSorter.hpp
  IGESSelect_WorkLibrary.cxx
  IGESSelect_WorkLibrary.hpp
)
