# Source files for OSD package
set(OCCT_OSD_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_OSD_FILES
  OSD.cxx
  OSD.hpp
  OSD_CachedFileSystem.cxx
  OSD_CachedFileSystem.hpp
  OSD_Chronometer.cxx
  OSD_Chronometer.hpp
  OSD_Directory.cxx
  OSD_Directory.hpp
  OSD_DirectoryIterator.cxx
  OSD_DirectoryIterator.hpp
  OSD_Disk.cxx
  OSD_Disk.hpp
  OSD_Environment.cxx
  OSD_Environment.hpp
  OSD_Error.cxx
  OSD_Error.hpp
  OSD_ErrorList.hpp
  OSD_Exception.hpp
  OSD_Exception_ACCESS_VIOLATION.hpp
  OSD_Exception_ARRAY_BOUNDS_EXCEEDED.hpp
  OSD_Exception_CTRL_BREAK.hpp
  OSD_Exception_ILLEGAL_INSTRUCTION.hpp
  OSD_Exception_IN_PAGE_ERROR.hpp
  OSD_Exception_INT_OVERFLOW.hpp
  OSD_Exception_INVALID_DISPOSITION.hpp
  OSD_Exception_NONCONTINUABLE_EXCEPTION.hpp
  OSD_Exception_PRIV_INSTRUCTION.hpp
  OSD_Exception_STACK_OVERFLOW.hpp
  OSD_Exception_STATUS_NO_MEMORY.hpp
  OSD_File.cxx
  OSD_File.hpp
  OSD_FileIterator.cxx
  OSD_FileIterator.hpp
  OSD_FileNode.cxx
  OSD_FileNode.hpp
  OSD_FileSystem.cxx
  OSD_FileSystem.hpp
  OSD_FileSystemSelector.cxx
  OSD_FileSystemSelector.hpp
  OSD_Function.hpp
  OSD_Host.cxx
  OSD_Host.hpp
  OSD_LoadMode.hpp
  OSD_LocalFileSystem.cxx
  OSD_LocalFileSystem.hpp
  OSD_MemInfo.cxx
  OSD_MemInfo.hpp
  OSD_OpenFile.cxx
  OSD_OpenFile.hpp
  OSD_OpenMode.hpp
  OSD_OSDError.hpp
  OSD_Parallel.cxx
  OSD_Parallel.hpp
  OSD_Parallel_TBB.cxx
  OSD_Parallel_Threads.cxx
  OSD_Path.cxx
  OSD_Path.hpp
  OSD_PerfMeter.cxx
  OSD_PerfMeter.hpp
  OSD_Process.cxx
  OSD_Process.hpp
  OSD_Protection.cxx
  OSD_Protection.hpp
  OSD_SharedLibrary.cxx
  OSD_SharedLibrary.hpp
  OSD_SIGBUS.hpp
  OSD_SIGHUP.hpp
  OSD_SIGILL.hpp
  OSD_SIGINT.hpp
  OSD_SIGKILL.hpp
  OSD_signal.cxx
  OSD_Signal.hpp
  OSD_SIGQUIT.hpp
  OSD_SIGSEGV.hpp
  OSD_SIGSYS.hpp
  OSD_SingleProtection.hpp
  OSD_StreamBuffer.hpp
  OSD_SysType.hpp
  OSD_Thread.cxx
  OSD_Thread.hpp
  OSD_ThreadPool.cxx
  OSD_ThreadPool.hpp
  OSD_Timer.cxx
  OSD_Timer.hpp
  OSD_WhoAmI.hpp
  OSD_WNT.cxx
  OSD_WNT.hpp
)
