# Source files for StepFEA package
set(OCCT_StepFEA_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_StepFEA_FILES
  StepFEA_AlignedCurve3dElementCoordinateSystem.cxx
  StepFEA_AlignedCurve3dElementCoordinateSystem.hpp
  StepFEA_AlignedSurface3dElementCoordinateSystem.cxx
  StepFEA_AlignedSurface3dElementCoordinateSystem.hpp
  StepFEA_ArbitraryVolume3dElementCoordinateSystem.cxx
  StepFEA_ArbitraryVolume3dElementCoordinateSystem.hpp

  StepFEA_ConstantSurface3dElementCoordinateSystem.cxx
  StepFEA_ConstantSurface3dElementCoordinateSystem.hpp
  StepFEA_Curve3dElementProperty.cxx
  StepFEA_Curve3dElementProperty.hpp
  StepFEA_Curve3dElementRepresentation.cxx
  StepFEA_Curve3dElementRepresentation.hpp
  
  StepFEA_CurveElementEndCoordinateSystem.cxx
  StepFEA_CurveElementEndCoordinateSystem.hpp
  StepFEA_CurveElementEndOffset.cxx
  StepFEA_CurveElementEndOffset.hpp
  StepFEA_CurveElementEndRelease.cxx
  StepFEA_CurveElementEndRelease.hpp
  StepFEA_CurveElementInterval.cxx
  StepFEA_CurveElementInterval.hpp
  StepFEA_CurveElementIntervalConstant.cxx
  StepFEA_CurveElementIntervalConstant.hpp
  StepFEA_CurveElementIntervalLinearlyVarying.cxx
  StepFEA_CurveElementIntervalLinearlyVarying.hpp
  StepFEA_CurveElementLocation.cxx
  StepFEA_CurveElementLocation.hpp
  StepFEA_DegreeOfFreedom.cxx
  StepFEA_DegreeOfFreedom.hpp
  StepFEA_DegreeOfFreedomMember.cxx
  StepFEA_DegreeOfFreedomMember.hpp
  StepFEA_DummyNode.cxx
  StepFEA_DummyNode.hpp
  StepFEA_ElementGeometricRelationship.cxx
  StepFEA_ElementGeometricRelationship.hpp
  StepFEA_ElementGroup.cxx
  StepFEA_ElementGroup.hpp
  StepFEA_ElementOrElementGroup.cxx
  StepFEA_ElementOrElementGroup.hpp
  StepFEA_ElementRepresentation.cxx
  StepFEA_ElementRepresentation.hpp
  
  StepFEA_FeaAreaDensity.cxx
  StepFEA_FeaAreaDensity.hpp
  StepFEA_FeaAxis2Placement3d.cxx
  StepFEA_FeaAxis2Placement3d.hpp
  StepFEA_FeaCurveSectionGeometricRelationship.cxx
  StepFEA_FeaCurveSectionGeometricRelationship.hpp
  StepFEA_FeaGroup.cxx
  StepFEA_FeaGroup.hpp
  StepFEA_FeaLinearElasticity.cxx
  StepFEA_FeaLinearElasticity.hpp
  StepFEA_FeaMassDensity.cxx
  StepFEA_FeaMassDensity.hpp
  StepFEA_FeaMaterialPropertyRepresentation.cxx
  StepFEA_FeaMaterialPropertyRepresentation.hpp
  StepFEA_FeaMaterialPropertyRepresentationItem.cxx
  StepFEA_FeaMaterialPropertyRepresentationItem.hpp
  StepFEA_FeaModel.cxx
  StepFEA_FeaModel.hpp
  StepFEA_FeaModel3d.cxx
  StepFEA_FeaModel3d.hpp
  StepFEA_FeaModelDefinition.cxx
  StepFEA_FeaModelDefinition.hpp
  StepFEA_FeaMoistureAbsorption.cxx
  StepFEA_FeaMoistureAbsorption.hpp
  StepFEA_FeaParametricPoint.cxx
  StepFEA_FeaParametricPoint.hpp
  StepFEA_FeaRepresentationItem.cxx
  StepFEA_FeaRepresentationItem.hpp
  StepFEA_FeaSecantCoefficientOfLinearThermalExpansion.cxx
  StepFEA_FeaSecantCoefficientOfLinearThermalExpansion.hpp
  StepFEA_FeaShellBendingStiffness.cxx
  StepFEA_FeaShellBendingStiffness.hpp
  StepFEA_FeaShellMembraneBendingCouplingStiffness.cxx
  StepFEA_FeaShellMembraneBendingCouplingStiffness.hpp
  StepFEA_FeaShellMembraneStiffness.cxx
  StepFEA_FeaShellMembraneStiffness.hpp
  StepFEA_FeaShellShearStiffness.cxx
  StepFEA_FeaShellShearStiffness.hpp
  StepFEA_FeaSurfaceSectionGeometricRelationship.cxx
  StepFEA_FeaSurfaceSectionGeometricRelationship.hpp
  StepFEA_FeaTangentialCoefficientOfLinearThermalExpansion.cxx
  StepFEA_FeaTangentialCoefficientOfLinearThermalExpansion.hpp
  StepFEA_FreedomAndCoefficient.cxx
  StepFEA_FreedomAndCoefficient.hpp
  StepFEA_FreedomsList.cxx
  StepFEA_FreedomsList.hpp
  StepFEA_GeometricNode.cxx
  StepFEA_GeometricNode.hpp

  StepFEA_Node.cxx
  StepFEA_Node.hpp
  StepFEA_NodeDefinition.cxx
  StepFEA_NodeDefinition.hpp
  StepFEA_NodeGroup.cxx
  StepFEA_NodeGroup.hpp
  StepFEA_NodeRepresentation.cxx
  StepFEA_NodeRepresentation.hpp
  StepFEA_NodeSet.cxx
  StepFEA_NodeSet.hpp
  StepFEA_NodeWithSolutionCoordinateSystem.cxx
  StepFEA_NodeWithSolutionCoordinateSystem.hpp
  StepFEA_NodeWithVector.cxx
  StepFEA_NodeWithVector.hpp
  StepFEA_ParametricCurve3dElementCoordinateDirection.cxx
  StepFEA_ParametricCurve3dElementCoordinateDirection.hpp
  StepFEA_ParametricCurve3dElementCoordinateSystem.cxx
  StepFEA_ParametricCurve3dElementCoordinateSystem.hpp
  StepFEA_ParametricSurface3dElementCoordinateSystem.cxx
  StepFEA_ParametricSurface3dElementCoordinateSystem.hpp

  StepFEA_Surface3dElementRepresentation.cxx
  StepFEA_Surface3dElementRepresentation.hpp
  StepFEA_SymmetricTensor22d.cxx
  StepFEA_SymmetricTensor22d.hpp
  StepFEA_SymmetricTensor23d.cxx
  StepFEA_SymmetricTensor23d.hpp
  StepFEA_SymmetricTensor23dMember.cxx
  StepFEA_SymmetricTensor23dMember.hpp
  StepFEA_SymmetricTensor42d.cxx
  StepFEA_SymmetricTensor42d.hpp
  StepFEA_SymmetricTensor43d.cxx
  StepFEA_SymmetricTensor43d.hpp
  StepFEA_SymmetricTensor43dMember.cxx
  StepFEA_SymmetricTensor43dMember.hpp
  
  StepFEA_Volume3dElementRepresentation.cxx
  StepFEA_Volume3dElementRepresentation.hpp
)
