# Source files for XCAFDoc package
set(OCCT_XCAFDoc_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_XCAFDoc_FILES
  FILES
  GUID.txt
  XCAFDoc.cxx
  XCAFDoc.hpp
  XCAFDoc_AssemblyItemId.cxx
  XCAFDoc_AssemblyItemId.hpp
  XCAFDoc_AssemblyItemRef.cxx
  XCAFDoc_AssemblyItemRef.hpp
  XCAFDoc_AssemblyIterator.hpp
  XCAFDoc_AssemblyIterator.cxx
  XCAFDoc_AssemblyGraph.hpp
  XCAFDoc_AssemblyGraph.cxx
  XCAFDoc_AssemblyTool.hpp
  XCAFDoc_PartId.hpp
  XCAFDoc_Area.cxx
  XCAFDoc_Area.hpp
  XCAFDoc_Centroid.cxx
  XCAFDoc_Centroid.hpp
  XCAFDoc_ClippingPlaneTool.cxx
  XCAFDoc_ClippingPlaneTool.hpp
  XCAFDoc_Color.cxx
  XCAFDoc_Color.hpp
  XCAFDoc_ColorTool.cxx
  XCAFDoc_ColorTool.hpp
  XCAFDoc_ColorType.hpp

  XCAFDoc_Datum.cxx
  XCAFDoc_Datum.hpp
  XCAFDoc_Dimension.cxx
  XCAFDoc_Dimension.hpp
  XCAFDoc_GeomTolerance.cxx
  XCAFDoc_GeomTolerance.hpp
  XCAFDoc_DimTol.cxx
  XCAFDoc_DimTol.hpp
  XCAFDoc_DimTolTool.cxx
  XCAFDoc_DimTolTool.hpp
  XCAFDoc_DocumentTool.cxx
  XCAFDoc_DocumentTool.hpp
  XCAFDoc_Editor.cxx
  XCAFDoc_Editor.hpp
  XCAFDoc_GraphNode.cxx
  XCAFDoc_GraphNode.hpp
  XCAFDoc_LayerTool.cxx
  XCAFDoc_LayerTool.hpp
  XCAFDoc_LengthUnit.cxx
  XCAFDoc_LengthUnit.hpp
  XCAFDoc_Location.cxx
  XCAFDoc_Location.hpp
  XCAFDoc_Material.cxx
  XCAFDoc_Material.hpp
  XCAFDoc_MaterialTool.cxx
  XCAFDoc_MaterialTool.hpp
  XCAFDoc_Note.cxx
  XCAFDoc_Note.hpp
  XCAFDoc_NoteBalloon.cxx
  XCAFDoc_NoteBalloon.hpp
  XCAFDoc_NoteComment.cxx
  XCAFDoc_NoteComment.hpp
  XCAFDoc_NoteBinData.cxx
  XCAFDoc_NoteBinData.hpp
  XCAFDoc_NotesTool.cxx
  XCAFDoc_NotesTool.hpp
  XCAFDoc_ShapeMapTool.cxx
  XCAFDoc_ShapeMapTool.hpp
  XCAFDoc_ShapeTool.cxx
  XCAFDoc_ShapeTool.hpp
  XCAFDoc_View.cxx
  XCAFDoc_View.hpp
  XCAFDoc_ViewTool.cxx
  XCAFDoc_ViewTool.hpp
  XCAFDoc_VisMaterial.cxx
  XCAFDoc_VisMaterial.hpp
  XCAFDoc_VisMaterialCommon.hpp
  XCAFDoc_VisMaterialPBR.hpp
  XCAFDoc_VisMaterialTool.cxx
  XCAFDoc_VisMaterialTool.hpp
  XCAFDoc_Volume.cxx
  XCAFDoc_Volume.hpp
)
