#pragma once

#include <Standard_Type.hpp>

class Standard_Transient;
class Standard_Persistent;
class Standard_Type;

#define IMPLEMENT_DOWNCAST(C1, BC)
#define IMPLEMENT_STANDARD_HANDLE(C1, C2)
#define IMPLEMENT_STANDARD_PHANDLE(C1, C2)
#define IMPLEMENT_STANDARD_RTTI(C1)
#define IMPLEMENT_STANDARD_TYPE(C1)
#define IMPLEMENT_STANDARD_SUPERTYPE(Cn)
#define IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
#define IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
#define IMPLEMENT_STANDARD_TYPE_END(C1)
