# Source files for IGESSolid package
set(OCCT_IGESSolid_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_IGESSolid_FILES
  IGESSolid.cxx
  IGESSolid.hpp

  IGESSolid_Block.cxx
  IGESSolid_Block.hpp
  IGESSolid_BooleanTree.cxx
  IGESSolid_BooleanTree.hpp
  IGESSolid_ConeFrustum.cxx
  IGESSolid_ConeFrustum.hpp
  IGESSolid_ConicalSurface.cxx
  IGESSolid_ConicalSurface.hpp
  IGESSolid_Cylinder.cxx
  IGESSolid_Cylinder.hpp
  IGESSolid_CylindricalSurface.cxx
  IGESSolid_CylindricalSurface.hpp
  IGESSolid_EdgeList.cxx
  IGESSolid_EdgeList.hpp
  IGESSolid_Ellipsoid.cxx
  IGESSolid_Ellipsoid.hpp
  IGESSolid_Face.cxx
  IGESSolid_Face.hpp
  IGESSolid_GeneralModule.cxx
  IGESSolid_GeneralModule.hpp

  IGESSolid_Loop.cxx
  IGESSolid_Loop.hpp
  IGESSolid_ManifoldSolid.cxx
  IGESSolid_ManifoldSolid.hpp
  IGESSolid_PlaneSurface.cxx
  IGESSolid_PlaneSurface.hpp
  IGESSolid_Protocol.cxx
  IGESSolid_Protocol.hpp
  IGESSolid_ReadWriteModule.cxx
  IGESSolid_ReadWriteModule.hpp
  IGESSolid_RightAngularWedge.cxx
  IGESSolid_RightAngularWedge.hpp
  IGESSolid_SelectedComponent.cxx
  IGESSolid_SelectedComponent.hpp
  IGESSolid_Shell.cxx
  IGESSolid_Shell.hpp
  IGESSolid_SolidAssembly.cxx
  IGESSolid_SolidAssembly.hpp
  IGESSolid_SolidInstance.cxx
  IGESSolid_SolidInstance.hpp
  IGESSolid_SolidOfLinearExtrusion.cxx
  IGESSolid_SolidOfLinearExtrusion.hpp
  IGESSolid_SolidOfRevolution.cxx
  IGESSolid_SolidOfRevolution.hpp
  IGESSolid_SpecificModule.cxx
  IGESSolid_SpecificModule.hpp
  IGESSolid_Sphere.cxx
  IGESSolid_Sphere.hpp
  IGESSolid_SphericalSurface.cxx
  IGESSolid_SphericalSurface.hpp
  IGESSolid_ToolBlock.cxx
  IGESSolid_ToolBlock.hpp
  IGESSolid_ToolBooleanTree.cxx
  IGESSolid_ToolBooleanTree.hpp
  IGESSolid_ToolConeFrustum.cxx
  IGESSolid_ToolConeFrustum.hpp
  IGESSolid_ToolConicalSurface.cxx
  IGESSolid_ToolConicalSurface.hpp
  IGESSolid_ToolCylinder.cxx
  IGESSolid_ToolCylinder.hpp
  IGESSolid_ToolCylindricalSurface.cxx
  IGESSolid_ToolCylindricalSurface.hpp
  IGESSolid_ToolEdgeList.cxx
  IGESSolid_ToolEdgeList.hpp
  IGESSolid_ToolEllipsoid.cxx
  IGESSolid_ToolEllipsoid.hpp
  IGESSolid_ToolFace.cxx
  IGESSolid_ToolFace.hpp
  IGESSolid_ToolLoop.cxx
  IGESSolid_ToolLoop.hpp
  IGESSolid_ToolManifoldSolid.cxx
  IGESSolid_ToolManifoldSolid.hpp
  IGESSolid_ToolPlaneSurface.cxx
  IGESSolid_ToolPlaneSurface.hpp
  IGESSolid_ToolRightAngularWedge.cxx
  IGESSolid_ToolRightAngularWedge.hpp
  IGESSolid_ToolSelectedComponent.cxx
  IGESSolid_ToolSelectedComponent.hpp
  IGESSolid_ToolShell.cxx
  IGESSolid_ToolShell.hpp
  IGESSolid_ToolSolidAssembly.cxx
  IGESSolid_ToolSolidAssembly.hpp
  IGESSolid_ToolSolidInstance.cxx
  IGESSolid_ToolSolidInstance.hpp
  IGESSolid_ToolSolidOfLinearExtrusion.cxx
  IGESSolid_ToolSolidOfLinearExtrusion.hpp
  IGESSolid_ToolSolidOfRevolution.cxx
  IGESSolid_ToolSolidOfRevolution.hpp
  IGESSolid_ToolSphere.cxx
  IGESSolid_ToolSphere.hpp
  IGESSolid_ToolSphericalSurface.cxx
  IGESSolid_ToolSphericalSurface.hpp
  IGESSolid_ToolToroidalSurface.cxx
  IGESSolid_ToolToroidalSurface.hpp
  IGESSolid_ToolTorus.cxx
  IGESSolid_ToolTorus.hpp
  IGESSolid_ToolVertexList.cxx
  IGESSolid_ToolVertexList.hpp
  IGESSolid_TopoBuilder.cxx
  IGESSolid_TopoBuilder.hpp
  IGESSolid_ToroidalSurface.cxx
  IGESSolid_ToroidalSurface.hpp
  IGESSolid_Torus.cxx
  IGESSolid_Torus.hpp
  IGESSolid_VertexList.cxx
  IGESSolid_VertexList.hpp
)
