# Source files for NCollection package
set(OCCT_NCollection_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_NCollection_FILES
  NCollection_AccAllocator.cxx
  NCollection_AccAllocator.hpp
  NCollection_AliasedArray.hpp
  NCollection_AlignedAllocator.cxx
  NCollection_AlignedAllocator.hpp
  NCollection_Allocator.hpp
  NCollection_Array1.hpp
  NCollection_Array2.hpp
  NCollection_BaseAllocator.cxx
  NCollection_BaseAllocator.hpp
  NCollection_BaseList.cxx
  NCollection_BaseList.hpp
  NCollection_BaseMap.cxx
  NCollection_BaseMap.hpp
  NCollection_BasePointerVector.cxx
  NCollection_BasePointerVector.hpp
  NCollection_BaseSequence.cxx
  NCollection_BaseSequence.hpp
  NCollection_Buffer.hpp
  NCollection_CellFilter.hpp
  NCollection_DataMap.hpp
  NCollection_DefaultHasher.hpp
  NCollection_DefineAlloc.hpp
  NCollection_DoubleMap.hpp
  NCollection_Haft.h
  NCollection_Handle.hpp
  NCollection_HArray1.hpp
  NCollection_HArray2.hpp
  NCollection_HeapAllocator.cxx
  NCollection_HeapAllocator.hpp
  NCollection_HSequence.hpp
  NCollection_IncAllocator.cxx
  NCollection_IncAllocator.hpp
  NCollection_IndexedDataMap.hpp
  NCollection_IndexedIterator.hpp
  NCollection_IndexedMap.hpp
  NCollection_Iterator.hpp
  NCollection_Lerp.hpp
  NCollection_List.hpp
  NCollection_ListNode.hpp
  NCollection_LocalArray.hpp
  NCollection_Map.hpp
  NCollection_MapAlgo.hpp
  NCollection_Mat4.hpp
  NCollection_OccAllocator.hpp
  NCollection_Primes.cxx
  NCollection_Primes.hpp
  NCollection_Sequence.hpp
  NCollection_Shared.hpp
  NCollection_SparseArray.hpp
  NCollection_SparseArrayBase.cxx
  NCollection_SparseArrayBase.hpp
  NCollection_StlIterator.hpp
  NCollection_String.hpp
  NCollection_TListNode.hpp
  NCollection_UBTree.hpp
  NCollection_UBTreeFiller.hpp
  NCollection_UtfIterator.hpp
  NCollection_UtfString.hpp
  NCollection_UtfString.cxx
  NCollection_Vec2.hpp
  NCollection_Vec3.hpp
  NCollection_Vec4.hpp
  NCollection_Vector.hpp
  NCollection_WinHeapAllocator.cxx
  NCollection_WinHeapAllocator.hpp
)
