# Source files for StepData package
set(OCCT_StepData_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_StepData_FILES
  StepData.cxx
  StepData.hpp

  StepData_DefaultGeneral.cxx
  StepData_DefaultGeneral.hpp
  StepData_Described.cxx
  StepData_Described.hpp
  StepData_ECDescr.cxx
  StepData_ECDescr.hpp
  StepData_EDescr.cxx
  StepData_EDescr.hpp
  StepData_EnumTool.cxx
  StepData_EnumTool.hpp
  StepData_ESDescr.cxx
  StepData_ESDescr.hpp
  StepData_Factors.cxx
  StepData_Factors.hpp
  StepData_Field.cxx
  StepData_Field.hpp
  StepData_FieldList.cxx
  StepData_FieldList.hpp
  StepData_FieldList1.cxx
  StepData_FieldList1.hpp
  StepData_FieldListD.cxx
  StepData_FieldListD.hpp
  StepData_FieldListN.cxx
  StepData_FieldListN.hpp
  StepData_FileProtocol.cxx
  StepData_FileProtocol.hpp
  StepData_FileRecognizer.hpp
  StepData_FileRecognizer_0.cxx
  StepData_FreeFormEntity.cxx
  StepData_FreeFormEntity.hpp
  StepData_GeneralModule.cxx
  StepData_GeneralModule.hpp
  StepData_GlobalNodeOfWriterLib.hpp
  StepData_GlobalNodeOfWriterLib_0.cxx

  StepData_Logical.hpp
  StepData_NodeOfWriterLib.hpp
  StepData_NodeOfWriterLib_0.cxx
  StepData_PDescr.cxx
  StepData_PDescr.hpp
  StepData_Plex.cxx
  StepData_Plex.hpp
  StepData_Protocol.cxx
  StepData_Protocol.hpp
  StepData_ReadWriteModule.cxx
  StepData_ReadWriteModule.hpp
  StepData_SelectArrReal.cxx
  StepData_SelectArrReal.hpp
  StepData_SelectInt.cxx
  StepData_SelectInt.hpp
  StepData_SelectMember.cxx
  StepData_SelectMember.hpp
  StepData_SelectNamed.cxx
  StepData_SelectNamed.hpp
  StepData_SelectReal.cxx
  StepData_SelectReal.hpp
  StepData_SelectType.cxx
  StepData_SelectType.hpp
  StepData_Simple.cxx
  StepData_Simple.hpp
  StepData_StepDumper.cxx
  StepData_StepDumper.hpp
  StepData_StepModel.cxx
  StepData_StepModel.hpp
  StepData_StepReaderData.cxx
  StepData_StepReaderData.hpp
  StepData_StepReaderTool.cxx
  StepData_StepReaderTool.hpp
  StepData_StepWriter.cxx
  StepData_StepWriter.hpp
  StepData_UndefinedEntity.cxx
  StepData_UndefinedEntity.hpp
  StepData_WriterLib.hpp
  StepData_WriterLib_0.cxx
)
