#pragma once


//! Defines types of geom tolerance
enum XCAFDimTolObjects_GeomToleranceType
{
  XCAFDimTolObjects_GeomToleranceType_None,
  XCAFDimTolObjects_GeomToleranceType_Angularity,
  XCAFDimTolObjects_GeomToleranceType_CircularRunout,
  XCAFDimTolObjects_GeomToleranceType_CircularityOrRoundness,
  XCAFDimTolObjects_GeomToleranceType_Coaxiality,
  XCAFDimTolObjects_GeomToleranceType_Concentricity,
  XCAFDimTolObjects_GeomToleranceType_Cylindricity,
  XCAFDimTolObjects_GeomToleranceType_Flatness,
  XCAFDimTolObjects_GeomToleranceType_Parallelism,
  XCAFDimTolObjects_GeomToleranceType_Perpendicularity,
  XCAFDimTolObjects_GeomToleranceType_Position,
  XCAFDimTolObjects_GeomToleranceType_ProfileOfLine,
  XCAFDimTolObjects_GeomToleranceType_ProfileOfSurface,
  XCAFDimTolObjects_GeomToleranceType_Straightness,
  XCAFDimTolObjects_GeomToleranceType_Symmetry,
  XCAFDimTolObjects_GeomToleranceType_TotalRunout
};

