#pragma once

enum XCAFDimTolObjects_GeomToleranceTypeValue
{
  XCAFDimTolObjects_GeomToleranceTypeValue_None,
  XCAFDimTolObjects_GeomToleranceTypeValue_Diameter,
  XCAFDimTolObjects_GeomToleranceTypeValue_SphericalDiameter
};
