# Source files for StepGeom package
set(OCCT_StepGeom_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_StepGeom_FILES

  StepGeom_Axis1Placement.cxx
  StepGeom_Axis1Placement.hpp
  StepGeom_Axis2Placement.cxx
  StepGeom_Axis2Placement.hpp
  StepGeom_Axis2Placement2d.cxx
  StepGeom_Axis2Placement2d.hpp
  StepGeom_Axis2Placement3d.cxx
  StepGeom_Axis2Placement3d.hpp
  StepGeom_BezierCurve.cxx
  StepGeom_BezierCurve.hpp
  StepGeom_BezierCurveAndRationalBSplineCurve.cxx
  StepGeom_BezierCurveAndRationalBSplineCurve.hpp
  StepGeom_BezierSurface.cxx
  StepGeom_BezierSurface.hpp
  StepGeom_BezierSurfaceAndRationalBSplineSurface.cxx
  StepGeom_BezierSurfaceAndRationalBSplineSurface.hpp
  StepGeom_BoundaryCurve.cxx
  StepGeom_BoundaryCurve.hpp
  StepGeom_BoundedCurve.cxx
  StepGeom_BoundedCurve.hpp
  StepGeom_BoundedSurface.cxx
  StepGeom_BoundedSurface.hpp
  StepGeom_BSplineCurve.cxx
  StepGeom_BSplineCurve.hpp
  StepGeom_BSplineCurveForm.hpp
  StepGeom_BSplineCurveWithKnots.cxx
  StepGeom_BSplineCurveWithKnots.hpp
  StepGeom_BSplineCurveWithKnotsAndRationalBSplineCurve.cxx
  StepGeom_BSplineCurveWithKnotsAndRationalBSplineCurve.hpp
  StepGeom_BSplineSurface.cxx
  StepGeom_BSplineSurface.hpp
  StepGeom_BSplineSurfaceForm.hpp
  StepGeom_BSplineSurfaceWithKnots.cxx
  StepGeom_BSplineSurfaceWithKnots.hpp
  StepGeom_BSplineSurfaceWithKnotsAndRationalBSplineSurface.cxx
  StepGeom_BSplineSurfaceWithKnotsAndRationalBSplineSurface.hpp
  StepGeom_CartesianPoint.cxx
  StepGeom_CartesianPoint.hpp
  StepGeom_CartesianTransformationOperator.cxx
  StepGeom_CartesianTransformationOperator.hpp
  StepGeom_CartesianTransformationOperator2d.cxx
  StepGeom_CartesianTransformationOperator2d.hpp
  StepGeom_CartesianTransformationOperator3d.cxx
  StepGeom_CartesianTransformationOperator3d.hpp
  StepGeom_Circle.cxx
  StepGeom_Circle.hpp
  StepGeom_CompositeCurve.cxx
  StepGeom_CompositeCurve.hpp
  StepGeom_CompositeCurveOnSurface.cxx
  StepGeom_CompositeCurveOnSurface.hpp
  StepGeom_CompositeCurveSegment.cxx
  StepGeom_CompositeCurveSegment.hpp
  StepGeom_Conic.cxx
  StepGeom_Conic.hpp
  StepGeom_ConicalSurface.cxx
  StepGeom_ConicalSurface.hpp
  StepGeom_Curve.cxx
  StepGeom_Curve.hpp
  StepGeom_CurveBoundedSurface.cxx
  StepGeom_CurveBoundedSurface.hpp
  StepGeom_CurveOnSurface.cxx
  StepGeom_CurveOnSurface.hpp
  StepGeom_CurveReplica.cxx
  StepGeom_CurveReplica.hpp
  StepGeom_CylindricalSurface.cxx
  StepGeom_CylindricalSurface.hpp
  StepGeom_DegeneratePcurve.cxx
  StepGeom_DegeneratePcurve.hpp
  StepGeom_DegenerateToroidalSurface.cxx
  StepGeom_DegenerateToroidalSurface.hpp
  StepGeom_Direction.cxx
  StepGeom_Direction.hpp
  StepGeom_ElementarySurface.cxx
  StepGeom_ElementarySurface.hpp
  StepGeom_Ellipse.cxx
  StepGeom_Ellipse.hpp
  StepGeom_EvaluatedDegeneratePcurve.cxx
  StepGeom_EvaluatedDegeneratePcurve.hpp
  StepGeom_GeometricRepresentationContext.cxx
  StepGeom_GeometricRepresentationContext.hpp
  StepGeom_GeometricRepresentationContextAndGlobalUnitAssignedContext.cxx
  StepGeom_GeometricRepresentationContextAndGlobalUnitAssignedContext.hpp
  StepGeom_GeometricRepresentationContextAndParametricRepresentationContext.cxx
  StepGeom_GeometricRepresentationContextAndParametricRepresentationContext.hpp
  StepGeom_GeometricRepresentationItem.cxx
  StepGeom_GeometricRepresentationItem.hpp
  StepGeom_GeomRepContextAndGlobUnitAssCtxAndGlobUncertaintyAssCtx.cxx
  StepGeom_GeomRepContextAndGlobUnitAssCtxAndGlobUncertaintyAssCtx.hpp

  StepGeom_Hyperbola.cxx
  StepGeom_Hyperbola.hpp
  StepGeom_IntersectionCurve.cxx
  StepGeom_IntersectionCurve.hpp
  StepGeom_KnotType.hpp
  StepGeom_Line.cxx
  StepGeom_Line.hpp
  StepGeom_OffsetCurve3d.cxx
  StepGeom_OffsetCurve3d.hpp
  StepGeom_OffsetSurface.cxx
  StepGeom_OffsetSurface.hpp
  StepGeom_OrientedSurface.cxx
  StepGeom_OrientedSurface.hpp
  StepGeom_OuterBoundaryCurve.cxx
  StepGeom_OuterBoundaryCurve.hpp
  StepGeom_Parabola.cxx
  StepGeom_Parabola.hpp
  StepGeom_Pcurve.cxx
  StepGeom_Pcurve.hpp
  StepGeom_PcurveOrSurface.cxx
  StepGeom_PcurveOrSurface.hpp
  StepGeom_Placement.cxx
  StepGeom_Placement.hpp
  StepGeom_Plane.cxx
  StepGeom_Plane.hpp
  StepGeom_Point.cxx
  StepGeom_Point.hpp
  StepGeom_PointOnCurve.cxx
  StepGeom_PointOnCurve.hpp
  StepGeom_PointOnSurface.cxx
  StepGeom_PointOnSurface.hpp
  StepGeom_PointReplica.cxx
  StepGeom_PointReplica.hpp
  StepGeom_Polyline.cxx
  StepGeom_Polyline.hpp
  StepGeom_PreferredSurfaceCurveRepresentation.hpp
  StepGeom_QuasiUniformCurve.cxx
  StepGeom_QuasiUniformCurve.hpp
  StepGeom_QuasiUniformCurveAndRationalBSplineCurve.cxx
  StepGeom_QuasiUniformCurveAndRationalBSplineCurve.hpp
  StepGeom_QuasiUniformSurface.cxx
  StepGeom_QuasiUniformSurface.hpp
  StepGeom_QuasiUniformSurfaceAndRationalBSplineSurface.cxx
  StepGeom_QuasiUniformSurfaceAndRationalBSplineSurface.hpp
  StepGeom_RationalBSplineCurve.cxx
  StepGeom_RationalBSplineCurve.hpp
  StepGeom_RationalBSplineSurface.cxx
  StepGeom_RationalBSplineSurface.hpp
  StepGeom_RectangularCompositeSurface.cxx
  StepGeom_RectangularCompositeSurface.hpp
  StepGeom_RectangularTrimmedSurface.cxx
  StepGeom_RectangularTrimmedSurface.hpp
  StepGeom_ReparametrisedCompositeCurveSegment.cxx
  StepGeom_ReparametrisedCompositeCurveSegment.hpp
  StepGeom_SeamCurve.cxx
  StepGeom_SeamCurve.hpp
  StepGeom_SphericalSurface.cxx
  StepGeom_SphericalSurface.hpp
  StepGeom_SuParameters.cxx
  StepGeom_SuParameters.hpp
  StepGeom_Surface.cxx
  StepGeom_Surface.hpp
  StepGeom_SurfaceBoundary.cxx
  StepGeom_SurfaceBoundary.hpp
  StepGeom_SurfaceCurve.cxx
  StepGeom_SurfaceCurve.hpp
  StepGeom_SurfaceCurveAndBoundedCurve.cxx
  StepGeom_SurfaceCurveAndBoundedCurve.hpp
  StepGeom_SurfaceOfLinearExtrusion.cxx
  StepGeom_SurfaceOfLinearExtrusion.hpp
  StepGeom_SurfaceOfRevolution.cxx
  StepGeom_SurfaceOfRevolution.hpp
  StepGeom_SurfacePatch.cxx
  StepGeom_SurfacePatch.hpp
  StepGeom_SurfaceReplica.cxx
  StepGeom_SurfaceReplica.hpp
  StepGeom_SweptSurface.cxx
  StepGeom_SweptSurface.hpp
  StepGeom_ToroidalSurface.cxx
  StepGeom_ToroidalSurface.hpp
  StepGeom_TransitionCode.hpp
  StepGeom_TrimmedCurve.cxx
  StepGeom_TrimmedCurve.hpp
  StepGeom_TrimmingMember.cxx
  StepGeom_TrimmingMember.hpp
  StepGeom_TrimmingPreference.hpp
  StepGeom_TrimmingSelect.cxx
  StepGeom_TrimmingSelect.hpp
  StepGeom_UniformCurve.cxx
  StepGeom_UniformCurve.hpp
  StepGeom_UniformCurveAndRationalBSplineCurve.cxx
  StepGeom_UniformCurveAndRationalBSplineCurve.hpp
  StepGeom_UniformSurface.cxx
  StepGeom_UniformSurface.hpp
  StepGeom_UniformSurfaceAndRationalBSplineSurface.cxx
  StepGeom_UniformSurfaceAndRationalBSplineSurface.hpp
  StepGeom_Vector.cxx
  StepGeom_Vector.hpp
  StepGeom_VectorOrDirection.cxx
  StepGeom_VectorOrDirection.hpp
)
