# Source files for DsgPrs package
set(OCCT_DsgPrs_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_DsgPrs_FILES
  DsgPrs.cxx
  DsgPrs.hpp
  DsgPrs_AnglePresentation.cxx
  DsgPrs_AnglePresentation.hpp
  DsgPrs_ArrowSide.hpp
  DsgPrs_Chamf2dPresentation.cxx
  DsgPrs_Chamf2dPresentation.hpp
  DsgPrs_ConcentricPresentation.cxx
  DsgPrs_ConcentricPresentation.hpp
  DsgPrs_DatumPrs.cxx
  DsgPrs_DatumPrs.hpp
  DsgPrs_DiameterPresentation.cxx
  DsgPrs_DiameterPresentation.hpp
  DsgPrs_EllipseRadiusPresentation.cxx
  DsgPrs_EllipseRadiusPresentation.hpp
  DsgPrs_EqualDistancePresentation.cxx
  DsgPrs_EqualDistancePresentation.hpp
  DsgPrs_EqualRadiusPresentation.cxx
  DsgPrs_EqualRadiusPresentation.hpp
  DsgPrs_FilletRadiusPresentation.cxx
  DsgPrs_FilletRadiusPresentation.hpp
  DsgPrs_FixPresentation.cxx
  DsgPrs_FixPresentation.hpp
  DsgPrs_IdenticPresentation.cxx
  DsgPrs_IdenticPresentation.hpp
  DsgPrs_LengthPresentation.cxx
  DsgPrs_LengthPresentation.hpp
  DsgPrs_MidPointPresentation.cxx
  DsgPrs_MidPointPresentation.hpp
  DsgPrs_OffsetPresentation.cxx
  DsgPrs_OffsetPresentation.hpp
  DsgPrs_ParalPresentation.cxx
  DsgPrs_ParalPresentation.hpp
  DsgPrs_PerpenPresentation.cxx
  DsgPrs_PerpenPresentation.hpp
  DsgPrs_RadiusPresentation.cxx
  DsgPrs_RadiusPresentation.hpp
  DsgPrs_ShadedPlanePresentation.cxx
  DsgPrs_ShadedPlanePresentation.hpp
  DsgPrs_ShapeDirPresentation.cxx
  DsgPrs_ShapeDirPresentation.hpp
  DsgPrs_SymbPresentation.cxx
  DsgPrs_SymbPresentation.hpp
  DsgPrs_SymmetricPresentation.cxx
  DsgPrs_SymmetricPresentation.hpp
  DsgPrs_TangentPresentation.cxx
  DsgPrs_TangentPresentation.hpp
  DsgPrs_XYZAxisPresentation.cxx
  DsgPrs_XYZAxisPresentation.hpp
  DsgPrs_XYZPlanePresentation.cxx
  DsgPrs_XYZPlanePresentation.hpp
)
