

#include <StepKinematics_ProductDefinitionKinematics.hpp>

IMPLEMENT_STANDARD_RTTIEXT(StepKinematics_ProductDefinitionKinematics, StepRepr_PropertyDefinition)

StepKinematics_ProductDefinitionKinematics::StepKinematics_ProductDefinitionKinematics() = default;
