

#include <StepKinematics_KinematicTopologyStructure.hpp>

IMPLEMENT_STANDARD_RTTIEXT(StepKinematics_KinematicTopologyStructure, StepRepr_Representation)

StepKinematics_KinematicTopologyStructure::StepKinematics_KinematicTopologyStructure() = default;
