

#include <StepKinematics_HighOrderKinematicPair.hpp>

IMPLEMENT_STANDARD_RTTIEXT(StepKinematics_HighOrderKinematicPair, StepKinematics_KinematicPair)

StepKinematics_HighOrderKinematicPair::StepKinematics_HighOrderKinematicPair() = default;
