#pragma once

enum StdSelect_TypeOfSelectionImage
{
  StdSelect_TypeOfSelectionImage_NormalizedDepth = 0,
  StdSelect_TypeOfSelectionImage_NormalizedDepthInverted,
  StdSelect_TypeOfSelectionImage_UnnormalizedDepth,
  StdSelect_TypeOfSelectionImage_ColoredDetectedObject,
  StdSelect_TypeOfSelectionImage_ColoredEntity,
  StdSelect_TypeOfSelectionImage_ColoredEntityType,
  StdSelect_TypeOfSelectionImage_ColoredOwner,
  StdSelect_TypeOfSelectionImage_ColoredSelectionMode,
  StdSelect_TypeOfSelectionImage_SurfaceNormal
};
