# Source files for IGESAppli package
set(OCCT_IGESAppli_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_IGESAppli_FILES
  IGESAppli.cxx
  IGESAppli.hpp

  IGESAppli_DrilledHole.cxx
  IGESAppli_DrilledHole.hpp
  IGESAppli_ElementResults.cxx
  IGESAppli_ElementResults.hpp
  IGESAppli_FiniteElement.cxx
  IGESAppli_FiniteElement.hpp
  IGESAppli_Flow.cxx
  IGESAppli_Flow.hpp
  IGESAppli_FlowLineSpec.cxx
  IGESAppli_FlowLineSpec.hpp
  IGESAppli_GeneralModule.cxx
  IGESAppli_GeneralModule.hpp

  IGESAppli_LevelFunction.cxx
  IGESAppli_LevelFunction.hpp
  IGESAppli_LevelToPWBLayerMap.cxx
  IGESAppli_LevelToPWBLayerMap.hpp
  IGESAppli_LineWidening.cxx
  IGESAppli_LineWidening.hpp
  IGESAppli_NodalConstraint.cxx
  IGESAppli_NodalConstraint.hpp
  IGESAppli_NodalDisplAndRot.cxx
  IGESAppli_NodalDisplAndRot.hpp
  IGESAppli_NodalResults.cxx
  IGESAppli_NodalResults.hpp
  IGESAppli_Node.cxx
  IGESAppli_Node.hpp
  IGESAppli_PartNumber.cxx
  IGESAppli_PartNumber.hpp
  IGESAppli_PinNumber.cxx
  IGESAppli_PinNumber.hpp
  IGESAppli_PipingFlow.cxx
  IGESAppli_PipingFlow.hpp
  IGESAppli_Protocol.cxx
  IGESAppli_Protocol.hpp
  IGESAppli_PWBArtworkStackup.cxx
  IGESAppli_PWBArtworkStackup.hpp
  IGESAppli_PWBDrilledHole.cxx
  IGESAppli_PWBDrilledHole.hpp
  IGESAppli_ReadWriteModule.cxx
  IGESAppli_ReadWriteModule.hpp
  IGESAppli_ReferenceDesignator.cxx
  IGESAppli_ReferenceDesignator.hpp
  IGESAppli_RegionRestriction.cxx
  IGESAppli_RegionRestriction.hpp
  IGESAppli_SpecificModule.cxx
  IGESAppli_SpecificModule.hpp
  IGESAppli_ToolDrilledHole.cxx
  IGESAppli_ToolDrilledHole.hpp
  IGESAppli_ToolElementResults.cxx
  IGESAppli_ToolElementResults.hpp
  IGESAppli_ToolFiniteElement.cxx
  IGESAppli_ToolFiniteElement.hpp
  IGESAppli_ToolFlow.cxx
  IGESAppli_ToolFlow.hpp
  IGESAppli_ToolFlowLineSpec.cxx
  IGESAppli_ToolFlowLineSpec.hpp
  IGESAppli_ToolLevelFunction.cxx
  IGESAppli_ToolLevelFunction.hpp
  IGESAppli_ToolLevelToPWBLayerMap.cxx
  IGESAppli_ToolLevelToPWBLayerMap.hpp
  IGESAppli_ToolLineWidening.cxx
  IGESAppli_ToolLineWidening.hpp
  IGESAppli_ToolNodalConstraint.cxx
  IGESAppli_ToolNodalConstraint.hpp
  IGESAppli_ToolNodalDisplAndRot.cxx
  IGESAppli_ToolNodalDisplAndRot.hpp
  IGESAppli_ToolNodalResults.cxx
  IGESAppli_ToolNodalResults.hpp
  IGESAppli_ToolNode.cxx
  IGESAppli_ToolNode.hpp
  IGESAppli_ToolPartNumber.cxx
  IGESAppli_ToolPartNumber.hpp
  IGESAppli_ToolPinNumber.cxx
  IGESAppli_ToolPinNumber.hpp
  IGESAppli_ToolPipingFlow.cxx
  IGESAppli_ToolPipingFlow.hpp
  IGESAppli_ToolPWBArtworkStackup.cxx
  IGESAppli_ToolPWBArtworkStackup.hpp
  IGESAppli_ToolPWBDrilledHole.cxx
  IGESAppli_ToolPWBDrilledHole.hpp
  IGESAppli_ToolReferenceDesignator.cxx
  IGESAppli_ToolReferenceDesignator.hpp
  IGESAppli_ToolRegionRestriction.cxx
  IGESAppli_ToolRegionRestriction.hpp
)
