#include <StepRepr_CompShAspAndDatumFeatAndShAsp.hpp>

IMPLEMENT_STANDARD_RTTIEXT(StepRepr_CompShAspAndDatumFeatAndShAsp, StepRepr_ShapeAspect)

StepRepr_CompShAspAndDatumFeatAndShAsp::StepRepr_CompShAspAndDatumFeatAndShAsp() = default;
