#include <StepRepr_NextAssemblyUsageOccurrence.hpp>

IMPLEMENT_STANDARD_RTTIEXT(StepRepr_NextAssemblyUsageOccurrence, StepRepr_AssemblyComponentUsage)

StepRepr_NextAssemblyUsageOccurrence::StepRepr_NextAssemblyUsageOccurrence() = default;
