#include <StepRepr_CompositeGroupShapeAspect.hpp>

IMPLEMENT_STANDARD_RTTIEXT(StepRepr_CompositeGroupShapeAspect, StepRepr_CompositeShapeAspect)

StepRepr_CompositeGroupShapeAspect::StepRepr_CompositeGroupShapeAspect() = default;
