# Source files for Vrml package
set(OCCT_Vrml_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_Vrml_FILES
  Vrml.cxx
  Vrml.hpp
  Vrml_AsciiText.cxx
  Vrml_AsciiText.hpp
  Vrml_Cone.cxx
  Vrml_Cone.hpp

  Vrml_Coordinate3.cxx
  Vrml_Coordinate3.hpp
  Vrml_Cube.cxx
  Vrml_Cube.hpp
  Vrml_Cylinder.cxx
  Vrml_Cylinder.hpp
  Vrml_DirectionalLight.cxx
  Vrml_DirectionalLight.hpp
  Vrml_FontStyle.cxx
  Vrml_FontStyle.hpp
  Vrml_Group.cxx
  Vrml_Group.hpp
  Vrml_IndexedFaceSet.cxx
  Vrml_IndexedFaceSet.hpp
  Vrml_IndexedLineSet.cxx
  Vrml_IndexedLineSet.hpp
  Vrml_Info.cxx
  Vrml_Info.hpp
  Vrml_Instancing.cxx
  Vrml_Instancing.hpp
  Vrml_LOD.cxx
  Vrml_LOD.hpp
  Vrml_Material.cxx
  Vrml_Material.hpp
  Vrml_MaterialBinding.cxx
  Vrml_MaterialBinding.hpp
  Vrml_MaterialBindingAndNormalBinding.hpp
  Vrml_MatrixTransform.cxx
  Vrml_MatrixTransform.hpp
  Vrml_Normal.cxx
  Vrml_Normal.hpp
  Vrml_NormalBinding.cxx
  Vrml_NormalBinding.hpp
  Vrml_OrthographicCamera.cxx
  Vrml_OrthographicCamera.hpp
  Vrml_PerspectiveCamera.cxx
  Vrml_PerspectiveCamera.hpp
  Vrml_PointLight.cxx
  Vrml_PointLight.hpp
  Vrml_PointSet.cxx
  Vrml_PointSet.hpp

  Vrml_Rotation.cxx
  Vrml_Rotation.hpp
  Vrml_Scale.cxx
  Vrml_Scale.hpp
  Vrml_Separator.cxx
  Vrml_Separator.hpp
  Vrml_SFImage.cxx
  Vrml_SFImage.hpp
  Vrml_SFRotation.cxx
  Vrml_SFRotation.hpp
  Vrml_ShapeHints.cxx
  Vrml_ShapeHints.hpp
  Vrml_Sphere.cxx
  Vrml_Sphere.hpp
  Vrml_SpotLight.cxx
  Vrml_SpotLight.hpp
  Vrml_Switch.cxx
  Vrml_Switch.hpp
  Vrml_Texture2.cxx
  Vrml_Texture2.hpp
  Vrml_Texture2Transform.cxx
  Vrml_Texture2Transform.hpp
  Vrml_TextureCoordinate2.cxx
  Vrml_TextureCoordinate2.hpp
  Vrml_Transform.cxx
  Vrml_Transform.hpp
  Vrml_TransformSeparator.cxx
  Vrml_TransformSeparator.hpp
  Vrml_Translation.cxx
  Vrml_Translation.hpp
  Vrml_WWWAnchor.cxx
  Vrml_WWWAnchor.hpp
  Vrml_WWWInline.cxx
  Vrml_WWWInline.hpp
)
