

#include <Vrml.hpp>

#include <Standard_Version.hxx>

Standard_OStream& Vrml::VrmlHeaderWriter(Standard_OStream& anOStream)
{
  anOStream << "#VRML V1.0 ascii\n";
  anOStream << "\n";
  anOStream << "# Generated by Open CASCADE Technology " << OCC_VERSION_STRING << "\n";
  anOStream << "\n";
  return anOStream;
}

Standard_OStream& Vrml::CommentWriter(const char* aComment, Standard_OStream& anOStream)
{
  anOStream << "# " << aComment << "\n";
  return anOStream;
}
