# Source files for IGESGraph package
set(OCCT_IGESGraph_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_IGESGraph_FILES
  IGESGraph.cxx
  IGESGraph.hpp

  IGESGraph_Color.cxx
  IGESGraph_Color.hpp
  IGESGraph_DefinitionLevel.cxx
  IGESGraph_DefinitionLevel.hpp
  IGESGraph_DrawingSize.cxx
  IGESGraph_DrawingSize.hpp
  IGESGraph_DrawingUnits.cxx
  IGESGraph_DrawingUnits.hpp
  IGESGraph_GeneralModule.cxx
  IGESGraph_GeneralModule.hpp

  IGESGraph_HighLight.cxx
  IGESGraph_HighLight.hpp
  IGESGraph_IntercharacterSpacing.cxx
  IGESGraph_IntercharacterSpacing.hpp
  IGESGraph_LineFontDefPattern.cxx
  IGESGraph_LineFontDefPattern.hpp
  IGESGraph_LineFontDefTemplate.cxx
  IGESGraph_LineFontDefTemplate.hpp
  IGESGraph_LineFontPredefined.cxx
  IGESGraph_LineFontPredefined.hpp
  IGESGraph_NominalSize.cxx
  IGESGraph_NominalSize.hpp
  IGESGraph_Pick.cxx
  IGESGraph_Pick.hpp
  IGESGraph_Protocol.cxx
  IGESGraph_Protocol.hpp
  IGESGraph_ReadWriteModule.cxx
  IGESGraph_ReadWriteModule.hpp
  IGESGraph_SpecificModule.cxx
  IGESGraph_SpecificModule.hpp
  IGESGraph_TextDisplayTemplate.cxx
  IGESGraph_TextDisplayTemplate.hpp
  IGESGraph_TextFontDef.cxx
  IGESGraph_TextFontDef.hpp
  IGESGraph_ToolColor.cxx
  IGESGraph_ToolColor.hpp
  IGESGraph_ToolDefinitionLevel.cxx
  IGESGraph_ToolDefinitionLevel.hpp
  IGESGraph_ToolDrawingSize.cxx
  IGESGraph_ToolDrawingSize.hpp
  IGESGraph_ToolDrawingUnits.cxx
  IGESGraph_ToolDrawingUnits.hpp
  IGESGraph_ToolHighLight.cxx
  IGESGraph_ToolHighLight.hpp
  IGESGraph_ToolIntercharacterSpacing.cxx
  IGESGraph_ToolIntercharacterSpacing.hpp
  IGESGraph_ToolLineFontDefPattern.cxx
  IGESGraph_ToolLineFontDefPattern.hpp
  IGESGraph_ToolLineFontDefTemplate.cxx
  IGESGraph_ToolLineFontDefTemplate.hpp
  IGESGraph_ToolLineFontPredefined.cxx
  IGESGraph_ToolLineFontPredefined.hpp
  IGESGraph_ToolNominalSize.cxx
  IGESGraph_ToolNominalSize.hpp
  IGESGraph_ToolPick.cxx
  IGESGraph_ToolPick.hpp
  IGESGraph_ToolTextDisplayTemplate.cxx
  IGESGraph_ToolTextDisplayTemplate.hpp
  IGESGraph_ToolTextFontDef.cxx
  IGESGraph_ToolTextFontDef.hpp
  IGESGraph_ToolUniformRectGrid.cxx
  IGESGraph_ToolUniformRectGrid.hpp
  IGESGraph_UniformRectGrid.cxx
  IGESGraph_UniformRectGrid.hpp
)
