#pragma once

#include <TopoDS_AlertWithShape.hpp>

DEFINE_SIMPLE_ALERT(BOPAlgo_AlertUserBreak)

DEFINE_SIMPLE_ALERT(BOPAlgo_AlertBOPNotAllowed)

DEFINE_SIMPLE_ALERT(BOPAlgo_AlertBOPNotSet)

DEFINE_SIMPLE_ALERT(BOPAlgo_AlertBuilderFailed)

DEFINE_SIMPLE_ALERT(BOPAlgo_AlertIntersectionFailed)

DEFINE_SIMPLE_ALERT(BOPAlgo_AlertMultipleArguments)

DEFINE_SIMPLE_ALERT(BOPAlgo_AlertNoFiller)

DEFINE_SIMPLE_ALERT(BOPAlgo_AlertNullInputShapes)

DEFINE_SIMPLE_ALERT(BOPAlgo_AlertPostTreatFF)

DEFINE_SIMPLE_ALERT(BOPAlgo_AlertSolidBuilderFailed)

DEFINE_SIMPLE_ALERT(BOPAlgo_AlertTooFewArguments)

DEFINE_ALERT_WITH_SHAPE(BOPAlgo_AlertBadPositioning)

DEFINE_ALERT_WITH_SHAPE(BOPAlgo_AlertEmptyShape)

DEFINE_ALERT_WITH_SHAPE(BOPAlgo_AlertNotSplittableEdge)

DEFINE_ALERT_WITH_SHAPE(BOPAlgo_AlertRemovalOfIBForEdgesFailed)

DEFINE_ALERT_WITH_SHAPE(BOPAlgo_AlertRemovalOfIBForFacesFailed)

DEFINE_ALERT_WITH_SHAPE(BOPAlgo_AlertRemovalOfIBForMDimShapes)

DEFINE_ALERT_WITH_SHAPE(BOPAlgo_AlertRemovalOfIBForSolidsFailed)

DEFINE_ALERT_WITH_SHAPE(BOPAlgo_AlertSelfInterferingShape)

DEFINE_ALERT_WITH_SHAPE(BOPAlgo_AlertShellSplitterFailed)

DEFINE_ALERT_WITH_SHAPE(BOPAlgo_AlertTooSmallEdge)

DEFINE_ALERT_WITH_SHAPE(BOPAlgo_AlertIntersectionOfPairOfShapesFailed)

DEFINE_ALERT_WITH_SHAPE(BOPAlgo_AlertBuildingPCurveFailed)

DEFINE_ALERT_WITH_SHAPE(BOPAlgo_AlertAcquiredSelfIntersection)

DEFINE_ALERT_WITH_SHAPE(BOPAlgo_AlertUnsupportedType)

DEFINE_SIMPLE_ALERT(BOPAlgo_AlertNoFacesToRemove)

DEFINE_ALERT_WITH_SHAPE(BOPAlgo_AlertUnableToRemoveTheFeature)

DEFINE_SIMPLE_ALERT(BOPAlgo_AlertRemoveFeaturesFailed)

DEFINE_ALERT_WITH_SHAPE(BOPAlgo_AlertSolidBuilderUnusedFaces)

DEFINE_ALERT_WITH_SHAPE(BOPAlgo_AlertFaceBuilderUnusedEdges)

DEFINE_ALERT_WITH_SHAPE(BOPAlgo_AlertUnableToOrientTheShape)

DEFINE_ALERT_WITH_SHAPE(BOPAlgo_AlertUnknownShape)

DEFINE_SIMPLE_ALERT(BOPAlgo_AlertNoPeriodicityRequired)

DEFINE_ALERT_WITH_SHAPE(BOPAlgo_AlertUnableToTrim)

DEFINE_ALERT_WITH_SHAPE(BOPAlgo_AlertUnableToMakeIdentical)

DEFINE_ALERT_WITH_SHAPE(BOPAlgo_AlertUnableToRepeat)

DEFINE_SIMPLE_ALERT(BOPAlgo_AlertMultiDimensionalArguments)

DEFINE_ALERT_WITH_SHAPE(BOPAlgo_AlertUnableToMakePeriodic)

DEFINE_ALERT_WITH_SHAPE(BOPAlgo_AlertUnableToGlue)

DEFINE_ALERT_WITH_SHAPE(BOPAlgo_AlertShapeIsNotPeriodic)

DEFINE_ALERT_WITH_SHAPE(BOPAlgo_AlertUnableToMakeClosedEdgeOnFace)
