# Source files for BOPAlgo package
set(OCCT_BOPAlgo_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_BOPAlgo_FILES
  BOPAlgo_Algo.cxx
  BOPAlgo_Algo.hpp
  BOPAlgo_ArgumentAnalyzer.cxx
  BOPAlgo_ArgumentAnalyzer.hpp
  BOPAlgo_ToolsProvider.cxx
  BOPAlgo_ToolsProvider.hpp
  BOPAlgo_BOP.cxx
  BOPAlgo_BOP.hpp
  BOPAlgo_Builder.cxx
  BOPAlgo_Builder.hpp
  BOPAlgo_Builder_1.cxx
  BOPAlgo_Builder_2.cxx
  BOPAlgo_Builder_3.cxx
  BOPAlgo_Builder_4.cxx
  BOPAlgo_BuilderArea.cxx
  BOPAlgo_BuilderArea.hpp
  BOPAlgo_BuilderFace.cxx
  BOPAlgo_BuilderFace.hpp
  BOPAlgo_BuilderShape.hpp
  BOPAlgo_BuilderSolid.cxx
  BOPAlgo_BuilderSolid.hpp
  BOPAlgo_CheckerSI.cxx
  BOPAlgo_CheckerSI.hpp
  BOPAlgo_CheckerSI_1.cxx
  BOPAlgo_CheckResult.cxx
  BOPAlgo_CheckResult.hpp

  BOPAlgo_MakeConnected.cxx
  BOPAlgo_MakeConnected.hpp
  BOPAlgo_MakePeriodic.cxx
  BOPAlgo_MakePeriodic.hpp
  BOPAlgo_MakerVolume.cxx
  BOPAlgo_MakerVolume.hpp
  BOPAlgo_Operation.hpp
  BOPAlgo_Options.cxx
  BOPAlgo_Options.hpp
  
  BOPAlgo_PaveFiller.cxx
  BOPAlgo_PaveFiller.hpp
  BOPAlgo_PaveFiller_1.cxx
  BOPAlgo_PaveFiller_2.cxx
  BOPAlgo_PaveFiller_3.cxx
  BOPAlgo_PaveFiller_4.cxx
  BOPAlgo_PaveFiller_5.cxx
  BOPAlgo_PaveFiller_6.cxx
  BOPAlgo_PaveFiller_7.cxx
  BOPAlgo_PaveFiller_8.cxx
  BOPAlgo_PaveFiller_9.cxx
  BOPAlgo_PaveFiller_10.cxx
  BOPAlgo_PaveFiller_11.cxx
  
  BOPAlgo_PBuilder.hpp
  BOPAlgo_PPaveFiller.hpp
  
  BOPAlgo_RemoveFeatures.cxx
  BOPAlgo_RemoveFeatures.hpp
  BOPAlgo_Section.cxx
  BOPAlgo_Section.hpp
  BOPAlgo_SectionAttribute.hpp
  BOPAlgo_ShellSplitter.cxx
  BOPAlgo_ShellSplitter.hpp
  BOPAlgo_Tools.cxx
  BOPAlgo_Tools.hpp
  BOPAlgo_WireEdgeSet.hpp
  BOPAlgo_WireSplitter.cxx
  BOPAlgo_WireSplitter.hpp
  BOPAlgo_WireSplitter_1.cxx
  BOPAlgo_CellsBuilder.cxx
  BOPAlgo_CellsBuilder.hpp
  BOPAlgo_GlueEnum.hpp
  BOPAlgo_Splitter.hpp
  BOPAlgo_Splitter.cxx
  BOPAlgo_Alerts.hpp
  BOPAlgo_BOPAlgo_msg.hpp
)
