# Source files for gp package
set(OCCT_gp_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_gp_FILES
  gp.cxx
  gp.hpp
  gp_Ax1.cxx
  gp_Ax1.hpp
  gp_Ax2.cxx
  gp_Ax2.hpp
  gp_Ax2d.cxx
  gp_Ax2d.hpp
  gp_Ax3.cxx
  gp_Ax3.hpp
  gp_Ax22d.cxx
  gp_Ax22d.hpp
  gp_Circ.cxx
  gp_Circ.hpp
  gp_Circ2d.cxx
  gp_Circ2d.hpp
  gp_Cone.cxx
  gp_Cone.hpp
  gp_Cylinder.cxx
  gp_Cylinder.hpp
  gp_Dir.cxx
  gp_Dir.hpp
  gp_Dir2d.cxx
  gp_Dir2d.hpp
  gp_Elips.cxx
  gp_Elips.hpp
  gp_Elips2d.cxx
  gp_Elips2d.hpp
  gp_EulerSequence.hpp
  gp_GTrsf.cxx
  gp_GTrsf.hpp
  gp_GTrsf2d.cxx
  gp_GTrsf2d.hpp
  gp_Hypr.cxx
  gp_Hypr.hpp
  gp_Hypr2d.cxx
  gp_Hypr2d.hpp
  gp_Lin.cxx
  gp_Lin.hpp
  gp_Lin2d.cxx
  gp_Lin2d.hpp
  gp_Mat.cxx
  gp_Mat.hpp
  gp_Mat2d.cxx
  gp_Mat2d.hpp
  gp_Parab.cxx
  gp_Parab.hpp
  gp_Parab2d.cxx
  gp_Parab2d.hpp
  gp_Pln.cxx
  gp_Pln.hpp
  gp_Pnt.cxx
  gp_Pnt.hpp
  gp_Pnt2d.cxx
  gp_Pnt2d.hpp
  gp_Quaternion.cxx
  gp_Quaternion.hpp
  gp_QuaternionNLerp.hpp
  gp_QuaternionSLerp.hpp
  gp_Sphere.cxx
  gp_Sphere.hpp
  gp_Torus.cxx
  gp_Torus.hpp
  gp_Trsf.cxx
  gp_Trsf.hpp
  gp_Trsf2d.cxx
  gp_Trsf2d.hpp
  gp_TrsfForm.hpp
  gp_TrsfNLerp.hpp
  gp_Vec.cxx
  gp_Vec.hpp
  gp_Vec2d.cxx
  gp_Vec2d.hpp

  gp_VectorWithNullMagnitude.hpp
  gp_XY.hpp
  gp_XYZ.cxx
  gp_XYZ.hpp
)
