#include <AppDef_MyGradientbisOfBSplineCompute.hpp>

#include <Standard_OutOfRange.hpp>
#include <StdFail_NotDone.hpp>
#include <AppDef_MultiLine.hpp>
#include <AppDef_MyLineTool.hpp>
#include <AppDef_ParLeastSquareOfMyGradientbisOfBSplineCompute.hpp>
#include <AppDef_ResConstraintOfMyGradientbisOfBSplineCompute.hpp>
#include <AppDef_ParFunctionOfMyGradientbisOfBSplineCompute.hpp>
#include <AppDef_Gradient_BFGSOfMyGradientbisOfBSplineCompute.hpp>
#include <AppParCurves_MultiCurve.hpp>

#define MultiLine AppDef_MultiLine
#define MultiLine_hxx <AppDef_MultiLine.hpp>
#define ToolLine AppDef_MyLineTool
#define ToolLine_hxx <AppDef_MyLineTool.hpp>
#define AppParCurves_ParLeastSquare AppDef_ParLeastSquareOfMyGradientbisOfBSplineCompute
#define AppParCurves_ParLeastSquare_hxx <AppDef_ParLeastSquareOfMyGradientbisOfBSplineCompute.hpp>
#define AppParCurves_ResConstraint AppDef_ResConstraintOfMyGradientbisOfBSplineCompute
#define AppParCurves_ResConstraint_hxx <AppDef_ResConstraintOfMyGradientbisOfBSplineCompute.hpp>
#define AppParCurves_ParFunction AppDef_ParFunctionOfMyGradientbisOfBSplineCompute
#define AppParCurves_ParFunction_hxx <AppDef_ParFunctionOfMyGradientbisOfBSplineCompute.hpp>
#define AppParCurves_Gradient_BFGS AppDef_Gradient_BFGSOfMyGradientbisOfBSplineCompute
#define AppParCurves_Gradient_BFGS_hxx <AppDef_Gradient_BFGSOfMyGradientbisOfBSplineCompute.hpp>
#define AppParCurves_Gradient AppDef_MyGradientbisOfBSplineCompute
#define AppParCurves_Gradient_hxx <AppDef_MyGradientbisOfBSplineCompute.hpp>
#include <AppParCurves_Gradient.hpp>
