# Source files for AppDef package
set(OCCT_AppDef_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_AppDef_FILES

  AppDef_BSpGradient_BFGSOfMyBSplGradientOfBSplineCompute.hpp
  AppDef_BSpGradient_BFGSOfMyBSplGradientOfBSplineCompute_0.cxx
  AppDef_BSplineCompute.hpp
  AppDef_BSplineCompute_0.cxx
  AppDef_BSpParFunctionOfMyBSplGradientOfBSplineCompute.hpp
  AppDef_BSpParFunctionOfMyBSplGradientOfBSplineCompute_0.cxx
  AppDef_BSpParLeastSquareOfMyBSplGradientOfBSplineCompute.hpp
  AppDef_BSpParLeastSquareOfMyBSplGradientOfBSplineCompute_0.cxx
  AppDef_Compute.hpp
  AppDef_Compute_0.cxx
  AppDef_Gradient_BFGSOfMyGradientbisOfBSplineCompute.hpp
  AppDef_Gradient_BFGSOfMyGradientbisOfBSplineCompute_0.cxx
  AppDef_Gradient_BFGSOfMyGradientOfCompute.hpp
  AppDef_Gradient_BFGSOfMyGradientOfCompute_0.cxx
  AppDef_Gradient_BFGSOfTheGradient.hpp
  AppDef_Gradient_BFGSOfTheGradient_0.cxx

  AppDef_LinearCriteria.cxx
  AppDef_LinearCriteria.hpp
  AppDef_MultiLine.cxx
  AppDef_MultiLine.hpp
  AppDef_MultiPointConstraint.cxx
  AppDef_MultiPointConstraint.hpp
  AppDef_MyBSplGradientOfBSplineCompute.hpp
  AppDef_MyBSplGradientOfBSplineCompute_0.cxx
  AppDef_MyGradientbisOfBSplineCompute.hpp
  AppDef_MyGradientbisOfBSplineCompute_0.cxx
  AppDef_MyGradientOfCompute.hpp
  AppDef_MyGradientOfCompute_0.cxx
  AppDef_MyLineTool.cxx
  AppDef_MyLineTool.hpp
  AppDef_ParFunctionOfMyGradientbisOfBSplineCompute.hpp
  AppDef_ParFunctionOfMyGradientbisOfBSplineCompute_0.cxx
  AppDef_ParFunctionOfMyGradientOfCompute.hpp
  AppDef_ParFunctionOfMyGradientOfCompute_0.cxx
  AppDef_ParFunctionOfTheGradient.hpp
  AppDef_ParFunctionOfTheGradient_0.cxx
  AppDef_ParLeastSquareOfMyGradientbisOfBSplineCompute.hpp
  AppDef_ParLeastSquareOfMyGradientbisOfBSplineCompute_0.cxx
  AppDef_ParLeastSquareOfMyGradientOfCompute.hpp
  AppDef_ParLeastSquareOfMyGradientOfCompute_0.cxx
  AppDef_ParLeastSquareOfTheGradient.hpp
  AppDef_ParLeastSquareOfTheGradient_0.cxx
  AppDef_ResConstraintOfMyGradientbisOfBSplineCompute.hpp
  AppDef_ResConstraintOfMyGradientbisOfBSplineCompute_0.cxx
  AppDef_ResConstraintOfMyGradientOfCompute.hpp
  AppDef_ResConstraintOfMyGradientOfCompute_0.cxx
  AppDef_ResConstraintOfTheGradient.hpp
  AppDef_ResConstraintOfTheGradient_0.cxx
  AppDef_SmoothCriterion.cxx
  AppDef_SmoothCriterion.hpp
  AppDef_TheFunction.hpp
  AppDef_TheFunction_0.cxx
  AppDef_TheGradient.hpp
  AppDef_TheGradient_0.cxx
  AppDef_TheLeastSquares.hpp
  AppDef_TheLeastSquares_0.cxx
  AppDef_TheResol.hpp
  AppDef_TheResol_0.cxx
  AppDef_Variational.cxx
  AppDef_Variational.hpp
)
