# Source files for GeomFill package
set(OCCT_GeomFill_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_GeomFill_FILES
  GeomFill.cxx
  GeomFill.hpp
  GeomFill_ApproxStyle.hpp
  GeomFill_AppSurf.hpp
  GeomFill_AppSurf_0.cxx
  GeomFill_AppSweep.hpp
  GeomFill_AppSweep_0.cxx

  GeomFill_BezierCurves.cxx
  GeomFill_BezierCurves.hpp
  GeomFill_Boundary.cxx
  GeomFill_Boundary.hpp
  GeomFill_BoundWithSurf.cxx
  GeomFill_BoundWithSurf.hpp
  GeomFill_BSplineCurves.cxx
  GeomFill_BSplineCurves.hpp
  GeomFill_CircularBlendFunc.cxx
  GeomFill_CircularBlendFunc.hpp
  GeomFill_ConstantBiNormal.cxx
  GeomFill_ConstantBiNormal.hpp
  GeomFill_ConstrainedFilling.cxx
  GeomFill_ConstrainedFilling.hpp
  GeomFill_Coons.cxx
  GeomFill_Coons.hpp
  GeomFill_CoonsAlgPatch.cxx
  GeomFill_CoonsAlgPatch.hpp
  GeomFill_CornerState.cxx
  GeomFill_CornerState.hpp
  GeomFill_CorrectedFrenet.cxx
  GeomFill_CorrectedFrenet.hpp
  GeomFill_CurveAndTrihedron.cxx
  GeomFill_CurveAndTrihedron.hpp
  GeomFill_Curved.cxx
  GeomFill_Curved.hpp
  GeomFill_Darboux.cxx
  GeomFill_Darboux.hpp
  GeomFill_DegeneratedBound.cxx
  GeomFill_DegeneratedBound.hpp
  GeomFill_DiscreteTrihedron.cxx
  GeomFill_DiscreteTrihedron.hpp
  GeomFill_DraftTrihedron.cxx
  GeomFill_DraftTrihedron.hpp
  GeomFill_EvolvedSection.cxx
  GeomFill_EvolvedSection.hpp
  GeomFill_Filling.cxx
  GeomFill_Filling.hpp
  GeomFill_FillingStyle.hpp
  GeomFill_Fixed.cxx
  GeomFill_Fixed.hpp
  GeomFill_Frenet.cxx
  GeomFill_Frenet.hpp
  GeomFill_FunctionDraft.cxx
  GeomFill_FunctionDraft.hpp
  GeomFill_FunctionGuide.cxx
  GeomFill_FunctionGuide.hpp
  GeomFill_Generator.cxx
  GeomFill_Generator.hpp
  GeomFill_GuideTrihedronAC.cxx
  GeomFill_GuideTrihedronAC.hpp
  GeomFill_GuideTrihedronPlan.cxx
  GeomFill_GuideTrihedronPlan.hpp

  GeomFill_Line.cxx
  GeomFill_Line.hpp
  GeomFill_LocationDraft.cxx
  GeomFill_LocationDraft.hpp
  GeomFill_LocationGuide.cxx
  GeomFill_LocationGuide.hpp
  GeomFill_LocationLaw.cxx
  GeomFill_LocationLaw.hpp
  GeomFill_LocFunction.cxx
  GeomFill_LocFunction.hpp
  GeomFill_NSections.cxx
  GeomFill_NSections.hpp
  GeomFill_Pipe.cxx
  GeomFill_Pipe.hpp
  GeomFill_PipeError.hpp
  GeomFill_PlanFunc.cxx
  GeomFill_PlanFunc.hpp
  GeomFill_PolynomialConvertor.cxx
  GeomFill_PolynomialConvertor.hpp
  GeomFill_Profiler.cxx
  GeomFill_Profiler.hpp
  GeomFill_QuasiAngularConvertor.cxx
  GeomFill_QuasiAngularConvertor.hpp
  GeomFill_SectionGenerator.cxx
  GeomFill_SectionGenerator.hpp
  GeomFill_SectionLaw.cxx
  GeomFill_SectionLaw.hpp
  GeomFill_SectionPlacement.cxx
  GeomFill_SectionPlacement.hpp

  GeomFill_SimpleBound.cxx
  GeomFill_SimpleBound.hpp
  GeomFill_SnglrFunc.cxx
  GeomFill_SnglrFunc.hpp
  GeomFill_Stretch.cxx
  GeomFill_Stretch.hpp
  GeomFill_Sweep.cxx
  GeomFill_Sweep.hpp
  GeomFill_SweepFunction.cxx
  GeomFill_SweepFunction.hpp
  GeomFill_SweepSectionGenerator.cxx
  GeomFill_SweepSectionGenerator.hpp
  GeomFill_Tensor.cxx
  GeomFill_Tensor.hpp
  GeomFill_TgtField.cxx
  GeomFill_TgtField.hpp
  GeomFill_TgtOnCoons.cxx
  GeomFill_TgtOnCoons.hpp
  GeomFill_Trihedron.hpp
  GeomFill_TrihedronLaw.cxx
  GeomFill_TrihedronLaw.hpp
  GeomFill_TrihedronWithGuide.cxx
  GeomFill_TrihedronWithGuide.hpp
  GeomFill_UniformSection.cxx
  GeomFill_UniformSection.hpp
)
