# Source files for BVH package
set(OCCT_BVH_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_BVH_FILES
  BVH.cxx
  BVH_BinnedBuilder.hpp
  BVH_Box.hpp
  BVH_BoxSet.hpp
  BVH_Builder.hpp
  BVH_Builder3d.hpp
  BVH_BuildQueue.hpp
  BVH_BuildThread.hpp
  BVH_BuildThread.cxx
  BVH_Constants.hpp
  BVH_Distance.hpp
  BVH_DistanceField.hpp
  BVH_DistanceField_1.hpp
  BVH_Geometry.hpp
  BVH_IndexedBoxSet.hpp
  BVH_LinearBuilder.hpp
  BVH_Object.hpp
  BVH_ObjectSet.hpp
  BVH_PairDistance.hpp
  BVH_PrimitiveSet.hpp
  BVH_PrimitiveSet3d.hpp
  BVH_Properties.cxx
  BVH_Properties.hpp
  BVH_QueueBuilder.hpp
  BVH_Ray.hpp
  BVH_Set.hpp
  BVH_Sorter.hpp
  BVH_QuickSorter.hpp
  BVH_RadixSorter.hpp
  BVH_SpatialMedianBuilder.hpp
  BVH_SweepPlaneBuilder.hpp
  BVH_Tools.hpp
  BVH_Traverse.hpp
  BVH_Traverse_1.hpp
  BVH_Tree.hpp
  BVH_BinaryTree.hpp
  BVH_QuadTree.hpp
  BVH_Triangulation.hpp
  BVH_Types.hpp
)
