# Source files for BRepLib package
set(OCCT_BRepLib_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_BRepLib_FILES
  BRepLib.cxx
  BRepLib.hpp
  BRepLib_1.cxx
  BRepLib_CheckCurveOnSurface.cxx
  BRepLib_CheckCurveOnSurface.hpp
  BRepLib_Command.cxx
  BRepLib_Command.hpp
  BRepLib_EdgeError.hpp
  BRepLib_FindSurface.cxx
  BRepLib_FindSurface.hpp
  BRepLib_FuseEdges.cxx
  BRepLib_FuseEdges.hpp
  BRepLib_MakeEdge.cxx
  BRepLib_MakeEdge.hpp
  BRepLib_MakeEdge2d.cxx
  BRepLib_MakeEdge2d.hpp
  BRepLib_MakeFace.cxx
  BRepLib_MakeFace.hpp
  BRepLib_MakePolygon.cxx
  BRepLib_MakePolygon.hpp
  BRepLib_MakeShape.cxx
  BRepLib_MakeShape.hpp
  BRepLib_MakeShell.cxx
  BRepLib_MakeShell.hpp
  BRepLib_MakeSolid.cxx
  BRepLib_MakeSolid.hpp
  BRepLib_MakeVertex.cxx
  BRepLib_MakeVertex.hpp
  BRepLib_MakeWire.cxx
  BRepLib_MakeWire.hpp
  BRepLib_MakeWire_1.cxx
  BRepLib_PointCloudShape.hpp
  BRepLib_PointCloudShape.cxx
  BRepLib_ShapeModification.hpp
  BRepLib_ToolTriangulatedShape.hpp
  BRepLib_ToolTriangulatedShape.cxx
  BRepLib_ValidateEdge.cxx
  BRepLib_ValidateEdge.hpp
)
