#pragma once

#define RESUNDEF (-100)
#define RESNEWSHA2 (-12)
#define RESNEWSHA1 (-11)
#define RESNEWCOM (-3)
#define RESNEWSOL (-2)
#define RESNEWSHE (-1)
#define RESNULL (0)
#define RESSHAPE1 (1)
#define RESSHAPE2 (2)
#define RESSHAPE12 (3)
#define RESFACE1 (11)
#define RESFACE2 (12)

#define SHEUNDEF (-100)
#define SHEAUCU (-1)
#define SHECLASCOUR (1)
#define SHECLASAUTR (2)
#define SHECLASTOUS (3)
#define SHEGARDCOUR (4)
#define SHEGARDAUTR (5)
#define SHEGARDTOUS (6)
