# Source files for DrawTrSurf package
set(OCCT_DrawTrSurf_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_DrawTrSurf_FILES
  DrawTrSurf.cxx
  DrawTrSurf.hpp
  DrawTrSurf_BezierCurve.cxx
  DrawTrSurf_BezierCurve.hpp
  DrawTrSurf_BezierCurve2d.cxx
  DrawTrSurf_BezierCurve2d.hpp
  DrawTrSurf_BezierSurface.cxx
  DrawTrSurf_BezierSurface.hpp
  DrawTrSurf_BSplineCurve.cxx
  DrawTrSurf_BSplineCurve.hpp
  DrawTrSurf_BSplineCurve2d.cxx
  DrawTrSurf_BSplineCurve2d.hpp
  DrawTrSurf_BSplineSurface.cxx
  DrawTrSurf_BSplineSurface.hpp
  DrawTrSurf_Curve.cxx
  DrawTrSurf_Curve.hpp
  DrawTrSurf_Curve2d.cxx
  DrawTrSurf_Curve2d.hpp
  DrawTrSurf_Debug.cxx
  DrawTrSurf_Drawable.cxx
  DrawTrSurf_Drawable.hpp
  DrawTrSurf_Params.hpp
  DrawTrSurf_Point.cxx
  DrawTrSurf_Point.hpp
  DrawTrSurf_Polygon2D.cxx
  DrawTrSurf_Polygon2D.hpp
  DrawTrSurf_Polygon3D.cxx
  DrawTrSurf_Polygon3D.hpp
  DrawTrSurf_Surface.cxx
  DrawTrSurf_Surface.hpp
  DrawTrSurf_Triangulation.cxx
  DrawTrSurf_Triangulation.hpp
  DrawTrSurf_Triangulation2D.cxx
  DrawTrSurf_Triangulation2D.hpp
)
